### ISSUE TITLE
Automated Docker Image Build

### ISSUE THREAD

**Issue by misilot** [grokability/snipe-it#10065]
### Snipe-IT Version

latest

### Operating System

docker

### Web Server

apache

### PHP Version

latest

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

N/A

### Describe the solution you'd like A clear and concise description of what you want to happen.

Automate utilizing github actions the publishing of docker images on release.

 
https://docs.github.com/en/actions/guides/publishing-docker-images

**Comment by snipe** [comment]
Unfortunately, since Dockerhub took away automated build-on-push a month or so ago, v5.2.0 isn't on Dockerhub. We just had to upgrade to Pro (which is complete bullshit since this is a public, open source repo) to re-enable auto-building, but we're currently unable to re-push that tag. 

You should be able to run `docker pull snipe/snipe-it:latest` for now until we get v5.2.0 pushed out manually, since there's no way I can find to trigger it via the web UI, and my local has a ton of artifacts we wouldn't want in that tagged release. :(

Before:
<img width="716" alt="Screen Shot 2021-09-10 at 5 26 43 PM" src="https://user-images.githubusercontent.com/197404/132930793-ec07acfe-1b28-4eb2-869f-4f29413ff1e3.png">

After:
<img width="718" alt="Screen Shot 2021-09-10 at 5 49 22 PM" src="https://user-images.githubusercontent.com/197404/132930823-8c8fdb0c-3d2d-4cb8-9b77-61f543a87528.png">

**Comment by misilot** [comment]
Thanks for looking at it @snipe! I wasn't sure if setting it up as a github action to do the pushing would help side step that the requirement to utilize a Pro account.

**Comment by Smankusors** [comment]
btw, have you guys considered the Docker Open Source Program?

https://www.docker.com/community/open-source/application

<blockquote><img src="https://www.docker.com/sites/default/files/social/docker_facebook_share.png" width="48" align="right"><div><strong><a href="https://www.docker.com/community/open-source/application">Docker Open Source Program</a></strong></div></blockquote>

**Comment by snipe** [comment]
Of course, @Smankusors - we do not meet their qualifications though. :(

**Comment by fabricat** [comment]
Thanks for the explanations.
I am looking forward for the `v5.2.0` tag to be published 😃 
Will this issue get updated when this happens?

**Comment by back-2-95** [comment]
You could have Github Action to build, test & push the image?
