### ISSUE TITLE
Connect one file to multiple assets

### ISSUE THREAD

**Issue by patwia** [grokability/snipe-it#10196]
### Snipe-IT Version

5.2.0

### Operating System

Ubuntu 20.10

### Web Server

Apache

### PHP Version

7.4.9

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

In order to prevent bulking storage on server I suggest to add a possibility to connect one file to multiple assets; e.g. we have 10 laptops bought in one order and I have to add 10 copies of one invoice to 10 assets which will bulk storage on server really fast.

### Describe the solution you'd like A clear and concise description of what you want to happen.

I expect some mechanism, that will be able to connect one uploaded file to multiple assets or possibility to attach files to order number maybe?

**Comment by pixelblut** [comment]
I have a similar situation, where i'm migrating a hacked-together and undocumented inventory system written by someone who quit 3 years ago to snipe-it. I've got all my data migrated, but the attached files still give me a headache.

e.g. we have 25 of the same type of device, instead of having to attach the datasheet to each device, why not let us attach it also to models? Or at least a bulk upload feature for assets which then are hardlinked in the filesystem like @patwia suggested.

i know i could just hardlink the files in the filesystem with something like jdupes myself to preserve disk space but my users (and me ;)) are kinda annoyed that they have to upload each file 25 times instead of just once.

**Comment by mikeroq** [comment]
@pixelblut they recently added file uploads to asset models. They show as additional files when viewing an asset. 

In version 6.0.6.

**Comment by pixelblut** [comment]
@mikeroq Thanks for the info, guess i have to update
