### ISSUE TITLE
Failed to load images

### ISSUE THREAD

**Issue by ZaidIsmailOdeh** [grokability/snipe-it#10278]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

After successfully upload the images, it can't be shown and when I press on the image it self "failed to load image" error appears, 

### Reproduction steps

1. Upload image
2. Press on image

### Expected behavior

to show the image

### Screenshots

![image](https://user-images.githubusercontent.com/30932616/140534859-2f4d4237-25db-46b8-be02-d0876b7a20bf.png)

### Snipe-IT Version

5.1.5 build 6029 (gb8c356443)

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

7.3.31-1~deb10u1

### Operating System

Windows

### Browser

Google Chrome

### Version

Version 95.0.4638.69 (Official Build) (64-bit)

### Error messages

```shell
No Extra message in the debug mode
```

### Additional context

Fresh install 
TurnKey Snipt It
TurnKey installation 
Hyber-V installation
No error while installation
No manual edit in the database

**Comment by Midnex** [comment]
From the Common issues page

404 Errors on Javascript, CSS or Image Files

This happens when the URL you've set in your configuration is not the actual URL your installation is using, for example if you had http://snipe.local as your URL in your configuration, but you are accessing the page from http://snipe-it.local. 

This should resolve it
https://snipe-it.readme.io/docs/common-issues

**Comment by snipe** [comment]
This is almost always caused by an incorrect `APP_URL` setting in your `.env`. The protocol is *always* required in the `APP_URL`, [per the documentation](https://snipe-it.readme.io/docs/configuration#required-basic-app-settings) and [Common Issues](https://snipe-it.readme.io/docs/common-issues#broken-barcodes). 🙂

<img width="807" alt="Screen Shot 2022-03-21 at 3 12 09 PM" src="https://user-images.githubusercontent.com/197404/159291713-6f99277c-6b55-493b-939a-2ab7b630c1f5.png">

**Comment by pedramaghaii** [comment]
hi your problem is php, after install packages on OS is Done
sudo apt install php-{opcache,pdo,bcmath,bz2,calendar,ctype,exif,ffi,fileinfo,ftp,gd,iconv,intl,json,mbstring,mysqli,phar,posix,readline,shmop,sockets,sysvmsg,sysvsem,sysvshm,tokenizer,zip,curl,ldap} php-cli git unzip
