### ISSUE TITLE
change language bug(?)

### ISSUE THREAD

**Issue by Xiayu8** [grokability/snipe-it#10445]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

hi there,

i am new to SnipeIT and i dont know if this "problem" is a bug or just misunderstanding.

I changed the language in my profile and it changed without problems.
More or less everything changed as expected, except "Asset Tag" (list all assets screen)
That was the first thing i noticed but my intention was to change the displayed words to my own needings.
I read about MVC structure so i was confident enough to find a way to change the displayed words.

I found the "lang/de"-file and edited the "general.php"-file.
default entry: " 'id' => 'Id' "
changed entry: " 'id' => 'IDD' " (just for testing)
i reloaded the page and "Id" changed to "IDD", perfect.

next i changed the entry "asset_tag".
default entry: " 'asset_tag' => 'Kennzeichnung' (seems to be already broken or not working as intended, because it shows "Asset Tag" instead of "Kennzeichnung")
changed entry: " 'asset_tag' => 'test' "
reloaded the page and nothing happend. 

After further "investigations" i found out that some entries are changeable and others are not.

Is this bugged or am i misunderstanding something/everything?

thanks in advance.

### Reproduction steps

1.open general.php (in language folders)
2.edit entry (example: 'asset_tag' => 'TEST')
3.save file
4.reload page
...

### Expected behavior

"Asset Tag" should change to "Test"

### Snipe-IT Version

v5.3.3 - build 6517 (master)

### Operating System

Ubuntu 20.04

### Web Server

Apache

### PHP Version

7.4.3

### Operating System

Ubuntu 20.04

### Browser

Firefox

### Version

95

**Comment by nuraeil** [comment]
See #10441

I am currently still working on having everything moved to localized strings: #10264

But it takes a lot of time and effort to go through each and every file to find all the non-localized strings. And as I am currently on vacation, I will not have any time until early January to continue working on it.

The ones you mentioned above were already fixed inside the PR.

But keep in mind that even though they were put into a localized string, they will not be automatically translated into the specific language as the translations have to be made through the Crowdin platform after the PR is merged into the dev branch and the dev branch into master. 

The process for the localizing strings is the following:

Example:

```html
This is a warning message.
```
The string inside the code is replaced with a 

```php
{{ trans('general.warning') }}
```
and in the lang/en/general.php you will have the

```php
'warning' => 'This is a warning message.'
```

The language file differs as you probably have seen in the folder structure.

Afterwards a translation can be submitted through the Crowdin platform in order to have a translation for the specific non-localized string.

Hope that cleared most things up.

Feel free to browse through the changed files in my PR commits to view what will be translatable after the merge, which is yet without an ETA.

**Comment by adagioajanes** [comment]
> See #10441

I think you MIGHT have referred to the wrong issue number. ;)

**Comment by nuraeil** [comment]
> > See #10441
> 
> I think you MIGHT have referred to the wrong issue number. ;)

Sometimes Github is quite weird... I copy-pasted the issue number, I pressed enter for the next line but Github wanted to auto-complete and I did not notice in time >_> The issue I meant was #10242

Thanks for pointing that out!

**Comment by Xiayu8** [comment]
Thanks for the real quick response.

I think i understand it now. Thanks for clearing that up.
i wish you nice holidays.
