### ISSUE TITLE
Fieldset used by categories 

### ISSUE THREAD

**Issue by fentmturner** [grokability/snipe-it#10541]
### Snipe-IT Version

5.3.7

### Operating System

Windows

### Web Server

IIS

### PHP Version

7.4.27

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

Can the ability to have fieldsets be used by categories be added?
My district is testing out Snipe-IT as a replacement for our current asset manager. 
We have over 130 different models of assets in our inventory and we need to have custom fields/fieldsets on these assets.
It is a deal breaker if we cannot just have custom fields/ fieldsets used by categories, especially as we purchase new assets that are different from ones we have in the district currently. 
I would assume this would require adding the option to select the category when adding an asset, which would be beneficial 

### Describe the solution you'd like A clear and concise description of what you want to happen.

The ability to add fieldsets/ custom fields to categories in addition to models
Ability to choose the category when creating an asset

**Comment by ccj9874** [comment]
When you create a new asset, you can create a new asset model and choose the category as well as the custom fieldset when creating that asset model. Why do you need fieldsets applied to the entire category instead of just the model?
![image](https://user-images.githubusercontent.com/91554371/150591205-826bdbcf-6ee8-40c2-b480-348b9ad233c7.png)

**Comment by fentmturner** [comment]
I work for a K-12 district and we have over 100 different types of models when you look at all of our assets. 
A majority of which are bond purchased so we would like to tag them with which bond they were purchased with. 
Also tracking which IP phone has which extension installed.
Plan on bulk uploading assets to avoid having to go in and create all the assets and models individually.
Unless there is a way to bulk upload models and have them link to fieldsets at the same time. 
Categories would be easier with this many models and adding more in the future

**Comment by ccj9874** [comment]
I do agree that there needs to be a way to link fieldsets when doing a bulk import, as that was annoying. 

However, I think a majority of that could be resolved with fieldsets for models. You can create a field called "Bond ID/Name" or something like that and add that field to every fieldset so that no matter what fieldset you choose, you can have a field that allows you to keep track of the bonds. You can also add a "Phone Extension" field to any fieldsets you use for phone models. 

My company has over 300 device models and the biggest issue I had was just the bulk import not having the fieldsets attached. My temporary solution was to create a "General" fieldset with all fields attached and then applying it to every model just so that they can have all the information needed in case I don't have a particular fieldset for them.

**Comment by snipe** [comment]
Bulk imports do import custom fields, as long as they're named correctly, and it's straightforward enough to bulk edit models to add whatever fieldset you need.
