### ISSUE TITLE
Can't install Snipe-it 5.3.8 in sub-directory

### ISSUE THREAD

**Issue by GaneshKandu** [grokability/snipe-it#10577]
### Snipe-IT Version

5.3.8

### Operating System

Linux CentOS

### Web Server

Apache

### PHP Version

PHP 7.4.25

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

Hi,

I am trying to install Snipe-it 5.3.8 in sub-directory Ex. ```http://mydomain.com/subdirectory/snipeit/public```
but Snipe-it looking css, js and images in root ```http://mydomain.com``` but they are present at ```http://mydomain.com/subdirectory/snipeit/public``` therefore it causing 404 error

### Describe the solution you'd like A clear and concise description of what you want to happen.

you can set other files and folder as ```data directory``` except public any where in non accessible directory
and public for any where in web accessible

**Comment by GaneshKandu** [comment]
@uberbrady you able to reproduce this bug ?

**Comment by chrisgraf** [comment]
Same here after an Update via php upgrade.php. It used to work before (I don't know the exact version)

**Comment by snipe** [comment]
Can you both tell me what you have set as your `APP_URL` in your .env?

**Comment by chrisgraf** [comment]
It's `APP_URL=https://<domainname>/snipeit` for me

**Comment by GaneshKandu** [comment]
```APP_URL=http://mydomain.com/subdirectory/snipeit/public```

**Comment by uberbrady** [comment]
`public` should not be in there.

**Comment by GaneshKandu** [comment]
Still not working

**Comment by snipe** [comment]
Thanks for the feedback. We've made it abundantly clear that Snipe-IT [does not want to be run in a subdirectory](https://snipe-it.readme.io/docs/subdirectories). We're working on fixing the issue here, but at the end of the day, the better answer is: Just Don't If You Can Avoid It.

We'll update this GH issue with our progress - please hang tight.

**Comment by chrisgraf** [comment]
I know, but as it worked until now I didn't expect this to break. For us running it on a subdomain is not an option. Thanks a lot for your effort! Is there an easy way to downgrade again in the meantime?

**Comment by snipe** [comment]
We made some changes to how root urls work in order to handle a laravel-level security issue.  Brady has been assigned to this issue and I’m confident he’ll get it sorted.

**Comment by savornicesei** [comment]
I can confirm the issue. As a workaround (since I'm running Snipe-IT in a Bitnami LAMPP env. limited to localhost) I've set 
`APP_ALLOW_INSECURE_HOSTS=true` in `.env` file, based on the changes made in [this commit](https://github.com/snipe/snipe-it/commit/70648dedd3d152e5115b0d8ac39cc848ab73e213).

Thanks.

**Comment by uberbrady** [comment]
Excellent workaround, @savornicesei - yes, that will at least disable the code that I added until I can get it all sorted out. I can’t believe that I didn’t think of mentioning it earlier, thank you!

It’s tough for me to work on because I don’t have a good test environment for subdirectories right now so I’m kinda struggling.

The test I want to see (with `APP_ALLOW_INSECURE_HOSTS` **unset**, of course), is this:

Changing this line:

https://github.com/snipe/snipe-it/blob/db0a078c0b585956a24b0594ee47606136ef638a/app/Providers/AppServiceProvider.php#L52

To instead say something like:

```
\URL::forceRootUrl(config(‘app.url’));
```

I’m wondering if that makes it work any better?

**Comment by savornicesei** [comment]
@uberbrady  With `\URL::forceRootUrl(config('app.url'));`  and `APP_ALLOW_INSECURE_HOSTS=false` Snipe-It configured as a subdirectory works fine.

**Comment by uberbrady** [comment]
I'll try and get a PR up with this today. Thanks for the troubleshooting help, @savornicesei !

**Comment by savornicesei** [comment]
@uberbrady No problem. Glad to help! Let me know if and when you need additional subdirectory testing :)
