### ISSUE TITLE
Getting 500 Server Error after Upgrade

### ISSUE THREAD

**Issue by GCHPX** [grokability/snipe-it#10807]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

![image](https://user-images.githubusercontent.com/19952514/157451036-327ce344-ff31-4921-850c-c9bbeb4752ad.png)

Getting an 500 Server Error after upgrading to the newest version over: 

sudo -u www-data php update.php

### Reproduction steps

1.Try to open the SnipeIT Homepage after upgrading
2.Getting a 500 Server Error
3.
...
[snipe-logfile.txt](https://github.com/snipe/snipe-it/files/8215086/snipe-logfile.txt)

### Expected behavior

Should start and get me to the login page. SSO is activated.

### Snipe-IT Version

5.4.1

### Operating System

Debian 10.11

### Web Server

Apache

### PHP Version

7.3.31

### Operating System

MacOS

### Browser

Brave

### Version

V1.36.111

### Error messages

```shell
root@pxs-ct-am:/var/www/snipe-it# sudo -u www-data composer check-platform-reqs
Cannot create cache directory /var/www/.cache/composer/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /var/www/.cache/composer/files/, or directory is not writable. Proceeding without cache
Checking platform requirements for packages in the vendor dir
ext-bcmath     7.3.31      success
ext-ctype      7.3.31      success
ext-curl       7.3.31      success
ext-date       7.3.31      success
ext-dom        20031129    success
ext-fileinfo   7.3.31      success
ext-filter     7.3.31      success
ext-gd         7.3.31      success
ext-iconv      7.3.31      success
ext-json       1.7.0       success
ext-ldap       7.3.31      success
ext-libxml     7.3.31      success
ext-mbstring   7.3.31      success
ext-openssl    7.3.31      success
ext-pcre       7.3.31      success
ext-pdo        7.3.31      success
ext-simplexml  7.3.31      success
ext-tokenizer  7.3.31      success
ext-xmlwriter  7.3.31      success
ext-zip        1.15.4      success
lib-pcre       10.32       success
php            7.3.31      success
root@pxs-ct-am:/var/www/snipe-it# sudo -u www-data php -m
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
intl
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

**Comment by snipe** [comment]
We need app logs in order to help.

**Comment by snipe** [comment]
(And the output of your upgrade.php process.)

**Comment by ZhisongZhang** [comment]
same here, got 500 soon after git pull
below is my logs when accessing the application:

[2022-03-10 14:30:00] production.ERROR: ReflectionException: Class Fruitcake\Cors\HandleCors does not exist in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php:803
Stack trace:
#0 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(803): ReflectionClass->__construct('Fruitcake\\Cors\\...')
#1 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\Container\Container->build('Fruitcake\\Cors\\...')
#2 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(785): Illuminate\Container\Container->resolve('Fruitcake\\Cors\\...', Array, true)
#3 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Foundation\Application->resolve('Fruitcake\\Cors\\...', Array)
#4 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(770): Illuminate\Container\Container->make('Fruitcake\\Cors\\...', Array)
#5 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(209): Illuminate\Foundation\Application->make('Fruitcake\\Cors\\...')
#6 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(183): Illuminate\Foundation\Http\Kernel->terminateMiddleware(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#7 /var/www/snipeit/public/index.php(63): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#8 {main}

Next Illuminate\Contracts\Container\BindingResolutionException: Target class [Fruitcake\Cors\HandleCors] does not exist. in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php:805
Stack trace:
#0 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\Container\Container->build('Fruitcake\\Cors\\...')
#1 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(785): Illuminate\Container\Container->resolve('Fruitcake\\Cors\\...', Array, true)
#2 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Foundation\Application->resolve('Fruitcake\\Cors\\...', Array)
#3 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(770): Illuminate\Container\Container->make('Fruitcake\\Cors\\...', Array)
#4 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(209): Illuminate\Foundation\Application->make('Fruitcake\\Cors\\...')
#5 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(183): Illuminate\Foundation\Http\Kernel->terminateMiddleware(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#6 /var/www/snipeit/public/index.php(63): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#7 {main}  
[2022-03-10 14:30:00] production.ERROR: Target class [Fruitcake\Cors\HandleCors] does not exist. {"userId":1,"exception":"[object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Target class [Fruitcake\\Cors\\HandleCors] does not exist. at /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php:805)
[stacktrace]
#0 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\\Container\\Container->build('Fruitcake\\\\Cors\\\\...')
#1 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(785): Illuminate\\Container\\Container->resolve('Fruitcake\\\\Cors\\\\...', Array, true)
#2 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\\Foundation\\Application->resolve('Fruitcake\\\\Cors\\\\...', Array)
#3 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(770): Illuminate\\Container\\Container->make('Fruitcake\\\\Cors\\\\...', Array)
#4 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(209): Illuminate\\Foundation\\Application->make('Fruitcake\\\\Cors\\\\...')
#5 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(183): Illuminate\\Foundation\\Http\\Kernel->terminateMiddleware(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\Response))
#6 /var/www/snipeit/public/index.php(63): Illuminate\\Foundation\\Http\\Kernel->terminate(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\Response))
#7 {main}

[previous exception] [object] (ReflectionException(code: -1): Class Fruitcake\\Cors\\HandleCors does not exist at /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php:803)
[stacktrace]
#0 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(803): ReflectionClass->__construct('Fruitcake\\\\Cors\\\\...')
#1 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\\Container\\Container->build('Fruitcake\\\\Cors\\\\...')
#2 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(785): Illuminate\\Container\\Container->resolve('Fruitcake\\\\Cors\\\\...', Array, true)
#3 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\\Foundation\\Application->resolve('Fruitcake\\\\Cors\\\\...', Array)
#4 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(770): Illuminate\\Container\\Container->make('Fruitcake\\\\Cors\\\\...', Array)
#5 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(209): Illuminate\\Foundation\\Application->make('Fruitcake\\\\Cors\\\\...')
#6 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(183): Illuminate\\Foundation\\Http\\Kernel->terminateMiddleware(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\Response))
#7 /var/www/snipeit/public/index.php(63): Illuminate\\Foundation\\Http\\Kernel->terminate(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\Response))
#8 {main}
"}

**Comment by ZhisongZhang** [comment]
below is the upgrade process output:

--------------------------------------------------------
WELCOME TO THE SNIPE-IT UPGRADER! 
--------------------------------------------------------

This script will attempt to: 

- check your PHP version and extension requirements 
- do a git pull to bring you to the latest version 
- run composer install to get your vendors up to date 
- run migrations to get your schema up to date 
- clear out old cache settings

--------------------------------------------------------
STEP 1: Checking PHP requirements: 
--------------------------------------------------------

Current PHP version: (7.2.24-0ubuntu0.18.04.11) is at least 7.2.5 - continuing... 
FYI: The php.ini used by this PHP is: /etc/php/7.2/cli/php.ini

Checking Required PHP extensions... 

√ bcmath is installed!
√ curl is installed!
√ fileinfo is installed!
√ gd is installed!
√ json is installed!
√ ldap is installed!
√ mbstring is installed!
√ mysqli is installed!
√ openssl is installed!
√ PDO is installed!
√ tokenizer is installed!
√ xml is installed!
√ zip is installed!

--------------------------------------------------------
STEP 2: Backing up database: 
--------------------------------------------------------

-- Starting backup...
Backup failed because: mkdir(): Permission denied.


--------------------------------------------------------
STEP 3: Putting application into maintenance mode: 
--------------------------------------------------------

-- Failed to enter maintenance mode.
file_put_contents(/var/www/snipeit/storage/framework/down): failed to open stream: Permission denied

--------------------------------------------------------
STEP 4: Pulling latest from Git (master branch): 
--------------------------------------------------------

Git is installed. 
error: cannot open .git/FETCH_HEAD: Permission denied
fatal: Unable to create '/var/www/snipeit/.git/index.lock': Permission denied
fatal: Unable to create '/var/www/snipeit/.git/index.lock': Permission denied
Cannot save the current index state
error: cannot open .git/FETCH_HEAD: Permission denied
-- -- -- 
--------------------------------------------------------
Step 5: Cleaning up old cached files:
--------------------------------------------------------

√ No bootstrap/cache/compiled.php, so nothing to delete.
√ No bootsrap/cache/services.php, so nothing to delete.
√ No bootstrap/cache/config.php, so nothing to delete.

-- Configuration cache cleared!
-- Application cache cleared!
-- Route cache cleared!
-- Compiled views cleared!

--------------------------------------------------------
Step 6: Updating composer dependencies:
(This may take a moment.)
--------------------------------------------------------

-- We couldn't find a local composer.phar. No worries, trying globally.

Generating optimized autoload files
                                                                                                                         
  [ErrorException]                                                                                                       
  file_put_contents(/var/www/snipeit/vendor/composer/autoload_namespaces.php): failed to open stream: Permission denied  
                                                                                                                         

dump-autoload [--no-scripts] [-o|--optimize] [-a|--classmap-authoritative] [--apcu] [--no-dev]

Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 10 installs, 102 updates, 2 removals
  - Removing dnoegel/php-xdg-base-dir (v0.1.1)

                                                                                  
  [RuntimeException]                                                              
  Could not delete /var/www/snipeit/vendor/dnoegel/php-xdg-base-dir/.travis.yml:  
                                                                                  

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...


--------------------------------------------------------
Step 7: Migrating database:
--------------------------------------------------------

Nothing to migrate.

--------------------------------------------------------
Step 8: Checking for OAuth keys:
--------------------------------------------------------

√ OAuth keys detected. Skipping passport install.

--------------------------------------------------------
Step 9: Taking application out of maintenance mode:
--------------------------------------------------------

-- Application is already up.

---------------------- FINISHED! -----------------------
All done! Clear your browser cookies and re-login to use 
your upgraded Snipe-IT!
--------------------------------------------------------

**Comment by ZhisongZhang** [comment]
I have to change the folder/files permission by
# sudo chown -R snipeitapp:www-data /var/www/snipeit 
then run the upgrade command as below
# sudo -u snipeitapp php upgrade.php
then change file mode
# sudo chmod -R 777 /var/www/snipeit
problem fixed for me (/var/www/snipeit is my snipe-it app location on the server, you might need to change it as per you scenario)

**Comment by snipe** [comment]
Yeah, the output of the upgrade script was showing a lot of "permission denied" errors. Any time you see that, you should always check that `storage` and all of its subfolders are writable.

Closing this for now, but if the OP is still having trouble and can provide logs, we can re-open it.

**Comment by GCHPX** [comment]
Hi,
sorry it took me a couple of days to get back to you. I did restore a backup and got the "old" version working. 
I would do the upgrade again in order to get this fixed. Which exact Logs do you need? I would also post the output of upgrade.php as soon I do the upgrade.

**Comment by snipe** [comment]
Server logs, app logs, php logs - literally any logs. Otherwise there’s no way to know what’s broken. I’d start with app logs tho.
