### ISSUE TITLE
Empty drop down lists when creating asset (6.0.0 RC4 build 6754)

### ISSUE THREAD

**Issue by rytispublic** [grokability/snipe-it#10825]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

SnipeIT demo environment:
https://develop.snipeitapp.com/hardware/create

Model -> New
Empty drop down lists in „Manufacturer“ and „Category“ selection

### Reproduction steps

1. Select "New Asset"
2. Select Model -> New
3.
...

### Expected behavior

Drop down lists in „Manufacturer“ and „Category“ selection should list and allow to select existing data.

### Screenshots

![SnipeIT 2022-03-16 110518](https://user-images.githubusercontent.com/97362122/158558317-941e4c19-9a4e-4f42-816b-c38aaa3a46c5.png)

### Snipe-IT Version

6.0.0 RC4 build 6754

### Operating System

-

### Web Server

-

### PHP Version

-

**Comment by snipe** [comment]
Excellent catch, @rytispublic! We’ll get that fixed ASAP.

**Comment by snipe** [comment]
Huh. I can reproduce this on the demo, but not locally, both of which are using the same version. 

Digging deeper here.

**Comment by snipe** [comment]
Ahh... JS error:

> [Error] ReferenceError: Can't find variable: baseUrl
	(anonymous function) (all.js:61406)
	each (all.js:385)
	(anonymous function) (all.js:61399)
	(anonymous function) (all.js:10412)
	each (all.js:385)
	(anonymous function) (all.js:10411)
	fire (all.js:3500)
	fireWith (all.js:3630)
	done (all.js:9796)
	(anonymous function) (all.js:10057)

**Comment by snipe** [comment]
This should be fixed on `develop`, though I don't love how it was fixed, and it should be revisited.

**Comment by snipe** [comment]
(This is fixed on `develop` but not deployed to the dev demo yet because GH is having some issues with webhooks, which we use to auto-deploy. I will keep trying.) 

https://www.githubstatus.com

<img width="1004" alt="Screen Shot 2022-03-16 at 8 32 35 AM" src="https://user-images.githubusercontent.com/197404/158628202-dc96f85c-c886-4c9e-a4c0-2a73da894c6c.png">


<blockquote><img src="//dka575ofm4ao0.cloudfront.net/pages-favicon_logos/original/36420/akacZEQQfOBdc7ftyxJt" width="48" align="right"><div><strong><a href="https://www.githubstatus.com/">GitHub Status</a></strong></div><div>Welcome to GitHub's home for real-time and historical data on system performance.</div></blockquote>
