### ISSUE TITLE
Translation in resources/views/users/print.blade.php

### ISSUE THREAD

**Issue by guiluxdj** [grokability/snipe-it#10890]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hi,
There is no translation for 'Assigned to'

### Reproduction steps

1.resources/views/users/print.blade.php

### Expected behavior

resources/views/users/print.blade.php

### Screenshots

![image](https://user-images.githubusercontent.com/26114260/161254207-651c29f6-5823-4b6c-b3b6-3a057e550c09.png)

### Snipe-IT Version

6.0.0-RC-5 - build 6772

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

Php 8

**Comment by opus-nbonenberger** [comment]
@snipe in addition to this, there is no translation for the columns in 'Assets' and 'Accessoires'. The language is set to 'German' but I see these columns in English. Accessoires itself is translated. Looked into the Crowdin project but could not find the file or spot.

![Bildschirmfoto 2022-05-06 um 10 06 52](https://user-images.githubusercontent.com/44579933/167092661-0866168d-d476-4797-b5df-9f38be586825.png)
![Bildschirmfoto 2022-05-06 um 10 06 48](https://user-images.githubusercontent.com/44579933/167092663-e761ce45-8389-4fd4-b5ce-bea64d461536.png)
.

**Comment by opus-nbonenberger** [comment]
Problem is here:
https://github.com/snipe/snipe-it/blob/1ac626a43a41dc2ee90a474ad6d64adc57aacfa1/resources/views/users/print.blade.php#L66-L72

https://github.com/snipe/snipe-it/blob/1ac626a43a41dc2ee90a474ad6d64adc57aacfa1/resources/views/users/print.blade.php#L133-L136

https://github.com/snipe/snipe-it/blob/1ac626a43a41dc2ee90a474ad6d64adc57aacfa1/resources/views/users/print.blade.php#L175-L178

https://github.com/snipe/snipe-it/blob/1ac626a43a41dc2ee90a474ad6d64adc57aacfa1/resources/views/users/print.blade.php#L211-L214

No translation for these th's.

**Comment by opus-nbonenberger** [comment]
@snipe Thank you, but still missing from translation is: 

https://github.com/snipe/snipe-it/blob/6304709c77ba62cc77f205107b24474659479724/resources/views/users/print.blade.php#L5

'Assigned to'

and

https://github.com/snipe/snipe-it/blob/6304709c77ba62cc77f205107b24474659479724/resources/views/users/print.blade.php#L72

'Checked out'

---

Also, I can't locate this translation in Crowdin. They are also displayed in English instead of german.

https://github.com/snipe/snipe-it/blob/6304709c77ba62cc77f205107b24474659479724/resources/views/users/print.blade.php#L250

Can you add this to translation? Thank you.

**Comment by snipe** [comment]
It should be on CrowdIn now
