### ISSUE TITLE
LDAP Sync msds-parentdistname for obtain user OU info

### ISSUE THREAD

**Issue by Ptraaaa** [grokability/snipe-it#11208]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Im planning to sync all AD user into Snipe IT 
Test LDAP Sync is ok just willing sync department field as well
we use ou directory to identify user's department therefore I tried use **msds-parentdistname** in department field
refer to guideline already entered in all lowercase. but seems it still unable to resolve data
not sure dash is not allow in LDAP sync or another other issue

### Reproduction steps

use **msds-parentdistname** in department field

### Expected behavior

Department field in snipeit to show with OU directory path e.g. parent distinguished name or RDN
 

### Snipe-IT Version

6.0.1

### Operating System

Windows

### Web Server

IIS

### PHP Version

8

**Comment by uberbrady** [comment]
I've never seen that attribute before, but it definitely seems like it's related to the OU-level, and not to the individual user-level.

We can accept 'department' or 'departmentnumber' but it seems like your directory isn't set up that way, so I don't think it's going to do what you want. Since you have 'departments' mapped to OU's, you possibly could do per-OU syncing, but that would sync your per-OU settings to individual locations, which is probably not what you want.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
