### ISSUE TITLE
Erro consulta exibição de tabelas

### ISSUE THREAD

**Issue by deservcombr** [grokability/snipe-it#11236]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Fiz a instalação do ambiente snipe-it no meu servidor, porém quando faço qualquer cadastro, por exemplo Empresa, ou Usuário, ele não aparece na listagem, quando tento cadastrar achando que deu algum erro, ele informa que já esta cadastrado.
Quando olho direto no banco, realmente foi criada a entrada, porém nos campos de ativo que pede para selecionar a empresa, por exemplo, fica processando e não tras a listagem de empresa para seleção.

### Reproduction steps

1. Acessar Menu Empresa
2. Criar nova empresa
3. Efetua o cadastro
4. Listar empresas
5. Não lista nada
...

### Expected behavior

Gostaria de saber se este problema já é conhecido, se sim qual a correção para o pleno funcionamento?

### Snipe-IT Version

6.0.2

### Operating System

Linux Centos 7.9

### Web Server

Apache 2.4

### PHP Version

7.4.29

**Comment by snipe** [comment]
Bom dia! Please post in English - while I *am* learning Portuguese, it's not good enough yet to give tech support in, and google translation isn't helping much here:

> I did the installation of the snipe-it environment on my server, so when I do any registration, for example Company, or User, it does not appear in the list, when I try to register because of some error, it informs me that it is already registered.
When she was directly in the bank, she was really created at the entrance, because of the asset fields that she asks to select a company, for example, she is processing and not after a company listing for selection.

You'll need to provide answers to the error log questions. 
https://snipe-it.readme.io/docs/getting-help

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/getting-help">Getting Help</a></strong></div><div>If you're having trouble setting up Snipe-IT, don't worry!</div></blockquote>

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
