### ISSUE TITLE
Sorting Asset List by Custom Field (Date) doesn't work.

### ISSUE THREAD

**Issue by Remnence** [grokability/snipe-it#11341]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Sorting Asset List by Custom Field (Date) doesn't work.

Date display issue was resolved in [Fixes #8143 Date localization not work in custom fields](https://github.com/snipe/snipe-it/pull/10804) but now when you try and sort the asset list by that column it doesn't work properly.

### Reproduction steps

1. Select Asset List.
2. Ensure custom date field is displayed.
3. Click the column to sort.

### Expected behavior

Assets sorted by dates in the column, newest to oldest or vice versa.

### Screenshots

![image](https://user-images.githubusercontent.com/1884580/174403859-332e3548-94ed-42cd-9d33-7e8ab4946eae.png)

### Snipe-IT Version

6.0.4

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8.1.2

### Operating System

Windows

### Browser

Chrome

### Version

102

**Comment by snipe** [comment]
Yeah, this is kind of a known issue. The reason for that is that when we create custom fields, we always use TEXT fields in the actual database column. We do this because people sometimes change the *type* of field something is, and if data is already entered into that field, the database no likey. 

For example, let's say you have a custom field called "Apple Care End Date". If you created that as a text field to start with, you could end up with weird user-added data, like "Monday". If we try to switch that data type to an actual Datetime field, the DB will blow up because the data isn't all actual well-formed dates. 

It's something we're trying to find a good workaround for, without pinning us specifically to MySQL (we try not to use raw queries within the system to leave it open for folks to use Sqlite, Postgres, etc), but we don't have an immediate solve for it.

**Comment by Remnence** [comment]
Honestly the ideal solution for a lot of people would be something like a Support Contract module similar to your Software License one. Allow us to create and track and assign vendor support packages for assets and software licenses. Enterprise grade servers, routers and software all usually require yearly purchases for support/warranty replacement after the initial purchase year.

**Comment by jwnukoski** [comment]
Is this still an issue?  
Creating a new custom field date resulted in this for me:  
![Screenshot from 2024-03-30 17-20-50](https://github.com/snipe/snipe-it/assets/59515951/3d66102e-900e-4eb9-b415-c8dffb06f6c4)
(v6.3.4 build 13139 develop branch)

**Comment by Remnence** [comment]
I'm on 6.3.1 at the moment and it's still an issue. It does look like they
created an actual field with the same name/function as my custom date field
so I don't need it anymore.
