### ISSUE TITLE
Downloading documents from history failed

### ISSUE THREAD

**Issue by gyurina** [grokability/snipe-it#11399]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

On history page uploaded file links are incorrect

### Reproduction steps

1. upload an attachment to an item
2. click on history
3. try to download
...

### Expected behavior

to download the uploaded file

### Screenshots

Incorrect link on history tab:
![image](https://user-images.githubusercontent.com/79877778/175944223-d7e7f0fc-2ced-4c76-99cb-0eee799ed493.png)
 Correct link on Uploads tab:
![image](https://user-images.githubusercontent.com/79877778/175944398-174d7010-0288-4c66-93df-bfc45a4de685.png)

### Snipe-IT Version

v6.0.5 - build 8126 (master)

### Operating System

Ubuntu Linux 20.04.3

### Web Server

Apache

### PHP Version

7.4.3

**Comment by mikeroq** [comment]
Appears to be a typo in the ActionlogsTransformer. 
https://github.com/snipe/snipe-it/blob/cb225cb1ce68aed38990f67d22019d03365774b5/app/Http/Transformers/ActionlogsTransformer.php#L64

Has `$actionlog->id` instead of `$actionlog->item->id` for assetId key.

**Comment by snipe** [comment]
I'm unable to reproduce this locally or on the demo.

https://demo.snipeitapp.com/hardware/1#files

<img width="1595" alt="Screen Shot 2022-06-27 at 9 47 10 AM" src="https://user-images.githubusercontent.com/197404/175993460-1c21919f-5fff-4f20-9641-565b849527f9.png">

Clicking on that download results in the correct file being downloaded. 

<blockquote><img src="https://demo.snipeitapp.com/favicon.ico" width="48" align="right"><div><strong><a href="https://demo.snipeitapp.com/hardware/1#files">Snipe-IT Asset Management Demo</a></strong></div></blockquote>

**Comment by snipe** [comment]
(Same for the history tab) https://demo.snipeitapp.com/hardware/1#history

<blockquote><img src="https://demo.snipeitapp.com/favicon.ico" width="48" align="right"><div><strong><a href="https://demo.snipeitapp.com/hardware/1#history">Snipe-IT Asset Management Demo</a></strong></div></blockquote>

**Comment by mikeroq** [comment]
> (Same for the history tab) https://demo.snipeitapp.com/hardware/1#history
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/3f2d9feccae7cd6385c9fc30a080435adee7ce46d66d566c7341352cc371e9e1/68747470733a2f2f64656d6f2e736e69706569746170702e636f6d2f66617669636f6e2e69636f">**[Snipe-IT Asset Management Demo](https://demo.snipeitapp.com/hardware/1#history)**

I uploaded a PDF file to hardware id 1, file id is 583. Looks like this is working in the demo due to there being a hardware id 583. There doesn't appear to be a check in the AssetFilesController show method if the file actually belongs to that ID or not. 

I went ahead and deleted asset ID 583 in the demo and now the download fails:
https://demo.snipeitapp.com/hardware/583/showfile/583

Working and "correct" link:
https://demo.snipeitapp.com/hardware/1/showfile/583

You can verify by changing the hardware ID to one that exists and the file will still download, even though it doesn't belong to that asset.
https://demo.snipeitapp.com/hardware/10/showfile/583

<blockquote><img src="https://demo.snipeitapp.com/favicon.ico" width="48" align="right"><div><strong><a href="https://demo.snipeitapp.com/hardware/1#history">Snipe-IT Asset Management Demo</a></strong></div></blockquote>
<blockquote><img src="https://demo.snipeitapp.com/favicon.ico" width="48" align="right"><div><strong><a href="https://demo.snipeitapp.com/hardware/583/showfile/583">Snipe-IT Asset Management Demo</a></strong></div></blockquote>
<blockquote><img src="https://demo.snipeitapp.com/favicon.ico" width="48" align="right"><div><strong><a href="https://demo.snipeitapp.com/hardware/1/showfile/583">Snipe-IT Asset Management Demo</a></strong></div></blockquote>
<blockquote><img src="https://demo.snipeitapp.com/favicon.ico" width="48" align="right"><div><strong><a href="https://demo.snipeitapp.com/hardware/10/showfile/583">Snipe-IT Asset Management Demo</a></strong></div></blockquote>

**Comment by snipe** [comment]
This should be fixed on master now.
