### ISSUE TITLE
Custom Field names with / can break asset updates

### ISSUE THREAD

**Issue by adamcbeck** [grokability/snipe-it#11401]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Trying to update an asset that we have, we started getting this error: 
`SQLSTATE[42S22]: Column not found: 1054 Unknown column '_snipeit_ps_2_keyboard_mouse_25' in 'field list' (SQL: update assets set requestable = 0, _snipeit_ram_31 = 64, snipeit_ps_2_keyboard_mouse_25 = ?, assets.updated_at = 2022-06-27 09:30:02 where id = 672)`

Did the normal troubleshooting, ran through the common issues, ran the debugging, ran the migration tool, it all came back clean. Upgraded to the newest version. Ran migration again. Still clean. 

Noted that this was actually a custom field created previously. The name of the field is "PS/2 Keyboard/Mouse".

Logged into the DB and noted the name of the column is as such:
_snipeit_ps2_keyboardmouse_25

so no _ between the ps_2 and no _ between the keyboard_mouse

It appears that by having "/" in the name of the custom field, this causes the update query to generate underscores where the table does not have any.

I havent tested (yet, but I will) if this issue exists in a new custom field created on the newest version with slashes, if the table created corresponds correctly with the new query or not

### Reproduction steps
1.Update from a older version of Snipe-IT
2. Go to an already existing computer asset with a custom field that includes slashes in the name
3. Try to edit it (in my case mouse/keyboard field)

### Expected behavior

When updating the server, should be able to detect/update these table values to respect new query generation

### Snipe-IT Version

v6.0.5 - build 8126 (master)

### Operating System

CentOS Linux release 7.9.2009 (Core)

### Web Server

nginx

### PHP Version

8.1.7

### Error messages

```shell
Illuminate\Database\QueryException
SQLSTATE[42S22]: Column not found: 1054 Unknown column '_snipeit_ps_2_keyboard_mouse_25' in 'field list' (SQL: update `assets` set `requestable` = 0, `_snipeit_ram_31` = 64, `_snipeit_ps_2_keyboard_mouse_25` = ?, `assets`.`updated_at` = 2022-06-27 09:30:02 where `id` = 672) 

 * @throws \Illuminate\Database\QueryException

     */

    protected function runQueryCallback($query, $bindings, Closure $callback)

    {

        // To execute the statement, we'll simply call the callback, which will actually

        // run the SQL against the PDO connection. Then we can calculate the time it

        // took to execute and log the query SQL, bindings and time in our memory.

        try {

            return $callback($query, $bindings);

        }

 

        // If an exception occurs when attempting to run a query, we'll format the error

        // message to include the bindings with SQL, which will make this exception a

        // lot more helpful to the developer instead of just the database's errors.

        catch (Exception $e) {

            throw new QueryException(

                $query, $this->prepareBindings($bindings), $e

            );

        }

    }

 

    /**

     * Log a query in the connection's query log.

     *

     * @param  string  $query

     * @param  array  $bindings

     * @param  float|null  $time

     * @return void

     */

    public function logQuery($query, $bindings, $time = null)

    {
```

**Comment by adamcbeck** [comment]
Updated the ticket above with a bit more info as I discovered this was being caused by a change in the way that custom fields with "/" in the name were being handled. Snipe had been updated by a colleague a week or so ago ( I don't remember the previous version we were on), however the previous version handled these custom name fields differently and the update hasnt handled

I also just created a new custom field named "Test/Test2" and can see in the DB that it was created following the new query generation and it works fine there. So this only appears to affect older installs that have custom fields, with "/" in the name that have been updated

**Comment by adamcbeck** [comment]
I was able to fix my issue by doing the below:

`ALTER TABLE assets CHANGE COLUMN _snipeit_ps2_keyboardmouse_25 _snipeit_ps_2_keyboard_mouse_25 text;`

Going to close this as im unsure if this is something that is worth fixing but at maybe itll help the odd person in the future who updates and finds this

**Comment by snipe** [comment]
So what I think it's happening is that the transliteration engine in PHP changed, perhaps between PHP versions, so the column name that was added BEFORE the update doesn't match what the database thinks it should be. (You can see this by going to the custom fields page and exposing the DB Column column - it should show you a warning.

![image](https://user-images.githubusercontent.com/197404/175996445-391e40ec-8ef3-441f-ba89-0b8094fab7e3.png)

(This is a bad example screenshot, since it was a slightly different issue - the field was actually missing - but otherwise it would show you what it expects the field name to be versus what it appears to be in the database.)

We will likely try to create an artisan command to fix them system wide. We're not 100% sure what version of PHP the transliteration changed, but we've definitely seen it before, and your solution is the correct one for now.

**Comment by snipe** [comment]
I have two PRs open that should hopefully make this less clunky.

[This one](https://github.com/snipe/snipe-it/pull/11405) makes it so that we only care about the converted unicode name when we're adding or editing a custom field. For everything else we just trust the `db_column` value in the `custom_fields` table.

[This one](https://github.com/snipe/snipe-it/pull/11404) updates the existing console script that tries to fix weird custom field names. In theory, you wouldn't need this one IF the first one works as expected, but I prefer belt and suspenders.
