### ISSUE TITLE
[Feature Request]: Automatically move users to a specific Location based on the OU they are under in Google?

### ISSUE THREAD

**Issue by kamsobe** [grokability/snipe-it#11434]
### Is your feature request related to a problem? Please describe.

Is there any documentation on the "LDAP Search OU" field found when editing a Location, and does it work with a Google LDAP server? Could this now or in the future be used to move users to a specific Location in SnipeIT?

### Describe the solution you'd like

I'm using the hosted version of SnipeIT, and the main LDAP server in question is from Google. I would really like to automatically send users to a specific Location in SnipeIT based on the OU that they are in on the Google side.

### Describe alternatives you've considered

Perhaps spinning up a separate server to automatically query all users from Google and SnipeIT, and move them accordingly via API.... But this would take extra resources and a lot of time to implement.

### Additional context

I'm admittedly new to working with LDAP.

**Comment by uberbrady** [comment]
If you have users that live under a specific OU, and you set that OU within a Snipe-IT location - then when you do a generic LDAP sync (without setting a specific location, just clicking the button) - or if you have an automation that does it for you, then - 

- Users that are found in your directory that *aren't* in one of those OU's will be set to the 'null' location - no location at all.
- Users that are found in your directory that *are* in one of those OU's will be assigned those specific locations.

If you would like some help setting that up, please reach out to support@snipeitapp.com we'll be happy to give you a hand.

I'm going to close this out since we already **do** have this feature, but please do reach out to support if you need more assistance with it.
