### ISSUE TITLE
Software Licenses Not Appear

### ISSUE THREAD

**Issue by theozul** [grokability/snipe-it#11495]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I try to create a new software license, but nothing appears in the menu or no error command shows.

### Reproduction steps

1. Click on Licenses tab
2. Click "Create New" button
3. Fill in the required text field
4. Click "Save" button

...

### Expected behavior

The newly created license should appear in the "Software Licenses" menu.

### Screenshots

![image](https://user-images.githubusercontent.com/109127297/178418452-8883dff8-9bf7-4b2a-b62d-b8892c695b7d.png)

### Snipe-IT Version

6.0.7 build 8351

### Operating System

Windows

### Web Server

Apache

### PHP Version

8.1.6

### Operating System

Windows 10

### Browser

Google Chrome

**Comment by snipe** [comment]
Hi - sorry you're having trouble. As mentioned in the Issue Template, we need a stack trace and browser console errors in order to help you. 

You can either provide the contents of your `storage/logs/laravel.log` (please do not attach files, just paste in the log lines that occur when you trigger the error, you can turn `APP_DEBUG=true` and then trigger the error and show us what's on the screen, or you can tail the log file. More information is available [in the documentation](https://snipe-it.readme.io/docs/getting-help).

https://snipe-it.readme.io/docs/getting-help
https://snipe-it.readme.io/docs/advanced-debugging

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/getting-help">Getting Help</a></strong></div><div>If you're having trouble setting up Snipe-IT, don't worry!</div></blockquote>
<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/advanced-debugging">Advanced Debugging</a></strong></div><div>Snipe-IT ships with the Laravel Debugbar, an amazing piece of software that lets you introspect much further into the framework and application to troubleshoot issues that may be a little harder to track down. To enable the debugbar, set the following in your .env file, and clear your config cache: ...</div></blockquote>

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)

**Comment by oparis94** [comment]
I have same issues when I open in Edge browser. But, when I open in Chrome it work.

**Comment by jamwotton** [comment]
I am also having this problem. Can someone help?
