### ISSUE TITLE
[Feature Request]: Categorize Custom Fields into the "Optional Information" or "Order Related Information" disclosure arrows

### ISSUE THREAD

**Issue by aaronpollock** [grokability/snipe-it#11506]
### Is your feature request related to a problem? Please describe.

When adding/updating assets, all custom fields added appear in the main form area of the asset. If you have a lot of custom fields, the form still remains cluttered even with the new relocation of some below. Plus, we have some custom fields that are specific to Order Related Information, such as an internal PO number and Invoice Number, that should exist in that area, not scattered above.

### Describe the solution you'd like

When defining a custom field, the ability to choose whether it should appear in the **Optional Information** or **Order Related Information** sections of the form.

### Describe alternatives you've considered

No alternatives, alternative will just be filling out the form as is is now.

**Comment by snipe** [comment]
That's not something we're considering at this time, since if someone created the custom fields in the first place, the information is generally desired for the asset, however the way we would likely want this implemented is to split out required custom fields and non-required custom fields, keeping the required ones outside of the Optional Info, and keeping the non-required ones inside.
