### ISSUE TITLE
LDAP Sync should update info for existing users 

### ISSUE THREAD

**Issue by Mike-NP** [grokability/snipe-it#11520]
### Is your feature request related to a problem? Please describe.

The user information stored in Snipe quickly gets out of date as changes are made to the user information in AD. We have scheduled syncs running regularly, but this is only giving us new users. We have a manual process in place to handle "deleted" users, but any updated information isn't being reflected into Snipe (eg department, phone etc), and doing this manually would be fairly intensive and prone to error.

We are using this information to allocate costs to different areas of the business, and once out of date is causing issues.

### Describe the solution you'd like

Would be good to have the LDAP sync update all imported fields.

**Comment by StarlessNights** [comment]
It really doesn't update existing users? Ohh my, I've just assumed that it does.

**Comment by snipe** [comment]
@StarlessNights it certainly should. We're looking into this on our end to see what might be going awry. We have tons of users who use the LDAP sync successfully, so we're not sure what makes this case different.

**Comment by snipe** [comment]
Or actually, maybe we're not anymore, since this ticket is from 2022. 

We offer lots (not all) of the fields to map in the LDAP settings, but you do have to map them correctly, since everybody's LDAP is set up a little differently:

<img width="830" alt="Screenshot 2024-04-08 at 9 00 01 AM" src="https://github.com/snipe/snipe-it/assets/197404/284d3da1-aa93-49dd-9ea2-79dfc4455e5f">
