### ISSUE TITLE
Empty Lists

### ISSUE THREAD

**Issue by AdhamNasr** [grokability/snipe-it#11629]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

All lists are empty (users, companies, etc)

Creating a new user or company with the same name results in an error saying “name already taken”

Even dropdown menus show nothing and give an error “The results could not be loaded.”

I also tried setting location, but I'm facing the same issue

### Reproduction steps

1. Installed snipe-it with install script
2. preflight setup was all green and ready for final setup
3. created company under companies page (multi-company support enabled), success, but nothing shows in the list
4. created new users, success, but again nothing shows in the list
5. trying to create a new asset, nothing shows in company dropdown
...

### Expected behavior

Data to be shown in lists, dropdown menus to have choices

### Screenshots

![ksnip_20220807-173956](https://user-images.githubusercontent.com/89584763/183299047-b749863c-086d-4977-9a0c-e9dcef8608ff.png)
![ksnip_20220807-174020](https://user-images.githubusercontent.com/89584763/183299052-46bc9c21-fc3d-42c5-b626-fd5d1fb0249f.png)
![ksnip_20220807-174043](https://user-images.githubusercontent.com/89584763/183299056-e1ff7807-8f93-48ed-8c7a-747c0c28fc3e.png)

### Snipe-IT Version

v6.0.8 - build 8409 (master)

### Operating System

Ubuntu 22.04

### Web Server

Apache

### PHP Version

8.1.2

### Operating System

Arch Linux

### Browser

Chromium, FireFox, Brave

### Version

Latest

### Additional context

Fresh installation using install.sh

**Comment by AdhamNasr** [comment]
Updated to the latest commit, still having the same problem.

I saw that people had the same issue before in the past, and I went through most if not all of them and tried the solutions posted on there, but I'm still having the same issue.

**Comment by snipe** [comment]
Hi - sorry you're having trouble. As mentioned in the Issue Template, we need a stack trace and browser console errors in order to help you. 

You can either provide the contents of your `storage/logs/laravel.log` (please do not attach files, just paste in the log lines that occur when you trigger the error, you can turn `APP_DEBUG=true` and then trigger the error and show us what's on the screen, or you can tail the log file. More information is available [in the documentation](https://snipe-it.readme.io/docs/getting-help).

https://snipe-it.readme.io/docs/getting-help
https://snipe-it.readme.io/docs/advanced-debugging

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/getting-help">Getting Help</a></strong></div><div>If you're having trouble setting up Snipe-IT, don't worry!</div></blockquote>
<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/advanced-debugging">Advanced Debugging</a></strong></div><div>Snipe-IT ships with the Laravel Debugbar, an amazing piece of software that lets you introspect much further into the framework and application to troubleshoot issues that may be a little harder to track down. To enable the debugbar, set the following in your .env file, and clear your config cache: ...</div></blockquote>
