### ISSUE TITLE
Have to Login Two Times to get in....v.6.0.10

### ISSUE THREAD

**Issue by brianhoganm** [grokability/snipe-it#11760]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Ever since I updated to v. 6.0.10 I always have to enter my username and password twice to get in. Other users have to do it twice as well.  It's so weird that it's doing this. Is anyone experiencing this issue? I have cleared my Browser's cache/history and I have issued the artisan commands Clear & Cache. This is so frustrating that this is happening. Everything else is working great! 

Note: Once I enter my username and password the second time I can get in. No errors of any kind. The system works beautifully. 

### Reproduction steps

1.Log In - Nope
2. Log in - Works
3. Log Out 
4. Log In - Nope
5. Login - Works

...

### Expected behavior

Log in on the first try with correct credentials.

### Snipe-IT Version

6.0.10

### Operating System

Windows Server 2019

### Web Server

IIS

### PHP Version

7.4

**Comment by snipe** [comment]
We’re only seeing this currently if you’re switching users, but it is a known issue. We’ve isolated the problem, just not the fix yet :(

It’s caused by us adding a new piece of middleware that’s needed to prevent session fixation attacks where someone is logged into two devices and they change their password - we have to log out other devices in that case. 

We’re trying to figure out the fix now - sorry for the aggravation.

**Comment by brianhoganm** [comment]
> 

Hi Snipe. Thanks for reaching out. Gld to hear it's just a small error. I can totally live with this problem for awhile. Thanks for all you do. It won't effect all of our users that much. It was primarily our Kiosk computer which I use to switch between a a few users. 

Thanks!
