### ISSUE TITLE
CSV import issue

### ISSUE THREAD

**Issue by GayathriSulaja** [grokability/snipe-it#11781]
![Screenshotsnipe-it](https://user-images.githubusercontent.com/96216040/188479519-b4cda952-d389-44b5-884a-85aa7f24f9ee.png)
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

We are unable to import csv file with headers like Asset Tag, Manufacturer and Model name. 

### Reproduction steps

1. Create a csv file with mandatory fields (Model name, Asset Tag and Manufacturer).
2. Go to import menu.
3. Import the csv file that is already created with above fields.
4. Select Import type 'Assets' from the dropdown.
5.Select the import fields  (Model name, Asset Tag and Manufacturer).
6.Click on Import.
7. Now observed the error as in the screenshot.
...

### Expected behavior

Expected a 'Success... Redirecting' msg and the imported assets need to be in List All Assets.

### Snipe-IT Version

Version v6.0.4

### Operating System

Windows

### Web Server

Apache

### PHP Version

7.4.29

### Error messages

```shell
Asset Model "Dell inspiron": The category id field is required.
Asset "": The model id field is required.
```

### Additional context

fresh install

**Comment by Anatharias** [comment]
There's definitely improvements that need to be made around the importing modules

Model Name is a field that exists in the following pages:
Assets : Asset Name (column)
View Asset, Info tab: Asset Name
Asset Update page: Asset Name (under Optional information)
Custom Asset Report (export CSV): Asset Name Checkbox
Generated .CSV: Asset Name Column

Import page; Type "Assets": No "Asset Name" field present in the selection
Only available choices are **Asset Notes** presented two times:

- One pointing to **select2-9hv8-result-y2e3-asset_notes**
- the other one pointing to **select2-9hv8-result-6im7-asset_notes**


Same for "Model No.". no "Model No." import field present in the selection
Only available choices are **Model Name** and **Model Notes** presented two times:
- One pointing to **select2-xh9a-result-687f-model_notes**
- the other one pointing to **select2-xh9a-result-xo4b-model_notes**

Which is which ??

As a matter of fact, few of the exported fields are matched against an available import field
Here's the list of the fields that are in the generated CSV and that are not matched automatically, because they don’t exist, or are called differently:

- ID
- Checked out
- Type
- Default location
- Serial (Called Serial Number)
- Asset Name
- Model
- Model No.
- Purchased
- Warranty
- Checkout date

![SnipeIT](https://user-images.githubusercontent.com/17396591/188663365-bdf72382-580a-4361-9b3d-9c4ace0e340d.png)

**Comment by snipe** [comment]
> As a matter of fact, few of the exported fields are matched against an available import field

We're aware of that, and it's not currently something we're interested in fixing. We format names differently sometimes because of a variety of reasons, and given the API, the custom report isn't really intended to be a source for imports (unless you change the header columns). We can be more verbose in some contexts (an exported file, for example) than we can on a web page, since screen real estate is limited.

**Comment by sebseb538** [comment]
Hi snipe, 

But what about the bug that prevent from importing? Are you interested in fixing that? We are a couple of tech struggling for a while now with the CSV import.

**Comment by snipe** [comment]
I think most of these importer issues have been addressed in the past year. I'm going to close this for now.

**Comment by tempu-rejo** [comment]
I have similar problem with new version v8.0.4 build 17196 (gc29bdbdac), after delete all inventories and purge deleted records. any ide how to fix it?

**Comment by snipe** [comment]
Hi there - this issue is closed. Please create a new issue and answer all of the questions in the [getting help docs](https://snipe-it.readme.io/docs/getting-help#step-5-post-an-issue-to-github-or-discord). (When you reply to old, closed threads, it sends an email notification to everyone who ever participated in it, which can be pretty annoying to have happen on a thread that's been resolved for a while.)
