### ISSUE TITLE
Unable upload jpg file

### ISSUE THREAD

**Issue by YukoHermawan** [grokability/snipe-it#12021]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hi All...
I am w new bie, and I have installe Snipe it yesterday.
Now I still test & I have an issue like :
1. Can not upload logo
2. Can not upload jpg files.
3. Cann not generate label

For information, I use Version v6.0.12 - build 8824
Maybe any step will need to do to solved that issues ?
Please let's me know.
Thank you.

### Reproduction steps

![SnipeITerr01](https://user-images.githubusercontent.com/99711900/197445859-4a8ee58e-2d5a-4d3c-9ee2-bead1f2eee11.jpg)

### Expected behavior

Need tu upload logo, jpg file & generate label

### Snipe-IT Version

Version v6.0.12 - build 8824

### Operating System

Ubuntu 20.04

### Web Server

Apache

### PHP Version

7.4.3

### Operating System

Windows 10

### Browser

Firefox

### Version

106.0.1 ( 64bit )

**Comment by snipe** [comment]
Hi - sorry you're having trouble. As mentioned in the Issue Template, we need a stack trace and browser console errors in order to help you. 

You can either provide the contents of your `storage/logs/laravel.log` (please do not attach files, just paste in the log lines that occur when you trigger the error, you can turn `APP_DEBUG=true` and then trigger the error and show us what's on the screen, or you can tail the log file. More information is available [in the documentation](https://snipe-it.readme.io/docs/getting-help).

https://snipe-it.readme.io/docs/getting-help
https://snipe-it.readme.io/docs/advanced-debugging

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/getting-help">Getting Help</a></strong></div><div>If you're having trouble setting up Snipe-IT, don't worry!</div></blockquote>
<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/advanced-debugging">Advanced Debugging</a></strong></div><div>Snipe-IT ships with the Laravel Debugbar, an amazing piece of software that lets you introspect much further into the framework and application to troubleshoot issues that may be a little harder to track down. To enable the debugbar, set the following in your .env file, and clear your config cache: ...</div></blockquote>

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
