### ISSUE TITLE
How to edit the header and footer in a PDF document?

### ISSUE THREAD

**Issue by kruzikruz** [grokability/snipe-it#12128]
### Is your feature request related to a problem? Please describe.

Hello, I would like to know where I can edit the text that appears in the footer and header when saving all assigned assets to a user.

<img width="468" alt="Zrzut ekranu 2022-11-16 o 10 27 22" src="https://user-images.githubusercontent.com/28232236/202154820-bf4718c5-1b60-40c2-85ad-38855b9ade68.png">

### Describe the solution you'd like

.

**Comment by ccj9874** [comment]
Are you trying to print the page itself? The page URL only shows up if you do it that way. There is a built-in save function when you're looking at a table of assets. You can download a formatted PDF there.

**Comment by kruzikruz** [comment]
Approx. I am downloading a pdf file that has header and footer. It's okay I have them. He just wanted to be able to add a few things to them. For example, this 'Dział IT' is not right-justified.

Below is a photo of the downloaded PDF file.

<img width="508" alt="Zrzut ekranu 2022-11-16 o 16 27 24" src="https://user-images.githubusercontent.com/28232236/202222849-7fe9a47e-0330-4883-86d1-12a7822d6e2b.png">

**Comment by snipe** [comment]
> For example, this 'Dział IT' is not right-justified.

That's a function of your browser, not something we do, in the same way that it includes the IP address in that header.

**Comment by reycasper** [comment]
Hi @snipe hope you could conder this featues in future update, we been looking for this specific features since as an asset management application this features is very usufull for a company that is stick on pulling out IT equipment from one location to another location and that requirest a approval with signature and present it during security inspection during asset pullout. 

What we are doing rignt now is we manually do it in exel we print it and have it sign to the team/personel in charge, and present that document during inspection at the gate. It would be a greate help if this features will be included and generate it directly in the snipe it application.

I already explore on editing the files where it generate the pdf files but as i check there is no specific templete it follow it just just generate the pdf based on what was in the screen. 

If you can advise any interm solution for this manual process, it will be much appreciated. 

Thanks
Rey

**Comment by snipe** [comment]
@reycasper again, the OP's issue is a function of their printer/browser, not part of Snipe-IT. This would be a separate issue.
