### ISSUE TITLE
Iam not able to go to the licenses page 

### ISSUE THREAD

**Issue by manish-q** [grokability/snipe-it#12143]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I am new at snipe it and its working so perfectly in all (Asset, consumable, accessories, Users Models Serial No) , but when iam clicking at License the html page is not showing and its showing this as attached please help . Iam using it on localhost via xampp server application installed:

![Screenshot 2022-11-18 111259](https://user-images.githubusercontent.com/71642976/202629419-aecf7257-be9e-461c-a076-af6c521ad101.jpg)

### Reproduction steps

1. 
2.
3.
...
issue mentioned above 

### Expected behavior

issue mentioned above 

### Screenshots

![Screenshot 2022-11-18 111259](https://user-images.githubusercontent.com/71642976/202629831-3c23c278-8059-4f1f-aa26-6ff54cd2a172.jpg)

### Snipe-IT Version

Version v6.0.12

### Operating System

Windows

### Web Server

Apache

### PHP Version

PHP 7.4.30 (c

### Operating System

WIndows

### Browser

Google chrome

### Version

n 107.0.5304.107

**Comment by snipe** [comment]
This is covered in the docs https://snipe-it.readme.io/docs/xampp#remove-built-in-aliases

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/xampp#remove-built-in-aliases">XAMPP</a></strong></div><div>Download the Snipe-IT project using one of the methods on the Download page. We strongly recommend installing via Git. Follow the directions in the configuration section of the normal setup. Download XAMPP from the official site. In order to install required library dependencies, you'll need to inst...</div></blockquote>

**Comment by manish-q** [comment]
Thank you so much .. It works  👍 )

**Comment by snipe** [comment]
Great, glad you’re sorted :)

**Comment by manish-q** [comment]
Yes thanks...  i would like to ask one more question, is there any way that i can send mail thru snipe it if the asset or license had been assinged to the particular user/person..  its giving server 500 error..  just an info: iam using this as a localhost , via xampp server.. any help would be helpful and appreciated .. Thanks,,,
