### ISSUE TITLE
Department missing from custom asset report

### ISSUE THREAD

**Issue by ryanjj509** [grokability/snipe-it#12222]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When generating a custom asset report, the department column is blank. Departments are visible within the data grid within the UI, but not in the CSV.

### Reproduction steps

1. Generate custom asset report and include "assigned to" and "department" in "checked out to fields"
2.
3.
...

### Expected behavior

CSV generates with users department visible. 

### Snipe-IT Version

v6.0.13 - build 8923

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

7.4.3

### Operating System

Windows 11

### Browser

Chrome

### Version

107.0.5304.106

**Comment by ryanjj509** [comment]
This is occurring on the demo as well

**Comment by GamingSanctum** [comment]
It appears that most of the user information, other than name, is not being pulled in the report even though it is seen in the UI. 
I noticed this because one of my scripts utilizes the "username" field, but it's coming up blank on the report.

As seen in UI:

![UI](https://user-images.githubusercontent.com/6711405/206316364-553aa81e-e2fc-4989-b45f-17799e10054b.PNG)

As seen on Report:
![Report](https://user-images.githubusercontent.com/6711405/206316398-f14444c8-13b6-4054-8535-087221f8856d.PNG)

**Comment by snipe** [comment]
This is already fixed in the latest release.

**Comment by Zack01235** [comment]
I am having this issue reoccur in the latest update
