### ISSUE TITLE
Assets slowness in display all assets

### ISSUE THREAD

**Issue by makpith** [grokability/snipe-it#12301]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

slow loading and make browse unresponsive 

### Reproduction steps

1.10.5.16-MariaDB MariaDB Serverphp
2. PHP 7.4.33 
3. snipe it V6.0.14 migrated from V4.6
...

### Expected behavior

slow loading and make browse unresponsive 

### Screenshots

![Asset](https://user-images.githubusercontent.com/12385442/210534331-856856c1-af03-4e22-bda3-e63a3efe9c02.PNG)

### Snipe-IT Version

V6.0.14

### Operating System

Centos 9

### Web Server

Apache

### PHP Version

PHP 7.4.33

### Operating System

Windows

### Browser

Google Chrom

### Version

lastverion

### Error messages

```shell
its  fresh install os and php and mysql and make migration to the DB and then restore the DB from the old version to the new
```

### Additional context

its  fresh install os and PHP and MySQL and make migration to the DB and then restore the DB from the old version to the new MySQL

**Comment by makpith** [comment]
![AAss](https://user-images.githubusercontent.com/12385442/210552308-34635b45-8e50-4b53-92ee-d283315148ef.PNG)
![AAA](https://user-images.githubusercontent.com/12385442/210552320-57182cd9-b910-4cb0-8d35-736b8da47016.PNG)

**Comment by makpith** [comment]
slow scroll Down and browse page when page limit to 500

**Comment by snipe** [comment]
> slow scroll Down and browse page when page limit to 500

I'm not sure what this means? It's slow when you have 500 per page? I'd suggest limiting to under 500, or experimenting with a faster computer (server *and* desktop/laptop you're using to browse.)

We have users with half a million or more assets, so it's not an app issue as far as I can tell. When you're selecting the number of results, the browser needs to grab those via the API (server) but then also has to paint them on your screen (client-side). It's difficult to tell where the slowness would be here. These are pretty complex queries, since the relationships are complex, but I'd imagine there is some optimization you can do on your end (turning on query caching in mysql, for example) that would help. We have a lot of indexes on the database, which are specifically designed to let us do complicated queries very quickly, but if you try turning on query caching, I'd be curious to see if that improves anything for you.

Also run `php artisan migrate` to make sure your schema is up to date. The restore tool is newer and in some unusual cases, it doesn't always work flawlessly and migrations can get skipped.

Also let me know if you're seeing anything in your app error logs when you try to load that page.

**Comment by makpith** [comment]
I have enabled SQL Cache but nothing has changed,
 if I limit 10 it works smoothly 

do I have to run migrate after restoration or before?
is any way to 
what is the best way to migrate old DB to New DB

**Comment by snipe** [comment]
The restore should try to run migrations for you, but depending on how you're set up, it might not be successful. Run migrations after restoring.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
