### ISSUE TITLE
[Feature Request]: Add multiple photos to asset

### ISSUE THREAD

**Issue by ncribb-r7** [grokability/snipe-it#12399]
### Is your feature request related to a problem? Please describe.

Sometimes one photo is not enough for an asset. Having multiple photos per asset will help to distinguish between similar assets. It will also allow a user to see more information about the asset quicker. 

### Describe the solution you'd like

The ability to add multiple photos to an asset would be a greatly appreciated improvement. 

### Additional context

Bringing this back up https://github.com/snipe/snipe-it/issues/7860

**Comment by snipe** [comment]
This is really more a matter of adding file(s) during creation, since the asset is only allowed one photo (but unlimited files that can also be photos). If the addition fails validation though, you'd still have to upload them all over again when the form is returned with errors, since we can't attach files to an asset that doesn't exist.

**Comment by ncribb-r7** [comment]
Makes sense. What about adding an additional photo once the asset is created? As another user pointed out in that same thread (#7860), it'd be beneficial to have a front and back photo of a device. I edited the title to more accurately reflect the feature request.

**Comment by snipe** [comment]
You can always add back, sides, etc as additional files. The initial image is just what should show in listings, but once you're on the asset page, you can view all of the additional files through the files tab.

**Comment by ncribb-r7** [comment]
oooh, wow.. my bad! Thank you for pointing that out! lol :)

I appreciate you!
