### ISSUE TITLE
[Feature Request]: Delete Button in Actions Dropdown on Assets

### ISSUE THREAD

**Issue by floschoepfer** [grokability/snipe-it#12567]
### Is your feature request related to a problem? Please describe.

Currently, if you want to delete an Asset, you have to search it in the Assets List (or if it's archived, in the archived list).
That is not so handy, especially, when you only know the asset tag and even though, you are on the Asset itself, you have to go back to the Asset List and find it there.

### Describe the solution you'd like

I would like to have a "delete" button in the Actions Dropdown on the Asset itself, so you can delete this Asset, if you are on its view.
![image](https://user-images.githubusercontent.com/112496896/221488289-a85a5d39-51c9-4c81-b797-4213ed4743bd.png)

**Comment by snipe** [comment]
This gets a little trickier, since the delete method is a POST, and all of those links in the dropdown menu are GET requests. Plus putting it there wouldn't allow for the interstitial that asks for confirmation. If we could add a button on the page (similar to how we do with users) would that work for you?

**Comment by floschoepfer** [comment]
Of course, I'm totally fine with this. But I would really like it, when there is still a confirmation message. Is that possible?

**Comment by akemidx** [comment]
being handled in https://github.com/snipe/snipe-it/pull/12940

not yet merged

**Comment by akemidx** [comment]
this was merged via #12940 on July 25th
