### ISSUE TITLE
[Feature Request]: Add column "Company" to Accessories tab in user view

### ISSUE THREAD

**Issue by floschoepfer** [grokability/snipe-it#12616]
### Is your feature request related to a problem? Please describe.

Currently, only the following columns are shown on the Accessories tab in the user view:
- Name
- Notes
- Purchase Cost
- Action
![image](https://user-images.githubusercontent.com/112496896/223045244-b6c49d4b-51f5-4009-a09d-b30cdb0ffd05.png)

The column `Company` is missing.

### Describe the solution you'd like

I would like to display the column `Company` on the Accessories tab in the user view, like you can on the Assets tab.

**Comment by Godmartinz** [comment]
Actually I believe you are looking at an individual accessory, `Company` is listed on the accessories view since you could have more than one of an item at a Company.
<img width="1781" alt="image" src="https://user-images.githubusercontent.com/47435081/223190980-2194a9e4-0ae2-4dd1-b5f3-fcafad53d1d7.png">
