### ISSUE TITLE
Your configuration files are not serializable

### ISSUE THREAD

**Issue by jayavman** [grokability/snipe-it#12671]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

php artisan config:cache
Configuration cache cleared!

   LogicException 

  Your configuration files are not serializable.

  at vendor/laravel/framework/src/Illuminate/Foundation/Console/ConfigCacheCommand.php:71
     67▕             require $configPath;
     68▕         } catch (Throwable $e) {
     69▕             $this->files->delete($configPath);
     70▕ 
  ➜  71▕             throw new LogicException('Your configuration files are not serializable.', 0, $e);
     72▕         }
     73▕ 
     74▕         $this->info('Configuration cached successfully!');
     75▕     }

  1   bootstrap/cache/config.php:928
      Error::("Call to undefined method Closure::__set_state()")

      +14 vendor frames 
  16  artisan:35
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

### Reproduction steps

1. Running php artisan config:cache After Upgrade

### Expected behavior

Not sure if this is normal.

### Screenshots

![Screenshot 2023-03-15 at 9 18 07 am](https://user-images.githubusercontent.com/114973646/225154918-293c27b5-9ea6-4631-a355-6ccd9a6d779b.png)

### Snipe-IT Version

 v6.0.14 build 9715 (g8b70a7f21)

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8.1.16

**Comment by rafiabergel** [comment]
This is also happening to me on php 8.1.17, I commented out the delete so I can debug the config.php file and the line is bootstrap/cache/config.php:928
      Error::("Call to undefined method Closure::__set_state()")
I tried to keep the file and replace the closure with a function, but that did not work, and anyway it is flushed each time. Please help I have tried on 2 new servers, did the whole configuration and tried every possible way to fix this but it causes me to see "admin/user/general.create_user_page_explanation" and the like show up in the browser in the preflight page in the browser instead of text, and I also cannot create a user - I fill out the form and it keeps reverting back. I checked and my cookie domain is set to null (other tickets said that was the issue) thank you for any help and guidance.

**Comment by snipe** [comment]
You really don't need to cache config files in general tbh.

**Comment by snipe** [comment]
This looks like it's an issue with our Rollbar config, which *does* want a function or a closure. (Most people wouldn't be using Rollbar, but we do for our production environment to trap exceptions.)

We'll see if we can turn this into a regular function so it won't throw that error, but as I said, you generally don't have to cache your config anyway - the performance increase is generally negligible and it often leads to confusion when you make an env change and nothing seems to happen (because the config was cached.)
