### ISSUE TITLE
All Users Locked Out

### ISSUE THREAD

**Issue by larrygyamfi** [grokability/snipe-it#12766]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Whenever someone tries to log in, we are given a "username or password is incorrect" error message. One of our admins set the ldap active flag to active our LDAP settings. I set the LDAP enabled flag back to 0 and the issue still persists.

![image](https://user-images.githubusercontent.com/53521137/228884681-05c7be52-dbd5-494e-9f0b-818cf3ee6010.png)

### Reproduction steps

1. Opened HeideSQL and logged in with root
2. Navigated to settings table
3. Changed ldap_enabled to 0
4. Posted change.

### Expected behavior

I would be able to log in with our admin superuser account and revert the changes made.

### Screenshots

![image](https://user-images.githubusercontent.com/53521137/228884794-af84f6df-6db2-427b-96b7-bf108c761d67.png)

![image](https://user-images.githubusercontent.com/53521137/228884867-fcc37065-0bc9-444d-a07c-12e20132c348.png)

### Snipe-IT Version

v6.0.13

### Operating System

Windows Server 2019

### Web Server

IIS

### PHP Version

8.0.27

### Additional context

Fresh Install
Windows Server 2019 with IIS
Manual Installion
Manually edited data in the database

We have been using snipeit without issue for about a month with succesful ldap syncs. The active flag being set it the only change that has occured within the last 24 hours.

**Comment by snipe** [comment]
I'm mot exactly sure where to steer you here. Unless someone did an update (which you haven't, since you're still on 6.0.13) nothing in the app would have changed - and even if you had updated, we haven't touched LDAP in quite a bit. We don't technically support HeidiSQL, so I can't really offer any advice there, but this feels to me like maybe something changed on your LDAP side. Anything of note in your app logs?

**Comment by snipe** [comment]
You might try the emergency "break glass" create an admin option: https://snipe-it.readme.io/docs/create-an-admin

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/create-an-admin">Create an Admin</a></strong></div><div>Since v3.0, we've added the rescue utility to add an admin user via the command line. This can be helpful if you've managed to lock yourself out of your installation (for example if you can't remember your password and never set the system up to send email.)Shell/path/to/php artisan snipeit:create-a...</div></blockquote>

**Comment by larrygyamfi** [comment]
Thank you for your response. It started working about 10 mins after i posted this. It may have needed time to synch the changes or something along those lines. Typing "active" in our active flag was the culprit.
