### ISSUE TITLE
[Feature Request]: LDAP physicaldeliveryofficename in GUI

### ISSUE THREAD

**Issue by 2queenz** [grokability/snipe-it#12817]
### Is your feature request related to a problem? Please describe.

Apologies if this has already been addressed elsewhere or if I've missed something obvious. I'm hoping to be able to set the location of users synced with LDAP by defining what LDAP attribute to assign as a location rather than creating an AD OU search for each defined location. My organization uses the "Office" (physicaldeliveryofficename) attribute in AD, rather than OUs to determine the site location of a user (all users are in one OU). Currently when syncing a new user with LDAP, the location comes up as null and has to be manually entered.

### Describe the solution you'd like

There are currently the following definable attributes in the GUI:

LDAP Employee Number
LDAP Department
LDAP Manager
LDAP Email
LDAP Telephone Number
LDAP Job Title
LDAP Country

If an additional one could be added, titled something like "LDAP Office Location", with perhaps a stipulation to not use the field if OU location search is being utilized, that would help me greatly. Thanks.

### Describe alternatives you've considered

Open to defining this in CLI but not sure how to based on Snipe KB.

**Comment by ry-oct** [comment]
+1 for this. 

Further to this, if someone selects a location during LDAP sync, it then assigns that selected location to any AD account that gets updated, including existing ones. So even if we set it manually, it will almost inevitably get messed up when someone accidentally selects a location during LDAP sync.

**Comment by Oddalmighty** [comment]
This would be huge for my agency. All 700+ employees are spread across approx 100 locations. We use the PhysicalDeliveryOfficeName attribute in AD as the employee's location (our OUs are separated by 'title' so we can't use the current LDAP feature). Because we work with school employees, locations change frequently. Having to change the location both in AD and in Snipe gets crazy for us during school startup in the fall, and our database quickly becomes inaccurate if we forget to change the location in Snipe or select the wrong location. Using LDAP to keep things in sync would make our lives so much easier. 

To make this even better, if the locations synced from LDAP were tied to locations within Snipe (automatically placing that employee within that location), that would be amazing. I believe I mentioned this in Discord in hopes it may be included in v7 if possible at all.

**Comment by emreiyioz** [comment]
Hi,

I needed the same feature about this topic and created a duplicated ticket which is closed anyway.
After this, I found a workaround to solve the issue. On Settings > Locations if you edit a location and put the correct LDAP Search OU like below worked for me :

OU="OUname",OU="LocationOU",OU="RootOU",DC="domain",DC=local

And then when I re-sync with LDAP all users' location has been set with correct one.

Still, it would be better to have this feature in LDAP settings 👍

**Comment by snipe** [comment]
If I'm understanding this correctly, the ask is to create a new LDAP mappable field for Location - in this case it would be `physicaldeliveryofficename` but could be whatever someone's LDAP setup is. This means we'd need to pull the value of `physicaldeliveryofficename` (or whatever), check the locations table to see if it exists or create it if it does not, and then save the user with that location's ID. Am I correct?

**Comment by Oddalmighty** [comment]
Correct. I think the initial request on this thread was for the physicaldeliveryofficename AD attribute to be an option within the LDAP fields. My request is the same but also to map the locations pulled via LDAP to locations within the Snipe database. That way it automatically ties users and assets to the correct locations when changed in AD.
