### ISSUE TITLE
Better french localization

### ISSUE THREAD

**Issue by ohmer1** [grokability/snipe-it#12948]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I would like to correct issues with the french localization. I created an account at crowdin (f4242) but I think I would need some access to be able to correct the various strings.

### Reproduction steps

1.
2.
3.
...

### Expected behavior

N/A

### Snipe-IT Version

6.1.0

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8.1

**Comment by qay21** [comment]
You don't need any specific access. Simply go to https://crowdin.com/project/snipe-it and select French.

I'm myself actively trying to enhance french translation. I started by adding all missing strings (you can see the blue part in the progress bar of each module). Much of my work is still waiting for approval at this day.

Next step will probably be to fix some of the most annoying mistranslations, such as "Caisse à" instead of "Attribuer à", a vey bot-like translation of "Check out". This will require quite some work, as there is several hundreds of strings. I'm glad I'm not the only active french translator here :smile: :wave: 

<blockquote><img src="https://crowdin-static.downloads.crowdin.com/images/project-logo/67597/small/3715dc5bf1a83beda1855c31a29fef96470.png" width="48" align="right"><div><img src="/favicon-16x16.png" height="14"> Crowdin</div><div><strong><a href="https://crowdin.com/project/snipe-it">Snipe-IT Asset Management — Translation Project on Crowdin</a></strong></div><div>Help us translate Snipe-IT Asset Management and bring it to the world!</div></blockquote>

**Comment by qay21** [comment]
This lead me to the very first issue I encountered while translating : the current french translation is gendered in the classic french doctrine : male gender prevails for plural and for neutral sentences. However, we do have some equivalent of gender neutral pronouns and grammar.

@snipe I can see that most of the english original strings are using gender-neutral forms, such as "they" instead of he/she. Would you like us to better reflect this inclusivity in our french translation ?

The biggest problem of french gender-neutral phrasing is its lengthiness : while "they" can be translated as "iel", some very simple gender-neutral forms have to be much much larger. For example, "user" would be translated by "utilisateur" in the classical form (male-gendered by default), and "utilisateur·trice" in the gender-neutral form (a modern shortening of "utilisateur ou utilisatrice").

**Comment by snipe** [comment]
@qay21 I would LOVE that. We do mention trying to use [gender-neutral langauge](https://snipe-it.readme.io/docs/translations#gender-inclusivity) (where it’s available) in our docs, but my French definitely isn’t good enough to proofread it well. I can add you as a proofreader if you’d like.

**Comment by qay21** [comment]
Does that mean I would be able to validate good translations in CrowdIn ? I'd be glad to help !

**Comment by snipe** [comment]
@qay21 Yep, that’s what it means :) We can’t speak all the languages, so we pick trusted folks that we know will give us the best versions, versus me just sort of shrugging and hoping whoever translated it got it right.

**Comment by qay21** [comment]
Then you can go ahead, I'm using this github account to login on crowdin, so you should find me easily. 😊 I'll have a look on how to validate translations in the first half of the week. Thanks !

**Comment by snipe** [comment]
@qay21 - Sorry for the delay - you should set up as a proofreader now - thank you!!
