### ISSUE TITLE
[Feature Request]: Remove short-circuit for manual LDAP sync, make it configurable

### ISSUE THREAD

**Issue by WilliButz** [grokability/snipe-it#12961]
### Is your feature request related to a problem? Please describe.

Introduced in https://github.com/snipe/snipe-it/pull/12444 + follow-up fix in https://github.com/snipe/snipe-it/pull/12445

I saw the comment in the first PR related to this but did not find an open issue that explicitly refers to this: https://github.com/snipe/snipe-it/pull/12444#issuecomment-1412985135

Just noticed this change while preparing to upgrade to 6.1.0.
Until now it was possible for users to be authenticated using SAML with LDAP disabled, while still having a systemd timer trigger a regular sync of the user attributes via LDAP using a limited service account.

We'd like to keep a setup like this without the need to pass user SSO credentials through the snipe-it app.

### Describe the solution you'd like

This was hacky to configure even before this change, i.e. one has to configure the "LDAP Integration" but leave it disabled :)

Would it be possible to make this functionality explicit? For example with an additional flag that lets admins configure LDAP parameters but disables authentication, e.g "Use LDAP for authentication" with default "Yes" ?

Mentions because of the above PRs:
@uberbrady
@snipe

**Comment by uberbrady** [comment]
Your use-case is definitely a totally valid one, and one of the more common ones that we see. Generally, the best-in-breed experience around Users and login is LDAP (or SCIM) for user-sync, and SAML for auth.

What I think you can do (and this may be 'enough' for you) is to turn on the LDAP checkbox, but then deliberately set a 'wrong' LDAP Auth Query. Then no user would ever be able to authenticate via LDAP.

The LDAP checkbox is _meant_ to mean: "Is the LDAP subsystem turned on at all?" - which is why we put in those fixes you mentioned.

Another option you might want to consider is setting `REQUIRE_SAML` to `true` in your `.env` - this will close the back-door of `/login?nosaml` so that SAML becomes the *ONLY* way you can log back in to the system. That means if you break your SAML setup, you're going to have to disable that to be able to get an admin user to be able to log back in.

I hope this helps, and makes sense. Thanks for using Snipe-IT, and thanks for a very solid bug report. Makes our jobs much easier :)

**Comment by WilliButz** [comment]
Thank you for the quick reply! The first workaround you proposed works and should be enough for our use case, given that with SAML enabled as the primary method of authentication, users are immediately redirected to our IdP before even getting a chance to put in their credentials into snipe-it. And the app-specific admin account is still accessible to us by using `/login?nosaml`, same as before 6.1.0.
I'd personally _prefer_ to see this setup properly supported without a workaround, maybe as described in my original message above, but I don't know if that is something you'd consider in the future. Feel free to close this issue if it's not :)
