### ISSUE TITLE
[Feature Request]: How can i assign a company to an asset via api ?

### ISSUE THREAD

**Issue by NiTRoeSE** [grokability/snipe-it#13087]
### Is your feature request related to a problem? Please describe.

We create assets through api with a self written agent for win clients.
While creating or updating assets its possible to assign or checkout an asset to a location.

Now we need the possability to assign a asset to a company through the api, but i cant find a way how to do this in api documentation.
Maybe its not possible?

### Describe the solution you'd like

A way to assign a asset to a company through api.

**Comment by jayavman** [comment]
time to read : https://snipe-it.readme.io/reference/api-overview

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/reference/api-overview">Overview</a></strong></div><div>The Snipe-IT JSON REST API allows you to perform most of the same actions through your own tools as you can through the web interface. If you need the Swagger/OpenAPI Specification, you can find it here. Since the API Explorer talks to the live development database - and resets periodically - you CA...</div></blockquote>

**Comment by snipe** [comment]
You cannot assign an asset to a company. An asset can *belong* to a company, but you can’t, for example, check out an asset to a company. If you want an asset to belong to a company, via the API, pass `company_id` in the create/update asset payload.
