### ISSUE TITLE
Unable to generate API Token.

### ISSUE THREAD

**Issue by cstief** [grokability/snipe-it#13168]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Using the hosted version of Snipe-IT I am unable to generate an API Token. I receive a generic error message stating: 
"Whoops! Something went wrong!
        * Server Error"

### Reproduction steps

1.Click on user on the top right
2. Select "Manage API Keys"
3. Click "Create New Token"
4. Enter name for the token and click "Create"

### Expected behavior

To receive a key to copy and paste.

### Screenshots

![image](https://github.com/snipe/snipe-it/assets/49765968/bd9702e3-621a-4056-b1ee-43b9d20bcfbc)

### Snipe-IT Version

v6.0.11 build 8758 (g61fa0bda4)

### Operating System

Hosted so I assume some flavor of Linux(?)

### Web Server

Hosted so I assume Apache(?)

### PHP Version

8.0.25

### Browser

Microsoft Edge

### Version

114.0.1823.43

### Device

Windows Laptop

### Operating System

Windows 11

**Comment by snipe** [comment]
Hi there - you can send an email to support@snipeitapp.com letting us know your hosted URL and we can fix that for you. :)

**Comment by michaeloconnor1717** [comment]
I am encountering the same issue. Is the solution still to email support or is there a different approach to resolve?

**Comment by snipe** [comment]
Emailing support is only for hosted customers. If you’re self-hosted, run the commands mentioned here: https://snipe-it.readme.io/reference/generating-api-tokens

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/reference/generating-api-tokens">Generating API Tokens</a></strong></div><div>In order to use the API, you'll need to generate an API key that will be associated with your user. You can do this through the Snipe-IT web interface, by going to your account dropdown in the top right and clicking on "Manage API Keys".If you run into an error when trying to create API tokens throu...</div></blockquote>
