### ISSUE TITLE
Login form redirecting to wrong URL

### ISSUE THREAD

**Issue by zmeggyesi** [grokability/snipe-it#13182]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When logging in, the login form redirects to a `localhost` URL with the external port, instead of the value of the `APP_URL` key in the env file.

### Reproduction steps

1. Configure a Docker install with an FQDN `APP_URL` and a fixed port (`-p 55080:80`) into the container
2. Log in
3. Observe a redirection to `http://127.0.0.1:55080` (for example)

### Expected behavior

I would expect the login form to use the `APP_URL` key for its redirections.

### Snipe-IT Version

v6.0.13 - build 8923 (master), Docker ID 9ab7645ab1e6

### Operating System

Debian with Docker

### Web Server

Nginx

### PHP Version

7.4.3

### Additional context

SnipeIT installed via Docker, using image ID `9ab7645ab1e6`

**Comment by uberbrady** [comment]
The only place it ever wants to redirect to is `APP_URL` - did you change that after you launched the container? It won't take effect if you do that, unfortunately. Or is there maybe some kind of proxy in front of it?

**Comment by zmeggyesi** [comment]
I did do a `docker restart` on the container, several times, in fact. Shouldn't that handle the config refresh?

And yes, there is an Nginx in front of it - perhaps I need to forward something there to the mapped Docker port?

**Comment by uberbrady** [comment]
I don't think so; I think you have to throw away the container and re-create it.

**Comment by zmeggyesi** [comment]
Let me try that tomorrow, and see if it fixes the issue.

Or maybe I could exec `php artisan config:cache` in the running container...?

**Comment by uberbrady** [comment]
Nope - won't work :(

**Comment by zmeggyesi** [comment]
Hmm, tried throwing the container away fully - and upgrading to `v6.1.0` while I'm at it - but it's still routes me to `127.0.0.1:55080` when logging in. 
The debug bar doesn't offer a lot of insight, since it's just a _Connection Refused_ at that point, not the PHP app...

What other info can I provide (and how, my strength is in Java, not PHP) to help?

**Comment by uberbrady** [comment]
Well, just as a troubleshooting step (you should avoid running this in production if you can) - you can try to set `APP_ALLOW_INSECURE_HOSTS` to `true` in your docker-env file, and then recreate the container - that allows you to come in on any URL you want. If it works after that, it's something on the Snipe-IT side that's the matter. If it *doesn't* work, it probably means the problem is on your proxy-side, not on the Snipe-IT side.

**Comment by zmeggyesi** [comment]
Huh: it did _not_ fix the redirection issue, but it _did_ make every single static resource - CSS, JS, images, etc. - try to load from localhost. It's like the app now thought _everything_ lives at `127.0.0.1:55080` and rendered that host into the HTMLs.

For instance:
```html
<link rel="stylesheet" href="http://127.0.0.1:55080/css/dist/all.css?id=29aefa88aeb1e2e938c741fd1aa15037">
<link rel="stylesheet" href="http://127.0.0.1:55080/css/dist/skins/skin-blue.css?id=392cc93cfc0be0349bab9697669dd091">
<link rel="stylesheet" href="http://127.0.0.1:55080/css/dist/bootstrap-table.css?id=ee4896df8b8f008ce73a9a0c2549aefd">
```

Perhaps I should forward the `Host` header to the container...?

**Comment by uberbrady** [comment]
Oh, I would definitely give that a try, since we are pretty hostname-sensitive - as you're seeing now. Another option you might want to try is to try to get Snipe-IT working OK _without_ any other proxy or front-end, and once everything is working OK, _then_ go and try to set up the proxy or whatever else is going on there - you'll at least know that your Snipe-IT instance is, in fact, working the way it's supposed to to start with.

**Comment by zmeggyesi** [comment]
That right there turned out to be the solution!
```
proxy_set_header Host $host;
```
We might want to put that in the docs somewhere, if Snipe-IT relies so heavily on the hostname.

Thanks for helping me debug this, your insight really helped me eliminate the non-issues.
