### ISSUE TITLE
[Bug] too many hidden columns in asset view for cookie

### ISSUE THREAD

**Issue by stampycode** [grokability/snipe-it#13256]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

hidden columns in asset view are stored in a cookie.
max cookie length is 4096 bytes.
our number of columns exceeds the cookie length when all column names are stored in the same cookie, so a lot of columns are always shown on page load, due to the cookie being truncated.

### Reproduction steps

1. have lots of columns
2. hide them all
3. the columns at the end are all displayed on refresh.

### Expected behavior

all hidden columns should remain hidden based on cookie preferences.

### Snipe-IT Version

v6.1.1 build 10847 (g2ac4449ea)

**Comment by snipe** [comment]
I mean, I'm not sure what the solve would be here though. We can't change how browsers handle cookies.

**Comment by stampycode** [comment]
Maybe splitting the list over multiple cookies, or switching to a `window.localStorage` method to store the list? No reason it has to be a cookie, it doesnt need to be sent to the server.

-------- Original Message --------

**Comment by snipe** [comment]
> No reason it has to be a cookie, it doesnt need to be sent to the server.

That's how the bootstrap table column selector works. I'm not sure there's a lot we can do to work around that.

**Comment by stampycode** [comment]
Please see response from @wenzhixin above, localStorage is an option on the bootstrap-table.

**Comment by snipe** [comment]
We have tried that before and it broke some of the other plugins in the past, but we can give it another shot.

**Comment by stampycode** [comment]
Thank you @snipe! ☺️

**Comment by snipe** [comment]
@stampycode This is now on `develop`. To switch to `localStorage`, there is a new `.env` var called `BS_TABLE_STORAGE`, so once this is merged to `master`, you'd want to add `BS_TABLE_STORAGE=localStorage` to your `.env` and clear your config cache via `php artisan config:clear`. (This defaults to `cookieStorage` so we don't break the "remembered" parts of everyone else's installs.)

https://github.com/snipe/snipe-it/pull/13302/files#diff-a3046da0d15a27e89f2afe639b25748a7ad4d9290af3e7b1b6c1a5533c8f0a8cR88

<blockquote><img src="https://avatars.githubusercontent.com/u/197404?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/snipe/snipe-it/pull/13302">Fixed #13256 - Added option to switch to localStorage instead of cookies by snipe · Pull Request #13302 · snipe/snipe-it</a></strong></div><div>This adds the ability to switch from cookieStorage to localStorage or sessionStorage in bootstrap table, which should be useful for folks with a LOT of custom fields hidden.
I set it to default to ...</div></blockquote>

Thanks for taking the initiative to investigate this further. While it *does* come up occasionally, we haven't seen it often, so I'm glad to make this into a setting to solve for folks with very large sets of hidden fields.

**Comment by stampycode** [comment]
That's very awesome thank you! However as we're currently using the hosted version, is there any chance we could get a config setting in there?

**Comment by snipe** [comment]
Ah, that *was* you on the helpdesk I was talking to. I'll get it handled for you once we merge to master. :)

**Comment by stampycode** [comment]
Actually I'm not sure that was me, but it may have been someone on my team!
I'm looking for access to the helpdesk now.... 👀
