### ISSUE TITLE
User field is Loading

### ISSUE THREAD

**Issue by joyanta86** [grokability/snipe-it#13273]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

after SSL configuration when I tried to check out the device to the user. The user field is loading

### Reproduction steps

1.
2.
3.
...

### Expected behavior

after SSL configuration when I tried to check out the device to the user. The user field is loading

### Screenshots

![snipe-it](https://github.com/snipe/snipe-it/assets/59603023/1de2f92d-0e53-4a02-8790-62e70e38ca44)

### Snipe-IT Version

v6.1.1-pre - build 10778 (master)

### Operating System

Ubuntu 20

### Web Server

Apache

### PHP Version

7.4

### Operating System

Windows

### Browser

Chrome

**Comment by marcusmoore** [comment]
Hi there @joyanta86,

Have you updated your `APP_URL` in `.env` to `https` after starting to use SSL?

**Comment by Dad-Ju** [comment]
hey @marcusmoore we got into it and we found out that the user is missing the `locations.view.selectlist` permission, this should apply when the user gets the `self.edit_location` or not?

Adding the Locations View Permissions doesnt let the user see the dropdown (because view.selectlist is still missing)

This seams to be a bug in the code!

![image](https://github.com/snipe/snipe-it/assets/26618439/ab977e4d-7493-4405-bc1c-a6a0a8d809b9)

**Comment by ozzman1021** [comment]
@marcusmoore your solution worked for me 
Thank you!

**Comment by marcusmoore** [comment]
Glad to hear @ozzman1021!

It's been a while since I heard back @joyanta86. I'm going to close this but feel free to ping me/re-open it if you're still having issues.
