### ISSUE TITLE
php upgrade.php does not report permission error

### ISSUE THREAD

**Issue by karlernstzenwesterncapegovza** [grokability/snipe-it#13345]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

On a Windows Server:
I switched to git install.
All worked well.
Asked me to check permissions on the laravel.log file. I created file without assigning permissions.
re-ran php upgrade.php and it did not complain about the file again.
got a 500 error after upgrade finished.

ran these commands since composer was out of date. checked php versions and settings
composer diagnose
composer update
git pull

----fix----
enabled debug and found the laravel.log permission issue.
on folder {projectroot}\storage
Added Modify permission for 
IUSR and servername\IIS_IUSR

### Reproduction steps

1.
2.
3.
...

### Expected behavior

Expected the laravel.log permission issue to be flagged by php upgrade.php

### Snipe-IT Version

Version v6.1.2 - build 10938 (master)

### Operating System

Windows

### Web Server

IIS

### PHP Version

7.4.30

### Operating System

Windows

### Browser

All

**Comment by lojacao** [comment]
Reproduction steps
1. Rename original project root.
2. Create a new folder with original project root name.
3. Follow switch to git install document https://snipe-it.readme.io/docs/switching-to-a-git-install
4.Work thru php upgrade.php, step 3 recommends to fix permission on rootFolder\storage\log\laravel.log. Create a new file, since one does not exist.
5. Error goes away, on re-run. Witness the 500 error.
6. In my case I ran composer diagnose and composer self-update --2 ; composer update
7. Avoided re-running php upgrade.php since it rolls back the composer updates.

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/switching-to-a-git-install">Switching to a Git Install</a></strong></div><div>As we mention (several times) throughout the documentation, installing via Git is our recommended way of installing Snipe-IT and keeping it up to date. If you installed manually (downloading a tarball or .zip file from Github), you can still switch to a Git install with just a little work. Doing so ...</div></blockquote>

**Comment by snipe** [comment]
You should never be running composer update. Doing so will overwrite our composer.lock, and it means your downloaded dependencies may not match the ones we ship with. upgrade.php will run `composer install`, which is the only thing you should be running there. (Additionally, on a git install, it means your version and ours will have conflicts, since your local file will have changes we don't have.) Using the upgrader does stash your changes specifically to avoid those version conflicts, but you always want to be using our composer lock, since we test everything and make sure that the dependencies work with the system correctly and within the requirements we document.
