### ISSUE TITLE
Install Problems

### ISSUE THREAD

**Issue by Noxx1986** [grokability/snipe-it#13411]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I'm trying to install snipe it on a VM Linux server...

the whole thing with Xampp there already exist 2 web projects under

"opt/lampp/htdocs/"

now i have created a folder for snipe-it with the path

"opt/lampp/htdocs/snipeit/

I then went through the instructions step by step

- database is created

But now I don't get the pre-setup page

my page looks soo
![image](https://github.com/snipe/snipe-it/assets/141613028/417691c7-0a53-43f7-81e4-8f72afb4d85c)

i don't really know anything about linux and i'm a bit desperate because i've been trying to install it for 3 days,
can somebody help me with my problem?

### Reproduction steps

1. snipe it downloaded
2. snipe it installed with install.sh
3. try to open snipe it with localhost/snipeit
4. error...
...

### Expected behavior

no idea...

### Screenshots

![image](https://github.com/snipe/snipe-it/assets/141613028/3b66ae8d-081c-4038-a457-4414f6f48e92)

### Snipe-IT Version

6.1.1

### Operating System

ubuntu 22.04

### Web Server

xampp 

### PHP Version

8.2.4

### Operating System

ubuntu

### Browser

firefox

**Comment by snipe** [comment]
First off, you're running PHP8.2, which we are not yet compatible with, per the [requirements documentation](https://snipe-it.readme.io/docs/requirements). Second off, it looks like the files are there, but your web server isn't set to the correct document root, and it's not set to use index.php/index.html as the directory index. You'd need to get those issues sorted (after downgrading PHP) before the pre-flight will come up.

https://stackoverflow.com/questions/5891802/how-do-i-change-the-root-directory-of-an-apache-server (this should point to the `public` directory within your Snipe-IT directory)

https://www.thesitewizard.com/apache/change-default-page-for-domain.shtml#:~:text=web%20server%20configuration.-,The%20Easiest%20Way,example.com%2F%22). - you'll want this to be `index.php`

<blockquote><img src="https://cdn.sstatic.net/Sites/stackoverflow/Img/apple-touch-icon@2.png?v=73d79a89bded" width="48" align="right"><div>Stack Overflow</div><div><strong><a href="https://stackoverflow.com/questions/5891802/how-do-i-change-the-root-directory-of-an-apache-server">How do I change the root directory of an Apache server?</a></strong></div><div>How can I change the document root of the Apache server? I basically want localhost to come from /users/spencer/projects directory instead of /var/www.

I ended up figuring it out. Some suggested I </div></blockquote>
<blockquote><img src="/favicon.ico" width="48" align="right"><div><strong><a href="https://www.thesitewizard.com/apache/change-default-page-for-domain.shtml#:~:text=web%20server%20configuration.-,The%20Easiest%20Way,example.com%2F%22">How to Change the Default Web Page that is Shown When Someone Goes to Your Domain Name (thesitewizard.com)</a></strong></div><div>How to change the page that is displayed whenever someone types in your domain name in their browser</div></blockquote>

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
