### ISSUE TITLE
Group Permissions not updating current profile permissions

### ISSUE THREAD

**Issue by jayavman** [grokability/snipe-it#13458]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I have a bunch of users that we have set permissions for them manually. I then went and created group permissions instead.
Once I assign the group permissions to the user it should automatically update them to the new group permissions but it doesn't. It will keep the current permissions we manually set and not auto change permission values.

### Reproduction steps

1. Set group permissions
2. go to user profile, change group permission
3. permissions don't show correctly the current group permissions you have now set in the profile.
4.
...

### Expected behavior

When users don't have inherent permissions set on the profile, and then assigned to a group with permissions. Permissions should then over-ride the current permissions the user has. 
Group permissions always have top level control.

### Snipe-IT Version

v6.1.2 build 10938 (g32747cafd) 

### Operating System

ubuntu

### Web Server

apache

### PHP Version

 8.1.22

**Comment by snipe** [comment]
This is expected behavior. 

> Users inherit permissions from the permission groups they are in, unless implicitly denied or granted permission on their user account.

https://snipe-it.readme.io/docs/permissions

You can manually blank out individual permissions (so that they inherit the group permissions) by running a mysql command to update those individual permissions to null. 

```sql
UPDATE users SET permissions = null;
```

But be advised that any users who do not belong to a permission group will be stripped of any permissions you granted them individually. 

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/permissions">Permissions</a></strong></div><div>Snipe-IT provides two privileged user account tiers, Admin and Superadmin, and a wide variety of more granular permissions for non-admin/non-superadmin users. RolePermissionSuperadminCan edit ALL admin settings, create new Groups, Locations, Status Labels, etc, and is NOT constrained by Company scop...</div></blockquote>
