### ISSUE TITLE
Preflight create user doesn't save user.

### ISSUE THREAD

**Issue by thomasbeaudry** [grokability/snipe-it#13596]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I am deploying snipe-it with the docker compose file (https://github.com/snipe/snipe-it/blob/master/docker-compose.yml).  My server has NGINX properly configured for my domain  (inventory.example.com).  When I start the preflight check list, i see the following check fails:

URL   Uh oh! Snipe-IT thinks your URL is https://inventory.example.com/setup, but your real URL is http://localhost:8077/setup Please update your APP_URL settings in your .env file

Despite this warning, I can continue to create a database, and then reach the "create user" page.  I fill out the fields, and click on save, and then it reloads the create user page with blank fields.

My .env.docker file has the field  APP_URL=https://inventory.example.com

### Reproduction steps

1.
2.
3.
...

### Expected behavior

for the user to be created, and the preflight terminate.

### Snipe-IT Version

latest

### Operating System

ubuntu

### Web Server

nginz

### PHP Version

8

**Comment by thomasbeaudry** [comment]
UPDATE:  I rebuild the container today, and I'm not failing the URL check anymore.  I still have the main issue of nothing being able to create the admin user that is persisting.

**Comment by snipe** [comment]
I couldn't tell you why that's happening - I can't reproduce it locally, but I'd bet it has something to do with a WAF, firewall, or some other network setting. Meantime you can create an admin through the command line to get you started: https://snipe-it.readme.io/docs/create-an-admin

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/create-an-admin">Create an Admin</a></strong></div><div>Since v3.0, we've added the rescue utility to add an admin user via the command line. This can be helpful if you've managed to lock yourself out of your installation (for example if you can't remember your password and never set the system up to send email.)Shell/path/to/php artisan snipeit:create-a...</div></blockquote>

**Comment by thomasbeaudry** [comment]
I created the admin user, but the preflight check still happens every time I visit my page.  How do i disable that?

**Comment by jdrakey** [comment]
I'm having the issue where I'm stuck on step 3 as well. I'm on a windows box using IIS. I used getcomposer.org.  I get the email sent, It says it created the database but won't get past the add user.  I don't get any errors. I've tried adding the admin user as stated above with the same user hoping it might find it. But still stuck on step 3. 

Running PHP 8.3.10
Running Mariadb10.5
Running on MS Window Server 2022
Ran composer check-platform-reqs ( success ).
Done the common problems. verified php extensions, cleared php caches

Not sure what to do next. 

Appreciate any help.
