### ISSUE TITLE
Error:: Please check the form below for errors. Trying to setup snipe-it as subdirectory.

### ISSUE THREAD

**Issue by Eamll** [grokability/snipe-it#13615]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Can't change admin settings. I can do all other operations but change admin settings. When pressing the save button I get the Error:: Please check the form below for errors. I want to be able to run other projects in other subdirectories while having snipe-it installed.

![image](https://github.com/snipe/snipe-it/assets/50913589/7338001d-121e-4764-9545-56c69a796ddf)

### Reproduction steps

1. Normal installation of snipe-it
2. Setup .env

```
APP_ENV=development
APP_DEBUG=true
APP_KEY= <Actual App Key>
APP_URL=http://<Actual Server Address>/snipe-it
APP_TIMEZONE='America/La_Paz'
APP_LOCALE=en
MAX_RESULTS=500
```

4. Setup 000-default.conf

```
<VirtualHost *:80>
    Alias /snipe-it "/var/www/html/snipe-it/public"
        <Directory /var/www/html/snipe-it/public>
                Allow From All
                AllowOverride All
                Options +Indexes
        </Directory>

        DocumentRoot /var/www/html/
        ServerName <Actual Server Address>
        # Other directives here
</VirtualHost>
```
5. Setup .htaccess in /public folder
```
    RewriteEngine On
    RewriteBase /snipe-it

```
6. Setup pre-flight and then try to change admin setting

### Expected behavior

To save any admin setting.

### Snipe-IT Version

v6.2.0-pre build 11531 (g20da6cccb)

### Operating System

Ubuntu 20.04

### Web Server

Apache2

### PHP Version

7.4.3-4ubuntu2.19

#### Is this a fresh install or an upgrade?
Fresh Install.
#### What OS and web server you're running Snipe-IT on
Ubuntu 20.04 using Apache2.
#### What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual installation.
#### Include what you've done so far in the installation, and if you got any error messages along the way.
No errors.
#### Indicate whether or not you've manually edited any data directly in the database
Didn't edit db.
#### Add any other context about the problem here.
I'm using postgresql. Installed everything as root user.

**Comment by snipe** [comment]
Hm, I'm not able to reproduce this locally. What happens if you check, save, then uncheck those options on the Security page in the admin?

**Comment by Eamll** [comment]
This happens when I try to save any Security setting, doesn't matter if the options are checked or unchecked.
The error is not the db user(most probably), just in case, i've tried to do it on my local machine and in production. Same error even giving all permissions to db user. And the folder is with 777 permissions.

![image](https://github.com/snipe/snipe-it/assets/50913589/42a5211e-46af-4589-b92b-ddb9a3f916be)

**Comment by Eamll** [comment]
I just did a fresh install in the subdirectory. It works well if using MySQL but it has the mentioned problem when using Postgres. We wanted to use an existing server that we had but it seems like a snipe-it query is not working as intended. Tested in PostgreSQL 10.7 and PostgreSQL 12. Tried with db being hosted locally and a remote db. I'll provide more details if needed.

I just noticed, it says in the documentation that it doesn't support PostgreSQL, sorry for wasting your time. Feel free to delete the issue.

**Comment by snipe** [comment]
Thanks for the follow up. We don’t strictly-speaking support Postgres, but it should work. I’ll take a look and see if we’re not setting a default value for those two fields

**Comment by landryb** [comment]
fwiw, i've just setupped a 6.4.2 with php 8.1 on OpenBSD, using psql 16, and regular usage mostly seems to work (eg creating locations/categories/assets), but saving settings fails the same way as reported in this issue.

i've added some debug printfs to display errors, and the `$setting->save` call in https://github.com/snipe/snipe-it/blob/master/app/Http/Controllers/SettingsController.php#L374 fails:

```
 save failed: {"login_remote_user_enabled":["The login remote user enabled must be a number."],"login_common_disabled":["The login common disabled must be a number."]}
```
in the database, those two fields in the settings table are `boolean`. I'll see if i can understand where this *has to be a number* comes from. I've tried dropping the two `(int)` casts in https://github.com/snipe/snipe-it/blob/master/app/Http/Controllers/SettingsController.php#L527 but that didnt help.

what isnt really helpful is that the page only displays **Error: Please check the form below for errors ** but doesnt actually display the error message :) ok, i'll turn on the debug mode to try to understand laravel console ..

@snipe, should this issue be reopened ? (even if psql is not supported, im aware that it's a best effort target)

<blockquote><img src="https://repository-images.githubusercontent.com/14346979/164a6580-7d79-11e9-865f-eae87593e11a" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/snipe/snipe-it/blob/master/app/Http/Controllers/SettingsController.php">snipe-it/app/Http/Controllers/SettingsController.php at master · snipe/snipe-it</a></strong></div><div>A free open source IT asset/license management system - snipe/snipe-it</div></blockquote>
<blockquote><img src="https://repository-images.githubusercontent.com/14346979/164a6580-7d79-11e9-865f-eae87593e11a" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/snipe/snipe-it/blob/master/app/Http/Controllers/SettingsController.php">snipe-it/app/Http/Controllers/SettingsController.php at master · snipe/snipe-it</a></strong></div><div>A free open source IT asset/license management system - snipe/snipe-it</div></blockquote>

**Comment by landryb** [comment]
not knowing much about laravel/php frameworks but digging more, i'm also seeing a 500 error code if i try to save on the security settings tab with `ERROR:  null value in column "login_remote_user_custom_logout_url" of relation "settings" violates not-null constraint` like @Eamll .

it feels strange because from my understanding of https://github.com/snipe/snipe-it/blob/master/app/Models/Setting.php#L69 those fields are 'nullable'. When i try to print the value of `login_remote_user_enabled` & `login_common_disabled` in `postSettings`, they're empty/undefined, so why is the framework complaining about them not being numbers, as they're nullable ?

ok, in the database, they're not..
```
 login_remote_user_enabled           | boolean                        |           | not null | false
 login_common_disabled               | boolean                        |           | not null | false
 login_remote_user_custom_logout_url | character varying(191)         |           | not null | ''::character varying
```

fiddling with the database table, i'm able to save security settings once i've removed the `not null` constraint
```
snipeit=# alter table settings alter login_remote_user_header_name drop not null; 
snipeit=# alter table settings alter login_remote_user_custom_logout_url drop not null; 
```
but doing the same for `login_remote_user_enabled` & `login_common_disabled` wasnt enough to fix saving settings in `postSettings` - it also choked on `require_accept_signature` being null.

so i checked for the value of `$setting->login_remote_user_enabled` & `$setting->login_common_disabled` and if they're empty i set them to 0.

with those 3 fields having their `not null` constraint dropped, i can save 'general settings'. but not 'branding settings'... it feels like trial-n-error to figure out which fields have wrong constraints/no proper defaults (should they come from the db ?).

<blockquote><img src="https://repository-images.githubusercontent.com/14346979/164a6580-7d79-11e9-865f-eae87593e11a" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/snipe/snipe-it/blob/master/app/Models/Setting.php">snipe-it/app/Models/Setting.php at master · snipe/snipe-it</a></strong></div><div>A free open source IT asset/license management system - snipe/snipe-it</div></blockquote>

**Comment by landryb** [comment]
ah, and i had seen #1920, but i didn't see #7600 which is also the same symptoms, where the proposed solution is to convert the `boolean` columns to `int2`. But doing so, i'm not fully sure future database schema migrations will work...
