### ISSUE TITLE
[Feature Request]: additional API endpoints for consumable to checkout/checkin 

### ISSUE THREAD

**Issue by rainer-c49** [grokability/snipe-it#13760]
### Is your feature request related to a problem? Please describe.

We would like to checkout and checkin accessories via API (similar to consumables) and this is currently not possible, because the necessary APIs are missing.

### Describe the solution you'd like

The accessories API already contains the endpoints to read all users that [_checkedout_](https://snipe-it.readme.io/reference/accessoriesidcheckedout) an accessory and to [_checkin_](https://snipe-it.readme.io/reference/accessoriesidcheckin) an accessory again. 
The solution would be to offer the same APIs for consumables as well.

**Comment by snipe** [comment]
I'm unclear as to how consumables factors in here? Consumables are never checked in, they are consumed. 

The accessory API endpoint for checking in accessories already exists.

https://snipe-it.readme.io/reference/accessories-checkin
https://snipe-it.readme.io/reference/accessories-checkout

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/reference/accessories-checkin">/accessories/:id/checkin</a></strong></div><div>Checkin an accessory from a user</div></blockquote>
<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/reference/accessories-checkout">/accessories/:id/checkout</a></strong></div><div>Check an accessory out to a user</div></blockquote>

**Comment by snipe** [comment]
Consumables checkout API is here: https://snipe-it.readme.io/reference/consumablesidcheckout

As mentioned, there is no checkin, since consumables by nature are not checked in.

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/reference/consumablesidcheckout">/consumables/:id/checkout</a></strong></div><div>Check an accessory out to a user</div></blockquote>
