### ISSUE TITLE
[Feature Request]: Display further information when installation fails

### ISSUE THREAD

**Issue by VewDev** [grokability/snipe-it#13918]
### Is your feature request related to a problem? Please describe.

When installing SnipeIT, you sometimes get a blank screen. Even if debug is turned on, you sometimes get either a simple 500 error with no information or the same blank page.

When troubleshooting this myself (solved it, was an issue with installation script #13917), found that this was a rather common problem several issues stumbled upon, and opened related issues:

- #11402 
- #4871 
- #8429 
- #11543 
- #4681 
- #7942 
- #7114 
- Just google "SnipeIT blank screen" and there's a lot of similar issues

The blank page leaves users clueless about the reason why the app is not working (specially since it usually happens after fresh install or some sort of update). Quick google search for troubleshooting shows you a variety of similar issues (linked above) which might not work for your case, since the error is unspecified.

Having some sort of error code and description instead of the blank page would make troubleshooting easier for the end user and relieve some support workload.

### Describe the solution you'd like

If the app is "succesfully" running and the error can be known (ie: permission denied on storage folder), display information about the error and troubleshooting steps.

If the app could not start for whatever reason (ie: php not running), display a generic error stating that the app could not be started.

Would be cool to also have a link to the common issues page and instructions on how to get community help over github in both cases. Maybe also some instructions on how to check the apache/php log files for unexperienced users trying to install the app.

**Comment by snipe** [comment]
Hey there - so, we do actually document spaces/quotes in the .env file pretty clearly in the docs:

https://snipe-it.readme.io/docs/configuration

<img width="812" alt="Screenshot 2023-11-22 at 9 04 54 AM" src="https://github.com/snipe/snipe-it/assets/197404/40ada987-6797-4b22-8581-0cb349294549">

Our app is written in PHP, so you can see that if PHP isn't running, we can't display a message (via PHP).

The install.sh script is meant to be a shortcut to install php/apache/etc, but it's the least common, least recommended, and least supported way of installing Snipe-IT, since so many other things could potentially go wrong (SELinux, networking issues, DNS, etc). We have a bevy of other ways to install Snipe-IT that work just as well or better. It's kind of not our job to troubleshoot linux, and it would be nearly impossible for us to do so if we wanted to.
