### ISSUE TITLE
Accessory check-in not recording the correct time.

### ISSUE THREAD

**Issue by noahammond** [grokability/snipe-it#14037]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

My colleague has been checking in some returned accessories from clients and noticed 2 things:
1) The check-in sometimes fails (we haven't been able to reproduce this issue) It says in the history that the device was checked out but doesn't actually change the status.
2) The check-in time sets itself to the correct date but the time is 12:00AM.
The check-out time is correct but the check-in time always sets itself to 12:00AM.

### Reproduction steps

1. Check-out any accessory 
2. Check-in any accessory
3. Check history to verify time and check-out status
...

### Expected behavior

The time should be accurate.

### Screenshots

![Screenshot 2023-12-14 150330](https://github.com/snipe/snipe-it/assets/81579778/e4cd121e-084c-465c-b95e-314883c77ba6)

### Snipe-IT Version

Version v6.2.3 - build 11759 (master) 

### Operating System

unsure

### Web Server

unsure 

### PHP Version

unsure

### Operating System

Windows 11 Enterprise

### Browser

Google Chrome

**Comment by snipe** [comment]
That's not exactly a bug, just a confusing way it's handled. Since we let you specify checkin date (which might not be today), we can't just assume the time. If you're checking something in in the future, or let's say you're checking it in from the past because it was already checked in, we don't expect you to know or care about the time. 

I can see if we can't at least check to see if the date is today, and if so, adopt the current time though.

**Comment by noahammond** [comment]
I was under the impression that this might be a bug because it's not an issue for Assets:
![Screenshot 2023-12-14 155256](https://github.com/snipe/snipe-it/assets/81579778/9b3e1c47-6c20-4625-8d25-1f93935551ee)

**Comment by snipe** [comment]
This fix is on master now
