### ISSUE TITLE
MISSING PHP EXTENSION:bcmath

### ISSUE THREAD

**Issue by 00717747** [grokability/snipe-it#14048]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Trying to upgrade to the latest version from 5.1.1 on ubuntu and it keeps saying the some extension is missing. 

i dont mind installing it but the documentation wont load for me to install it and I avent found the right thing on google. can you assist me please?

### Reproduction steps

1.
2.
3.
...
php upgrade.php

### Expected behavior

Upgrade to start

### Screenshots

![Snipe IT upgrade](https://github.com/snipe/snipe-it/assets/154071246/04c42f44-1cd6-4670-ba00-113abc3d13c7)

### Snipe-IT Version

5.1.1

### Operating System

ubuntu 20.0.8

### Web Server

Apache

### PHP Version

7.2

### Operating System

Ubuntu

### Browser

Google Chrome

### Version

120

### Error messages

```shell
-------------------- !! ERROR !! ----------------------
✘ MISSING PHP EXTENSION: bcmath
✘ MISSING PHP EXTENSION: curl
✘ MISSING PHP EXTENSION: gd OR imagick
✘ MISSING PHP EXTENSION: ldap
✘ MISSING PHP EXTENSION: mbstring
✘ MISSING PHP EXTENSION: mysqli OR pgsql
✘ MISSING PHP EXTENSION: xml
✘ MISSING PHP EXTENSION: zip
------------------------- :( ---------------------------
ABORTING THE INSTALLER  
Please install the extensions above and re-run this script.
------------------------- :( ---------------------------
```

### Additional context

Upgrade

**Comment by snipe** [comment]
We don't provide information on how to install extensions in PHP in our documentation, since that's outside the scope. A quick google search should get you there though.

https://xpertdeveloper.com/install-bcmath-extension-in-php/
https://stackoverflow.com/questions/38800606/how-to-install-php-curl-in-ubuntu-16-04
etc 

<blockquote><img src="https://static.xpertdeveloper.com/uploads/2018/07/Install-bcmath-in-php.jpg" width="48" align="right"><div><img src="https://xpertdeveloper.com/wp-content/uploads/2020/07/128x128.png" height="14"> Xpert Developer</div><div><strong><a href="https://xpertdeveloper.com/install-bcmath-extension-in-php/">Install BCmath Extension in PHP</a></strong></div><div>PHP offers various extensions to deal with different cases. BCMath is one of PHP extension which helps us while working with float values in PHP. In BCMath, BC Stands for Binary Calculator. In this article, we will see how to Install BCMath Extension in PHP on various platforms.</div></blockquote>
<blockquote><img src="https://cdn.sstatic.net/Sites/stackoverflow/Img/apple-touch-icon@2.png?v=73d79a89bded" width="48" align="right"><div>Stack Overflow</div><div><strong><a href="https://stackoverflow.com/questions/38800606/how-to-install-php-curl-in-ubuntu-16-04">How to install php-curl in Ubuntu 16.04</a></strong></div><div>Upgraded to Ubuntu 16.04 and facing problem after installing PHP5.

Installed PHP-5 with following:

sudo add-apt-repository ppa:ondrej/php
sudo apt-get update
sudo apt-get upgrade
sudo apt-get ins...</div></blockquote>
