### ISSUE TITLE
Asset Model Default Values Checkbox Error

### ISSUE THREAD

**Issue by godnroc** [grokability/snipe-it#14202]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When attempting to set a default value in a new asset, if a checkbox custom field is selected the default value is rejected and any previously saved default values are removed. An error of "Error validating default fieldset values." is shown.

### Reproduction steps

1. Create a custom field with the checkbox type. Populate with options.
2. Assign the custom field to a fieldset.
3. Create a new asset model.
4. Select the fieldset for the new asset model.
5. Check the option to include default values.
6. Check one or more of the checkbox values.
7. Attempt to save the asset.

### Expected behavior

The checked values should be saved and used as the default when creating a new asset with that model.

### Screenshots

Custom field for printer functions.
![image](https://github.com/snipe/snipe-it/assets/2201722/6da5d5c9-3dd7-4b0d-9c9f-d45f7963ed71)

Fieldset with the field contained therein.
![image](https://github.com/snipe/snipe-it/assets/2201722/d525bc74-580c-4b39-b95e-19ee96ac7a38)

Attemping to add the default value to a newly created asset model.
![image](https://github.com/snipe/snipe-it/assets/2201722/179e8ce5-eefb-4aa0-a3ca-1e980993c590)

The error the occurs when trying to save.
![image](https://github.com/snipe/snipe-it/assets/2201722/e976d86f-559c-4736-a40d-c559841f9082)

### Snipe-IT Version

6.3.0

### Operating System

Hosted

### Web Server

Hosted

### PHP Version

8.1.23

### Operating System

Windows

### Browser

Edge

### Version

121.0.2277.83 (Official build) (64-bit)

**Comment by SimBeo** [comment]
Same Problem, same way

No problem for listbox or radio.

**Comment by Kedeir** [comment]
Same Problem

**Comment by leclou69** [comment]
Same here

**Comment by reggiepack** [comment]
I am having the same issue.

**Comment by FTTG** [comment]
Wanted to add a comment saying I am having the exact same issue. I am trying to set a field for monitors and PCs showing what video ports they have as a checkbox field, so when I need to look for replacements, I can just easily find something that is compatible with it.

Get that exact same issue when trying to save the model default value (so I don't need to manually add it multiple times for same model monitors)

Hopefully this gets a reply soon. @uberbrady thank you in advance, I know the team is hard at work with multiple tickets and updates, the app is otherwise great aside from this one issue I have.

**Comment by godnroc** [comment]
Just tested on the demo version for V6.3.4 and I believe this has been fixed.
