### ISSUE TITLE
500 Server Error after upgrading Ubuntu 20.04 -> 22.04

### ISSUE THREAD

**Issue by tolmbrae** [grokability/snipe-it#14526]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Initially, PHP code displayed in web browser after upgrading server. After solving that issue, browser shows 500 | Server error when navigating to Snipe-IT Asset server URL.

### Reproduction steps

1. Upgrade Linux Ubuntu 20.04 to 22.04
2. Resolve PHP code displaying in browser via `a2enmod php8.1`

### Expected behavior

Arrive at Snipe-IT assets login screen.

### Screenshots

![Screenshot 2024-03-29 at 4 29 14 PM](https://github.com/snipe/snipe-it/assets/46572567/a1ba3357-7970-4967-9110-95950ded68a2)
![Screenshot 2024-03-29 at 4 27 27 PM](https://github.com/snipe/snipe-it/assets/46572567/928c7a5d-f443-4c7c-b870-16473a5d22a3)

### Snipe-IT Version

v6.0.4 build 8050 (gb448c8965)

### Operating System

Ubuntu 20.04

### Web Server

Apache

### PHP Version

7.4.3-4ubuntu2.20

### Operating System

macOS 14.2.1

### Browser

Safari

### Version

17.2.1

### Error messages

```shell
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
```

### Additional context

Upgraded Ubuntu 20.04 to 22.04.

Installed Snipe-IT via git clone.

**Comment by snipe** [comment]
https://laraveltips.io/how-to-fix-the-could-not-find-driver-error-in-laravel/

<blockquote><img src="https://laraveltips.io/wp-content/uploads/2023/09/How-to-fix-the-Could-Not-Find-Driver-error-in-Laravel.png" width="48" align="right"><div><img src="https://cdn-jjplh.nitrocdn.com/diONQasbEkZCaIkyfzqUmaViEqwxCRqF/assets/images/optimized/rev-d07513d/laraveltips.io/wp-content/uploads/2023/02/cropped-Laraveltips-Favicon-192x192.png" height="14"> Laravel Tips - "Innovative web development for a digital age"</div><div><strong><a href="https://laraveltips.io/how-to-fix-the-could-not-find-driver-error-in-laravel/">How to fix the “Could Not Find Driver” error in Laravel</a></strong></div><div>The "Could Not Find Driver" error in Laravel is a common error that can occur when you are trying to connect to a database. This error can be caused by a number of things, including: The PDO extension is not installed or enabled. The PDO driver for your database is not installed. You are using</div></blockquote>

**Comment by tolmbrae** [comment]
@snipe Thank you, that resolved it!
