### ISSUE TITLE
authentication problem

### ISSUE THREAD

**Issue by aelhajjaji** [grokability/snipe-it#14806]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

i have a problem to login into snipe it after ldap sync; i use the same username & password but it doesn't work. I tried to create a new user directly in the database but it still doesn't work. for the hash password I generated it through this web site 'https://generate-random.org/encryption-key-generator' . I also changed the flag "ldap_import"  of my account that I used before  from 1 to 0 but it does not work either. Could you please help me on this point because I'm really stuck.

### Reproduction steps

1.login into snipe-it is impossible  he show me that the username & password are wrong.

### Expected behavior

there is no Expected behavior

### Screenshots

![Uploading snipe it 6.JPG…]()
![Uploading snipe it 9.JPG…]()

### Snipe-IT Version

unknown

### Operating System

ubuntu 

### Web Server

apache

### PHP Version

8

**Comment by snipe** [comment]
You can use the admin user generator to create a local user: https://snipe-it.readme.io/docs/create-an-admin

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/create-an-admin">Create an Admin</a></strong></div><div>Since v3.0, we've added the rescue utility to add an admin user via the command line. This can be helpful if you've managed to lock yourself out of your installation (for example if you can't remember your password and never set the system up to send email.) &lt;button aria-selected="true" class="Co...</div></blockquote>

**Comment by aelhajjaji** [comment]
when I put the command it shows me this:
![error](https://github.com/snipe/snipe-it/assets/171365413/29de6c39-c8a7-4703-ab19-398ccbdc5826)
