### ISSUE TITLE
can not bulk request/bulk check in/bulk check out?

### ISSUE THREAD

**Issue by huifei0129** [grokability/snipe-it#14946]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

1、Can not bulk request
need to click one by one
![bulk request](https://github.com/snipe/snipe-it/assets/156650496/be508b69-fbeb-4bf5-a77d-23668edb7974)

2、Requested SOP
(1) need to checkin first (Status: ready to deploy)
(2) later check out to the request user
3、but can not "bulk checkin" and "bulk checkout"
need to click one by one
![bulk requested](https://github.com/snipe/snipe-it/assets/156650496/bc0aefc2-28a3-4c65-a20c-0be6cb90bb48)

4、what is the different between the two "requestable"
![Request different](https://github.com/snipe/snipe-it/assets/156650496/4d258cb2-3fcc-44d9-b5b6-ec07477e7899)

### Snipe-IT Version

v6.4.2 build 13487 (gb489c71fa2)

### Operating System

Ubuntu, Windows

### Web Server

Apache

### PHP Version

8.1.2-1ubuntu2.18

### Operating System

windows

### Browser

google

**Comment by snipe** [comment]
There isn't currently a way to bulk request assets, since that's just not a use-case we see very often. Usually a user will request a keyboard or a display, not hundreds of items.

As for the difference between 1 and 3, 1 is a filter on all assets, which is only available to users with the ability to manage assets, where 3 would be visible to any user who can *request* assets.

Also, please calm down with the triple question marks. It's a bit insulting.

**Comment by huifei0129** [comment]
sorry to use the wrong "?"
thanks very much for your reply 
and your effort.
