### ISSUE TITLE
[Feature Request]: Show EOL Date to the User

### ISSUE THREAD

**Issue by SebastianKlimczok** [grokability/snipe-it#15103]
### Is your feature request related to a problem? Please describe.

Currently in order to know, when a device is EOL or over the minimum usage time and has to get exchanged, the user has to ask us directly. There is no way to show the EOL Date directly in SnipeIT to the user.

### Describe the solution you'd like

An option to enable the EOL date on the User view-asset#asset page in the checked out asset table

### Describe alternatives you've considered

Showing other column for a similar purpose (e.g. Expected Checkin Date)
Showing custom fields with references to the current date (e.g. checkout date + 3 years)

**Comment by huifei0129** [comment]
one way to achieve
fix company and user permission "View"
![image](https://github.com/user-attachments/assets/4fe9eb4a-bd0a-4c5d-aad5-2a0ae37010b9)

**Comment by Norjek** [comment]
Hi @SebastianKlimczok & @huifei0129

+1 from my side

However, @huifei0129: Your solution does not work for us. We have the same problem as Sebastian. Our end users should not see all the equipment of their entire company. Every user should only see the devices checked out to him or herself, but be able to see how old these are.
In the end, I have them running up to my desk or the one of the companies key user and asking us questions which they could see themself in the assigned asset page, if we'd be able to add a few more columns there.

Perhaps I am just to stupid to give a user view permission to the users assets only? How would that work? But then again, this would give them permissions to see the history, notes and stuff as well? And not sure if my clients feel well with that...

So would definitively be nice if I could add a few columns to the assigned asset page for end users and show them the EOL of their devices, in order to enable them to plan ahead any device exchanges (people get pretty serious about getting new stuff!)

**Comment by snipe** [comment]
This is now on master and will be in the next release.
