### ISSUE TITLE
ERROR: Custom status label and snipeit native status label Confuse

### ISSUE THREAD

**Issue by huifei0129** [grokability/snipe-it#15179]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Firstly, creat a new custom status label named "Ready to deploy".

Second, when check in a single asset, both custom status label and snipeit native status label display one asset. It is correct.
![image](https://github.com/user-attachments/assets/3ec55000-1ac3-406f-aec8-849d3bba4987)

Third, after check out the asset under snipeit native status label. Something is wrong
Error one: Snipeit native status label will display zero, but the custom status label still display one.
![image](https://github.com/user-attachments/assets/b6b6f044-3924-4e16-abc7-a2224bb0a62c)

Four, if I check out the asset under custom status label. The same error.
![image](https://github.com/user-attachments/assets/663a6afd-3a74-4d11-bda1-8f3df8bd6de1)

Eventually, When Check out the asset and select status into "Deployable", not error.
![image](https://github.com/user-attachments/assets/1e76bbe3-1c7b-4d14-a818-f1b1146a67d6)
![image](https://github.com/user-attachments/assets/cf2b7b2f-b7f3-4864-945b-fe721a6145ff)

So I think after check out when select the status "Ready to deploy",
1、snipeit native status label default change status into "Deployable".--------important
but the menu left is "Ready to deploy"
![image](https://github.com/user-attachments/assets/6045fa5c-b137-4d69-99c6-1019a4dc68c4)

2、custom status label remain the status "Ready to deploy"

### Reproduction steps

1. creat a new custom status label named "Ready to deploy".
2. when check in a single asset, both custom status label and snipeit native status label display one asset. It is correct.
3. after check out the asset under snipeit native status label. Something is wrong
4. if I check out the asset under custom status label. The same error.
5. Eventually, When Check out the asset and select status into "Deployable", not error.
So I think after check out when select the status "Reday to deploy",
1、snipeit native status label default change status into "Deployable".--------important
2、custom status label remain the status "Reday to deploy"
...

### Expected behavior

Hope to solve it
Thanks for your support

### Snipe-IT Version

 Version v7.0.9 - build 14371 (master)

### Operating System

Ubuntu, Windows

### Web Server

Apache

### PHP Version

8.1.2-1ubuntu2.18

### Operating System

windows

### Browser

google

**Comment by snipe** [comment]
What you're seeing in the sidebar isn't a "native" status label, it's the *kind* of status label. 
https://snipe-it.readme.io/docs/overview#status-labels

If you call your own status label something other than "Ready to Deploy", this will become more clear.

The labels in the sidenbar show in a solid dot, the "types" show in the hollow dot. Your screen shots are correctly showing that once you check out an item, you should change its status label to something other than "Ready to Deploy", since it's no longer ready to deploy, it's deployed. If you don't change the status label on checkout to something that reflects this, it can be confusing. Changing it to the "Deployable" status label on checkout is only going to add more confusion. 

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/overview#status-labels">Overview</a></strong></div><div>When your Snipe-IT installation is first set up, it can be a little overwhelming to figure out where to get started. The first place to start is usually your Admin Settings. We go through each of the specific admin options one by one in the Admin Settings section of this documentation, but that's wh...</div></blockquote>
