### ISSUE TITLE
Logo in email is too big

### ISSUE THREAD

**Issue by swift2512** [grokability/snipe-it#15236]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

It's more aesthetics when a bug, but it looks like this 570px creeped in during intense coding session. 150-200 px would look better. Such big image in email looks meh... 
(Disregard 1024x1024 - for testing purposes only)
![image](https://github.com/user-attachments/assets/4b3e33ed-9e3f-493d-8b86-cac70396089c)

570px found in these files:
snipe-it-7.0.10\resources\views\notifications\markdown\asset-requested.blade.php
snipe-it-7.0.10\resources\views\notifications\markdown\checkin-accessory.blade.php
snipe-it-7.0.10\resources\views\notifications\markdown\checkin-asset.blade.php
snipe-it-7.0.10\resources\views\notifications\markdown\checkout-accessory.blade.php
snipe-it-7.0.10\resources\views\notifications\markdown\checkout-asset.blade.php
`<center><img src="{{ $item->getImageUrl() }}" alt="Asset" **style="max-width: 570px;">**</center>`

### Reproduction steps

Just send confirmation emails.

### Expected behavior

Logo doesn't use all readable space in in Outlook (or other email client)

### Screenshots

![image](https://github.com/user-attachments/assets/667af8c1-da31-4fa9-a330-40a7a29297b9)
![image](https://github.com/user-attachments/assets/0fe9b414-b892-4e7c-9240-5b35a5198496)

### Snipe-IT Version

7.0.10

### Operating System

-

### Web Server

-

### PHP Version

-

**Comment by snipe** [comment]
You can upload a separate email logo that works better with the email layout.

**Comment by swift2512** [comment]
I understand, but 570 is an overkill in an email. Who needs such big logo in their emails? :) 
Also, it's worth to mention that Site Logo is used automatically when email logo isn't uploaded. In my case, I use 512x512 logo for the site  and it doesn't look good in emails. (I don't have SVG and raster doesn't compress well in Gimp)

**Comment by snipe** [comment]
We give you the ability to upload an email image specifically because we don't know what the dimensions of your logo might be (wide and short, taller and more square, etc.) Just upload a separate image for email. Use the tools we already provide for you. (Who needs a 512x514 logo on the website, by that logic.) There are lots of online image resizing tools. https://imageresizer.com

<blockquote><img src="/social.png" width="48" align="right"><div><strong><a href="https://imageresizer.com">Image Resizer | Easily Resize Images Online for FREE</a></strong></div><div>Image Resizer. Quickly resize image files online at the highest image quality. No software to install and easy to use.</div></blockquote>

**Comment by swift2512** [comment]
Logo resizes nicely as Site Logo, but it doesn't in emails. And why Site Logo shows in emails? Maybe I don't want logos is emails. :) Do I need to edit php files or env settings?

**Comment by snipe** [comment]
> Logo resizes nicely as Site Logo

That's why you upload a different one. One for each purpose.

Upload a clear gif as your email logo if you don't want one. 

I swear I feel like you just find things to open issues about. That code isn't even getting the logo - that's getting the image of the item being requested, checked out etc:

```
<center><img src="{{ $item->getImageUrl() }}" alt="Asset" **style="max-width: 570px;">**</center>
```

The mail template logo code is here:

https://github.com/snipe/snipe-it/blob/28abb8d8cc269af554f562bac639124e3cf5bc3d/resources/views/vendor/mail/html/message.blade.php#L16-L44

**Comment by swift2512** [comment]
Sorry for me wanting the product to look professional out of the box. I am not a programmer, so I'm not good at finding correct code, either. But why is it wrong to show sides of product that are bad in terms of user experience? I've spent years doing QA and translations, I've met many developers. Sadly, with Snipe-IT I feel this vibe some small teams have: "our product is flawless, even if it's not, - take it or leave it, or make one yourself." You are loosing customers with such approach.

For user to dance around all the quirks software has - bad experience. Only 23% of displays worldwide are 1920x1080, but your team decides that it's OK to allocate 600px for a logo. You do not see anything wrong with that?
![image](https://github.com/user-attachments/assets/a22b21db-9e1d-4688-a9e8-fd809abd1044)

I specifically didn't upload email logo, because I don't need any in my emails. Yet, Snipe-IT decides that I need one and uses Site Logo for emails. "It's a feature - not a bug?" Why do I need to add 1x1 px blank gif as Email logo?

While text in 'Admin > Branding says' Square logos look best with Logo + Text. Logo **maximum display size is 50px high x 500px wide.** your own Snipe-IT logo is 78px high. Why does system allow to upload anything higher than 50px, and more importantly - why then max-height is 600px in emails? (Firefox shows it through F12)

When going through an activity history, I found that PDFs are generated when person signs and accepts assets. In this PDF full logo is displayed. Where in the Admin settings or Snipe-IT documentation does it say that Snipe-IT will use full size logo for the documents? :) 
![PDF](https://github.com/user-attachments/assets/9cd6f332-243f-4536-bd81-afb4244c2277)

**Comment by snipe** [comment]
We absolutely do not think the product is perfect, and have never implied as much, however intentionally uploading a gigantic logo is also a weird thing to do, when resizing it to the size you actually want seems like a pretty normal thing for a user to do. Since we don’t know what every logo will look like, we can’t guess what it will look like in emails. Additionally, uploading a giant image is going to slow down page loads, so it’s generally an overall bad idea. That’s not because of anything we do, it’s just how the internet works.

We always appreciate a heads up on things we can improve on, but this particular detail seems like it’s solvable by the user as easily (or more so) as by us, and in every single issue you open here, you never have anything nice to say about any of the things (and there are many) that we do right. We’re glad for the heads up, but you could soften some of these issues by sounding a little more supportive of the hard work and attention to detail we have in addition to the things we miss. That’s just called “being nice”. Additionally, whenever we change something, even the size of a logo, we always impact other people with different workflows, and it’s our responsibility to bear that in mind.

We’re not losing customers over this issue. We’ll take a look at it but it’s lower priority over more important issues we’re working on.
