### ISSUE TITLE
Creating API token does not work

### ISSUE THREAD

**Issue by rdnixon** [grokability/snipe-it#15365]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When we go to create an API key it comes up with 404 Not found - The resource requested could not be found on this server! 
On the help it suggest running a php command - but this does not generate a valid API key - it makes a string - but a very short one. The hosting company, Kualo did take a look (fresh install using their quick install) and found this int he logs:
[22/Aug/2024:02:38:38 +0000] "POST /livewire/update HTTP/1.1" 404 708 "https://rltinventory.co.uk/public/account/api" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/2 0100101 Firefox/129.0" [22/Aug/2024:02:38:39 +0000] "POST /livewire/update HTTP/1.1" 404 708 "https://rltinventory.co.uk/public/account/api" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/2 0100101 Firefox/129.0"

### Reproduction steps

1. Select Manage API keys
2. Create Key
3. 404 is presented
...

### Expected behavior

An API key is generated

### Screenshots

![Screenshot 2024-08-22 090603](https://github.com/user-attachments/assets/c93e1721-86d7-4029-a269-f72b2c2577c2)

### Snipe-IT Version

7.0.11

### Operating System

Kualo hosting - Linux angelo.ldn.kualo.net 4.18.0-513.11.1.lve.el8.x86_64 #1 SMP Thu Jan 18 16:21:02 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Web Server

Apache I think

### PHP Version

8.1.29

### Operating System

Windows

### Browser

Chrome

### Version

127.0.6533.120

### Error messages

```shell
404 error trying to make an api key. Cannot reproduce on the demo as its turned off. Not really sure which bit of the debug screen to provide. Nothing in the bit that says logs. The livewire but gives personal-access-tokens #1sW9LUoTbMfTGS1pO028
array:4 [ "data" => array:2 [ "name" => null "newTokenString" => null ] "name" => "per...
```

### Additional context

Fresh install on Kualo hosting installed via their one click install. Everything else works fine - but do need API access to work. Any ideas would be welcome. They said post here as they did not know!

**Comment by snipe** [comment]
Per the docs, you should never have `public` in your URL (I do see that you've at least set up redirects, but the document root should be set to public so that you don't need `public` in your URL.) When you have `public` in your URL, the app thinks you're running this in a subdirectory, so you need to add the livewire prefix. https://snipe-it.readme.io/docs/subdirectories#add-the-livewire-config-variable

<blockquote><img src="https://files.readme.io/e9d890e-small-standalone-transparent-400.png" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/subdirectories#add-the-livewire-config-variable">Subdirectories</a></strong></div><div>Snipe-IT really wants to be run as a subdomain or on its own domain name. If you wish to run Snipe-IT in a subdirectory ( https://yourserver.com/snipe-it ) instead of at a primary domain ( http://yourserver.com ) or a sub-domain ( https://snipe-it.yourserver.com ), you'll need to go through the stan...</div></blockquote>

**Comment by rdnixon** [comment]
Many thanks for getting back to me. To be honest - Kualo just step this up - not me. I did wonder about the public bit in the url they popped in. I'll feed this back to them and have a go at what it says in that doc.

**Comment by snipe** [comment]
I don't know who or what Kualo is 😂 But at least they seem to have covered the security basics, i.e. your `.env` file isn't exposed to the outside world, and it's redirecting if I try to access one level up, so that's good. That liveware prefix (until/unless you change the URL so that `public` isn't in there anymore) would be `/public`.

**Comment by rdnixon** [comment]
They are a hosting company that does one click installs. I'll talk to them and see what they say.

**Comment by snipe** [comment]
Ahh, they're probably using Softaculous. That's the "packaging up open source projects and make them one-click" company, usually done via cPanel integration. Unfortunately,  Softaculous doesn't share their process with us, so we don't really know what their installer thingie does (or doesn't do.)

**Comment by rdnixon** [comment]
I have tried changing LIVEWIRE_URL_PREFIX=/public

Making an API key gives the same error. Maybe there is some other issue as well.

**Comment by rdnixon** [comment]
Think they have sorted it out. The public bit is gone and API is working grand now. Many thanks for pointed us and them in the right direction. Think its going to be great for our schools.

**Comment by snipe** [comment]
@rdnixon Great, glad to hear you're sorted!
