### ISSUE TITLE
[7.0.11] Wrong character encoding when restoring backup via SnipeIT GUI

### ISSUE THREAD

**Issue by swift2512** [grokability/snipe-it#15449]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When restoring backup (generated in 'Admin > Backups', lithuanian letters are encoded incorrectly. Instead of ĄČĘĖĮŠŲŪŽ i get something like Ä„ÄŒÄ˜Ä–Ä®Å Å²ÅªÅ½
![image](https://github.com/user-attachments/assets/9d024023-d6fc-40d7-81ca-23221295e6a4)
This doesn't happen when restoring same backup file through SSH (php artisan snipeit:restore /var/www/snipeit/storage/app/backups/snipe-it-2024-08-26-15-42-46.zip)
Can't figure out what's wrong. Tried Edge and Firefox browsers for backup restore - same result.

### Reproduction steps

1. Use Lithuanian characters (ĄČĘĖĮŠŲŪ) in names or other fields 
2. Generate backup.
3. Restore backup in Admin > Backups

### Expected behavior

Characters encoded correctly.

### Screenshots

![image](https://github.com/user-attachments/assets/f312bad1-2b04-4dab-a3f6-bc0ed831fb8e)
![image](https://github.com/user-attachments/assets/9d352afd-d9c8-4a53-a1ff-9f8c67c2d204)
![image](https://github.com/user-attachments/assets/22e7d7b4-1453-477b-ad0b-345470dced54)

### Snipe-IT Version

Version v7.0.11 - build 15044 (master)

### Operating System

ubuntu

### Web Server

apache

### PHP Version

8.3

### Operating System

Windows 11

### Browser

Edge, Firefox

### Version

Latest

### Error messages

```shell
No errors in log files with debug enabled.
```

### Additional context

No

**Comment by snipe** [comment]
Well what makes less sense there is that the GUI tool just calls the cli tool, so it doesn't really have opinions about encoding.

**Comment by snipe** [comment]
When you do the gui restore, do you see any options (checkboxes)? We recently added a “clean” option where we do some regexes which could potentially be mangling the Unicode.

**Comment by swift2512** [comment]
Yes, there's this checkbox for database cleaning. I checked that.

**Comment by swift2512** [comment]
Leaving this unchecked restores backup with correct characters. If checked- garbage characters everywhere.
![image](https://github.com/user-attachments/assets/f173dfce-b6cc-4d42-8b7f-c5fb0be09eea)

**Comment by BartFridayski** [comment]
I have exactly the same problem. In my case it is a problem with Polish letters 
but now when I add new records containing Polish characters it is OK.
The problem is only with the imported data. 

I assume there is a problem with the export, then the encoding is lost.

**Comment by swift2512** [comment]
> I have exactly the same problem. In my case it is a problem with Polish letters but now when I add new records containing Polish characters it is OK. The problem is only with the imported data.
> 
> I assume there is a problem with the export, then the encoding is lost.

Exported backup is ok, it has correct encoding information and characters. Backup restore only fails when "Clean backed-up database before restore' is checked. Then this is unchecked or restore through ssh is done, are letters are correct. 

While dbdumb file is using utf8 format, looks like 
data parser uses ANSI when reading this file and then forwards these wrongly decoded characters to the database.

**Comment by snipe** [comment]
You generally don't need to clean the database unless you've uploaded it from somewhere else. What we were finding is that restores would break, if for example you were running as a mysql user with special grants on one server, but the new server doesn't have those grants. The process would basically be that the tables get dropped and then the import fails because the mysql user on the current system didn't have enough rights granted (or sometimes there were settings included in the export from one machine that the new machine can't handle.)

Thanks for helping us pin this down, @swift2512 - we'll get it sorted shortly.

**Comment by uberbrady** [comment]
I think this is addressed with the PR mentioned above - #15960 .

According to @snipe that's now on 'master' - so if you pull that down you should find that the 'cleaning mode' should (hopefully) stop mangling international characters.

Please let us know if the new version works any better for you. Thank you!

**Comment by swift2512** [comment]
Tried this morning on latest pull (v7.1.15 - build 16052 (master). Everything looks good. :+1:

**Comment by marcinBB8** [comment]
today I made restore on new docker instance ( v8.1.4 - build 18245) with  cleaning option and have problem with polish characters.

Backup was made from Ubuntu VM old instance (don't remember Snipe version but newest at January 2025).

**Comment by snipe** [comment]
@marcinBB8 Hi there - this issue is closed. Please create a new issue with steps to reproduce. (When you reply to old, closed threads, it sends an email notification to everyone who ever participated in it, which can be pretty annoying to have happen on a thread that's been resolved for a while.)

**Comment by marcinBB8** [comment]
@snipe  I will try to remember for the future, but in these case it looks like issue  "is back" and in my opinion rewriting everything (clone issue) is more annoying, than mail notification, that no more interested can switch of. 
And info from old can be more useful for devs to locate problem ;)

edit: in addition, without "cleaning option" it restore correctly but have no idea how it impact for future, because backup was created on deferent configuration (before ubuntu VM-naw docker, different Snipe version etc.)

**Comment by snipe** [comment]
Yeah, but spamming everyone who commented on a thing can be kind of inconsiderate. 

Usually a good rule of thumb is to link back to the older issue with your new scenario, that way we have the best of both worlds. (Also older issues that are closed and then commented on can often go unseen, since to us, they're "done" and we don't check closed issues very often. 

No harm done, just something to keep in mind :)
