### ISSUE TITLE
[Feature Request]: Postgres Support?

### ISSUE THREAD

**Issue by Chris53897** [grokability/snipe-it#15554]
### Is your feature request related to a problem? Please describe.

The docs state that postgres is not supported. https://snipe-it.readme.io/docs/requirements

But there are some tests. So i have a little hope that it could maybe work.
https://github.com/snipe/snipe-it/blob/refs/heads/master/.github/workflows/tests-postgres.yml

Are the docs maybe outdated? Or is Postgres not supported?

### Describe the solution you'd like

see above

**Comment by uberbrady** [comment]
Well, we _try_ to maintain compatibility with Postgres, but don't "formally" support it. We have that test to try and keep that compatibility. If you find problems with our Postgres implementation, we _will_ try to fix it if we can. If you look back at our previous PR's and issues, you can see a few examples of us reworking something that was MySQL-specific into something that can work with more databases. We run a lot of tests with sqlite, which is a different engine, so that does help keep us honest.

**Comment by Chris53897** [comment]
Thanks for the fast response.
We will try it and post results here.

**Comment by Chris53897** [comment]
We decided to take the save way and use MariaDB for now.
