### ISSUE TITLE
[Feature Request]: Check out one asset to multiple users 

### ISSUE THREAD

**Issue by Rayyyy0** [grokability/snipe-it#15678]
### Is your feature request related to a problem? Please describe.

in a 24/7 support centers we have 1 PC but 4 employs use it because they do 4 shifts 

Timmy from 6am to 12pm 

jimmy from 12pm to 6pm

Kimmy from 6pm to 12am

Dimmy from 12am to 6am

can you please add the option to do a multi user check out ( same asset for multiple users ) for this scenario 

if you are not planning to do it is there a play around or a trick to do it 

### Describe the solution you'd like

Can you do something like a link or virtual assets mirror anything so when i view any of those users i will see the assets the have and use

**Comment by snipe** [comment]
That's not currently on the short-term roadmap. This system isn't really intended for that kind of hourly scheduling.

**Comment by swift2512** [comment]
What sort of shady business you have? :D

Add your items as Assets to Snipe-IT and assign these assets to the LOCATION where those 4 work.

**Comment by Rayyyy0** [comment]
@swift2512 
>24/7 support center
>They have the assets checked out to one of the employees currently but 4 employees are using them 
I don't mind it personally but they want to know what equipment each employ is using there bc now on the assets system a lot of employees have empty profiles when they are actually using assets

**Comment by swift2512** [comment]
Shared equipment (table, chair, computer, etc.) is assigned to the location. Employees should have their own earpiece/earphones due to hygienic reasons. That's standard for all developed countries.  What you want is not standard and makes little sense because, usually, receiver has to sign for item he receives. If there's no signature/acceptance, receiver can't be hold liable for it.
That's why your autorotation of assets between set users over set time doesn't make any sense- it won't be signed.

Make your equipment as an accessory, set quantity to 4, disable acceptance and assign a piece to each user. This way you will see who shares which item.

**Comment by sweetins** [comment]
I believe one of the reasons an asset is checked out to a user is to be able to hold them accountable. If they are running shift, then permissions should be set such that each user can check that particular asset out to himself when shift starts and back in when shift ends. That way each user could be held accountable.
