### ISSUE TITLE
[Feature Request]: LDAP sync from different OU's in Active Directory

### ISSUE THREAD

**Issue by bfry2461** [grokability/snipe-it#15778]
### Is your feature request related to a problem? Please describe.

We have different OU's for various locations we have employee's.  If I sync from the top level of the AD domain, it sync's everything.  I have created 3 locations where I have users and put those specific OU's in the Location tab for each.  How does this sync work if I automated the updates?

### Describe the solution you'd like

To be able to sync from different OU's in Active Directory

### Describe alternatives you've considered

None

**Comment by snipe** [comment]
You can pass the location via cli: https://snipe-it.readme.io/docs/ldap-sync

<blockquote><img src="https://files.readme.io/e9d890e-small-standalone-transparent-400.png" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/ldap-sync">LDAP Sync</a></strong></div><div>❗️ Large LDAP Directories: In your .env file, you may need to modify the LDAP_MEM_LIM (expressed as '500M' for 500MB) and/or the LDAP_TIME_LIM (expressed in seconds) in order to avoid a large LDAP sync from timing out or exhausting all memory. The default time limit is 10 minutes. The default memory...</div></blockquote>
