### ISSUE TITLE
Asset checkin/out emails not being sent

### ISSUE THREAD

**Issue by divEruner** [grokability/snipe-it#15813]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

The test email sending function works fine. However, the checkin and checkout emails are not being sent.
I have checked the settings of the asset categories and the option to send email, EULA, and asset accettance are configured properly.
The user's email addresses are set correctly too. 

### Reproduction steps

1. Checked the email settings in the categories
2.Checked the functioning of the emails via the test function
3.Tried the debug mode but cannot find any errors 
...

### Expected behavior

Email being sent on checkin/checkout of an asset

### Snipe-IT Version

7.1.14 build 15942

### Operating System

Docker

### Web Server

Apache

### PHP Version

8.1.2

**Comment by JoshJames04** [comment]
I can second to having this issue.

**Comment by snipe** [comment]
I'm not able to reproduce this. @Godmartinz @marcusmoore - can you?

**Comment by Toby737** [comment]
Email notifications on asset check in / check out seems to be working fine for me.
Shows the To: as the person who it's checked out to and CC: as the email set in the CC Email in Notification Settings in Snipe-IT.

Version v7.1.14 - build 15942 (master)

**Comment by Godmartinz** [comment]
Hmm, I am unable to reproduce as well. 🤔

**Comment by marcusmoore** [comment]
@divEruner can you post a screenshot of the edit category screen for the item you are checking out?

**Comment by divEruner** [comment]
Sure, here it is

![category_settings](https://github.com/user-attachments/assets/6374a883-57c2-4030-a346-9751016a8d63)

**Comment by LegendEronZ** [comment]
Experiencing the same thing in docker setup, please let me know if you need any info

**Comment by FernandoDultra** [comment]
I have the same Problem, but my debug show me this warning:

`production.WARNING: Exception caught during checkin notification: Expected response code "250" but got code "554", with message "554 5.2.252 SendAsDenied; myusername@xxx.com not allowed to send as service@snipe-it.io; STOREDRV.Submission.Exception:SendAsDeniedException.MapiExceptionSendAsDenied; Failed to process message due to a permanent exception with message [BeginDiagnosticData]Cannot submit message. 1.84300:01000000, 1.84300:0B000000, 1.84300:0A000000, 1.84300:0A000000, 1.84300:0E000000, 1.84300:32000000, 0.117068:15000000, 1.79180:0B000000, 1.79180:0A000000, 1.79180:0A000000, 1.79180:0E000000, 1.79180:32000000, 1.79180:FA000000, 0.73100:4F4D0000, 5.95292:670000003130330055736572, 8.111356:8F5F19C9441AE441A6536B31ED2F214BA6536B31, 0.38698:AB037096, 1.41134:87000000, 1.41134:87000000, 1.41134:87000000, 1.41134:47000000, 0.37692:01000000, 0.37948:7C000100, 5.33852:00000000534D545000000000, 7.36354:010000000000010900000000, 4.56248:DC040000, 7.40748:010000000000010B00000000, 7.57132:000000000000000000000000, 4.39640:DC040000, 1.63016:32000000, 8.45434:91B3B290173F124D8F107E245A70CC1400000000, 1.46798:04000000, 5.10786:0000000031352E32302E383135382E3031333A53435A503231354D42323839343A33663265613039642D653461622D343030392D616266622D3334366238656563356230633A3236303635363A2E4E455420382E302E313000000000, 7.51330:400415B2FF06DD0800000000, 0.39570:00000000, 1.55954:0B000000, 0.40818:09000000, 1.33010:0B000000, 2.54258:00000000, 0.59634:07000000, 1.56562:00000000, 1.33010:0B000000, 2.54258:00000000, 0.59634:22000000, 1.56562:00000000, 1.55954:0A000000, 1.33010:0A000000, 2.54258:00000000, 0.40002:00000000, 1.56562:00000000, 1.33010:0A000000, 2.54258:00000000, 0.40002:00000000, 1.56562:00000000, 1.55954:0A000000, 1.33010:0A000000, 2.54258:00000000, 0.40002:22000000, 1.56562:00000000, 1.33010:0A000000, 2.54258:00000000, 0.40002:22000000, 1.56562:00000000, 1.64146:0E000000, 1.33010:0E000000, 2.54258:00000000, 1.33010:0E000000, 2.54258:00000000, 1.64146:32000000, 1.33010:32000000, 2.54258:DC040000, 1.33010:32000000, 2.54258:DC040000, 0.79500:00000000, 0.100684:00000000, 0.66700:00000000, 5.95292:670000003130330055736572, 8.111356:8F5F19C9441AE441A6536B31ED2F214BA6536B31, 0.38698:AB037096, 1.41134:87000000, 1.41134:87000000, 1.41134:87000000, 1.41134:47000000, 0.37692:01000000, 0.37948:7C000100, 5.33852:00000000534D545000000000, 7.36354:010000000000010900000000, 4.56248:DC040000, 7.40748:010000000000010B00000000, 7.57132:000000000000000000000000, 4.39640:DC040000, 1.63016:32000000, 8.45434:91B3B290173F124D8F107E245A70CC1400000000, 1.46798:04000000, 5.10786:0000000031352E32302E383135382E3031333A53435A503231354D42323839343A33663265613039642D653461622D343030392D616266622D3334366238656563356230633A3236303635363A2E4E455420382E302E313000000000, 7.51330:400415B2FF06DD0800000000, 0.39570:00000000, 1.55954:0B000000, 0.40818:09000000, 1.33010:0B000000, 2.54258:00000000, 0.59634:07000000, 1.56562:00000000, 1.33010:0B000000, 2.54258:00000000, 0.59634:22000000, 1.56562:00000000, 1.55954:0A000000, 1.33010:0A000000, 2.54258:00000000, 0.40002:00000000, 1.56562:00000000, 1.33010:0A000000, 2.54258:00000000, 0.40002:00000000, 1.56562:00000000, 1.55954:0A000000, 1.33010:0A000000, 2.54258:00000000, 0.40002:22000000, 1.56562:00000000, 1.33010:0A000000, 2.54258:00000000, 0.40002:22000000, 1.56562:00000000, 1.64146:0E000000, 1.33010:0E000000, 2.54258:00000000, 1.33010:0E000000, 2.54258:00000000, 1.64146:32000000, 1.33010:32000000, 2.54258:DC040000, 1.33010:32000000, 2.54258:DC040000, 0.97900:00000000, 4.120460:DC040000, 1.52466:02000000, 1.52466:02000000, 1.42738:09000000, 0.37698:07000000, 0.37698:02000000, 1.42738:09000000, 0.37698:77000000, 0.37698:02000000, 1.52466:01000000, 0.60402:02000000, 1.52466:01000000[EndDiagnosticData] [Hostname=SCZP215MB2894.LAMP215.PROD.OUTLOOK.COM]".`

**Comment by LegendEronZ** [comment]
Hi,

Based on what Fernando said I have added MAIL_FROM_ADDR env var and now it is working again.

Before, MAIL_ENV_FROM_ADDR was enough for the setup did something change?

**Comment by divEruner** [comment]
I can confirm what Eron wrote, I added the string MAIL_FROM_ADDR and it is now working properly again

**Comment by FernandoDultra** [comment]
I solved my problem by adjusting the php file below. Changing the snipe it service address in the file "service@snipe-it.io" to my department's email address.

nano /var/www/html/snipeit/app/Mail/CheckoutAssetMail.php


> I have the same Problem, but my debug show me this warning:
> 
> `production.WARNING: Exception caught during checkin notification: Expected response code "250" but got code "554", with message "554 5.2.252 SendAsDenied; myusername@xxx.com not allowed to send as service@snipe-it.io; STOREDRV.Submission.Exception:SendAsDeniedException.MapiExceptionSendAsDenied; Failed to process message due to a permanent exception with message [BeginDiagnosticData]Cannot submit message. 1.84300:01000000, 1.84300:0B000000, 1.84300:0A000000, 1.84300:0A000000, 1.84300:0E000000, 1.84300:32000000, 0.117068:15000000, 1.79180:0B000000, 1.79180:0A000000, 1.79180:0A000000, 1.79180:0E000000, 1.79180:32000000, 1.79180:FA000000, 0.73100:4F4D0000, 5.95292:670000003130330055736572, 8.111356:8F5F19C9441AE441A6536B31ED2F214BA6536B31, 0.38698:AB037096, 1.41134:87000000, 1.41134:87000000, 1.41134:87000000, 1.41134:47000000, 0.37692:01000000, 0.37948:7C000100, 5.33852:00000000534D545000000000, 7.36354:010000000000010900000000, 4.56248:DC040000, 7.40748:010000000000010B00000000, 7.57132:000000000000000000000000, 4.39640:DC040000, 1.63016:32000000, 8.45434:91B3B290173F124D8F107E245A70CC1400000000, 1.46798:04000000, 5.10786:0000000031352E32302E383135382E3031333A53435A503231354D42323839343A33663265613039642D653461622D343030392D616266622D3334366238656563356230633A3236303635363A2E4E455420382E302E313000000000, 7.51330:400415B2FF06DD0800000000, 0.39570:00000000, 1.55954:0B000000, 0.40818:09000000, 1.33010:0B000000, 2.54258:00000000, 0.59634:07000000, 1.56562:00000000, 1.33010:0B000000, 2.54258:00000000, 0.59634:22000000, 1.56562:00000000, 1.55954:0A000000, 1.33010:0A000000, 2.54258:00000000, 0.40002:00000000, 1.56562:00000000, 1.33010:0A000000, 2.54258:00000000, 0.40002:00000000, 1.56562:00000000, 1.55954:0A000000, 1.33010:0A000000, 2.54258:00000000, 0.40002:22000000, 1.56562:00000000, 1.33010:0A000000, 2.54258:00000000, 0.40002:22000000, 1.56562:00000000, 1.64146:0E000000, 1.33010:0E000000, 2.54258:00000000, 1.33010:0E000000, 2.54258:00000000, 1.64146:32000000, 1.33010:32000000, 2.54258:DC040000, 1.33010:32000000, 2.54258:DC040000, 0.79500:00000000, 0.100684:00000000, 0.66700:00000000, 5.95292:670000003130330055736572, 8.111356:8F5F19C9441AE441A6536B31ED2F214BA6536B31, 0.38698:AB037096, 1.41134:87000000, 1.41134:87000000, 1.41134:87000000, 1.41134:47000000, 0.37692:01000000, 0.37948:7C000100, 5.33852:00000000534D545000000000, 7.36354:010000000000010900000000, 4.56248:DC040000, 7.40748:010000000000010B00000000, 7.57132:000000000000000000000000, 4.39640:DC040000, 1.63016:32000000, 8.45434:91B3B290173F124D8F107E245A70CC1400000000, 1.46798:04000000, 5.10786:0000000031352E32302E383135382E3031333A53435A503231354D42323839343A33663265613039642D653461622D343030392D616266622D3334366238656563356230633A3236303635363A2E4E455420382E302E313000000000, 7.51330:400415B2FF06DD0800000000, 0.39570:00000000, 1.55954:0B000000, 0.40818:09000000, 1.33010:0B000000, 2.54258:00000000, 0.59634:07000000, 1.56562:00000000, 1.33010:0B000000, 2.54258:00000000, 0.59634:22000000, 1.56562:00000000, 1.55954:0A000000, 1.33010:0A000000, 2.54258:00000000, 0.40002:00000000, 1.56562:00000000, 1.33010:0A000000, 2.54258:00000000, 0.40002:00000000, 1.56562:00000000, 1.55954:0A000000, 1.33010:0A000000, 2.54258:00000000, 0.40002:22000000, 1.56562:00000000, 1.33010:0A000000, 2.54258:00000000, 0.40002:22000000, 1.56562:00000000, 1.64146:0E000000, 1.33010:0E000000, 2.54258:00000000, 1.33010:0E000000, 2.54258:00000000, 1.64146:32000000, 1.33010:32000000, 2.54258:DC040000, 1.33010:32000000, 2.54258:DC040000, 0.97900:00000000, 4.120460:DC040000, 1.52466:02000000, 1.52466:02000000, 1.42738:09000000, 0.37698:07000000, 0.37698:02000000, 1.42738:09000000, 0.37698:77000000, 0.37698:02000000, 1.52466:01000000, 0.60402:02000000, 1.52466:01000000[EndDiagnosticData] [Hostname=SCZP215MB2894.LAMP215.PROD.OUTLOOK.COM]".`

**Comment by al-dubois** [comment]
I have the same bug. Snipe-It seems to be ignoring my .env file and defaulting to the value specified in /var/www/html/snipeit/app/Mail/CheckoutAssetMail.php as mentionned by @FernandoDultra 

Here's my redacted config:


 REQUIRED: OUTGOING MAIL SERVER SETTINGS

MAIL_DRIVER=smtp
MAIL_HOST=mail.smtp2go.com
MAIL_PORT=587
MAIL_USERNAME=[REDACTED]
MAIL_PASSWORD=[REDACTED]
MAIL_FROM_ADDR=snipeit@MYDOMAIN.com
MAIL_FROM_NAME='Snipe-IT'
MAIL_REPLYTO_ADDR=snipe-it@MYDOMAIN.com
MAIL_REPLYTO_NAME='Snipe-IT'
MAIL_AUTO_EMBED_METHOD='attachment'

On my SMTP provider (SMTP2GO), I can see the e-mail is rejected because the sender is service@snipe-it.io
![image](https://github.com/user-attachments/assets/24fcdbf9-0748-4c1d-ba8e-8094fe8bc0b6)

Did something change in release v7.1.14 ? It worked fine in v7.0.13

**Comment by marcusmoore** [comment]
There was a bug introduced in v7.1.14 that is being fixed in #15839. Manually adding a `MAIL_FROM_ADDR` value to your `.env` file should fix it in the mean time.

**Comment by marcusmoore** [comment]
Ah I spoke too soon. I see manually changing the file is the actual fix which is _not_ ideal. Do that if it works for you now and the actual fix should be included soon.

**Comment by Godmartinz** [comment]
<img width="639" alt="image" src="https://github.com/user-attachments/assets/422c1bd4-348e-4c7f-a809-41179e417d7b">
changing the second param to the alternate config variable instead of the service@snipe.it.io should correct this, no?

**Comment by al-dubois** [comment]
In my case,  version v7.1.15 fixed the issue.
