### ISSUE TITLE
[Feature Request]: Add User-Based Search in Asset Search Function

### ISSUE THREAD

**Issue by Kanishka-Deshan** [grokability/snipe-it#15865]
### Is your feature request related to a problem? Please describe.

The current asset search functionality in Snipe-IT allows users to search by asset tag only. However, there are scenarios where searching by user or employee ID would greatly enhance productivity. For example, if we need to quickly find all assets assigned to a specific user or an employee identified by their employee number, there is no direct way to do this. This limitation makes managing and auditing assets more time-consuming.

![image](https://github.com/user-attachments/assets/4c971776-7e45-4a7c-a60d-e609ad320019)

### Describe the solution you'd like

I would like to have an option added to the asset search functionality that allows searching by user or employee number in addition to the asset tag. When a user inputs an employee number, the system should return all assets assigned to that user, such as laptops, monitors, or other hardware. This feature should integrate seamlessly with the current search bar in the top navigation.

### Describe alternatives you've considered

An alternative could be creating a dedicated "Search by User" function in the user management section, but that would involve navigating to a separate page and add extra steps to the workflow. Another option would be to build a custom report, but this requires significant manual effort and is not as intuitive or efficient as enhancing the existing search functionality.

### Additional context

Adding this feature would help organizations streamline asset tracking, improve inventory management efficiency, and reduce the time spent on audits. It is particularly useful for IT teams managing large-scale deployments where employees frequently transfer assets or roles. This feature can leverage existing user-asset relationships in the database, making it relatively simple to implement.

**Comment by FlorentDotMe** [comment]
Hi @Kanish-d. What you describe has already been implemented since release v7.0.11 (https://github.com/snipe/snipe-it/releases/tag/v7.0.11), if I'm not mistaken.

<blockquote><img src="https://opengraph.githubassets.com/f27d57ca615bc80e8bea169ee575e3daeaff417b78b3d7ba8b3d1d7b9730945f/snipe/snipe-it/releases/tag/v7.0.11" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="/snipe/snipe-it/releases/tag/v7.0.11">Release v7.0.11 · snipe/snipe-it</a></strong></div><div>CautionSnipe-IT now requires PHP 8.1.2 or greater

Happy Thursday everyone! This release comes with a bunch of small UX/UI improvements, and a few additional features, including the ability to opti...</div></blockquote>
