### ISSUE TITLE
what is right way to create my own module \ my own custom asset ? 

### ISSUE THREAD

**Issue by do-d1** [grokability/snipe-it#7664]
i need to manage cell phone lines and sim cards 
i need fildes like ,ISP, CCID, creation \ termination date , package cost , package valid till , minutes included , data included and so on ..

the best way in my opinion is to be able to create one more line in the menu called sim cards and it will be a custom assets with my own custom fields.

any idea or pointer to some how to will be appreciated , thank you .

**Comment by Jarli01** [comment]
You'd want to create a custom model, and once that model is created you'd create a custom fieldset and apply that fieldset to your model.

**Comment by samotelf** [comment]
Hey @do-d1.
Actually somebody asked me the same on reddit and you can follow this quick and dirty how to:

Yes. Go to Settings -> Custom Fields. Then, new custom field.

For instance, IMEI, choose field name, Text Box, Format Numeric. Then in the same page, create new fieldset (SIM), edit it and add the IMEI custom field. Do the same for pin, puk, provider, so on and so on. It takes a few minutes to configure it to your environment, but after that everything works.


[Take a look](https://paste.pics/7J0JU)

Anything else, hit me up since I have this working in my org.

**Comment by do-d1** [comment]
thank you 
first i was trying to do it as new category ..
now i see the right way to do it is with the asset models
