### ISSUE TITLE
Filter assets based on departments 

### ISSUE THREAD

**Issue by snehamanukonda** [grokability/snipe-it#7670]
can any one help me to filter the assets based on the departments.
Now, I can able filter based on the companies through Full Multiple Companies Support in admin section.

Snipe-IT version | v4.7.7
PHP Version | 7.3.9
Installed on Windows 10

**Comment by pbrink231** [comment]
I think it would be great to add Department field to an asset.

This is the managing department.  We have several assets and would be great to filter by department that manages that asset.

Since departments already exist I believe it would be an easy change to add the relation field for this.  Hopefully I can make a pull request soon for it.

**Comment by pbrink231** [comment]
Linking related issues that I found to this
- #7359 - This is a small part of this open issue  
- #7672 - Similar to 7359 request.  This would be a small portion of that
- #7662 - This is exactly the same issue as
