### ISSUE TITLE
Will the changes in the back-end accept while updating snipe-it latest version ???

### ISSUE THREAD

**Issue by snehamanukonda** [grokability/snipe-it#7671]
If i mad any changes in the database (i.e., adding a new field in a table). will it accept while updating the snipe-it to latest version ??

Snipe-IT version | v4.7.7
PHP Version | 7.3.9
Installed on Windows 10

**Comment by snipe** [comment]
That really depends, but most likely you'd run into issues, which is why [we strongly recommend against it](https://snipe-it.readme.io/docs/manually-editing-data). Adding fields without the appropriate changes to the code is bound to lead to problems. 

Your best bet would be to create a test instance off of your existing install and try the upgrade.
