### ISSUE TITLE
Multiple drop-down fields showing "The results could not be loaded".

### ISSUE THREAD

**Issue by dm-andreas** [grokability/snipe-it#7720]
#### Please confirm you have done the following before posting your bug report:

- [ Yes ] I have enabled debug mode 
- [ Yes ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When checking out equipment to users, the drop down list with users or locations will show up with "The results could not be loaded".

**To Reproduce**
1. Go to 'Requested assets'
2. Click on 'Check out'
3. Click 'User'
4. Click the drop down, to select a user.
5. See error

**Expected behavior**
the drop down list should populate with all my users matching my input.

**Screenshots**
![image](https://user-images.githubusercontent.com/59877925/72353467-6a2d0480-36e4-11ea-8370-cded94980624.png)

**Server (please complete the following information):**
 - Snipe-IT Version 4.8.0 - build 4186 (master)
 - OS: Ubuntu 18.04.3 LTS (Bionic Beaver)
 - Web Server: Apache 2.4.29
 - PHP Version PHP 7.2.24

**Desktop (please complete the following information):**
 - OS: Windows 10 1903
 - Browser Firefox, Edge
 - Version 73.0b4 (64-bit), -

**Error Messages**
```
/var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php#179
Symfony\Component\HttpKernel\Exception\NotFoundHttpException
```

![image](https://user-images.githubusercontent.com/59877925/72354176-91d09c80-36e5-11ea-8272-32b5b354626e.png)

- Error included from debug-mode
- No stacktrace was generated.

Error from console in chrome:
```
all.js?id=bf1b244d8cc9096e4a18:3 GET http://assets.dentalmedia.local/hardware/193/undefinedapi/v1/users/selectlist?page=1 404 (Not Found)
send @ all.js?id=bf1b244d8cc9096e4a18:3
ajax @ all.js?id=bf1b244d8cc9096e4a18:3
transport @ all.js?id=bf1b244d8cc9096e4a18:20
n @ all.js?id=bf1b244d8cc9096e4a18:20
n.query @ all.js?id=bf1b244d8cc9096e4a18:20
(anonymous) @ all.js?id=bf1b244d8cc9096e4a18:21
n.invoke @ all.js?id=bf1b244d8cc9096e4a18:19
n.trigger @ all.js?id=bf1b244d8cc9096e4a18:19
s.trigger @ all.js?id=bf1b244d8cc9096e4a18:21
s.open @ all.js?id=bf1b244d8cc9096e4a18:21
s.toggleDropdown @ all.js?id=bf1b244d8cc9096e4a18:21
(anonymous) @ all.js?id=bf1b244d8cc9096e4a18:21
n.invoke @ all.js?id=bf1b244d8cc9096e4a18:19
n.trigger @ all.js?id=bf1b244d8cc9096e4a18:19
(anonymous) @ all.js?id=bf1b244d8cc9096e4a18:19
dispatch @ all.js?id=bf1b244d8cc9096e4a18:2
m.handle @ all.js?id=bf1b244d8cc9096e4a18:2
all.js?id=bf1b244d8cc9096e4a18:3 XHR failed loading: GET "http://assets.dentalmedia.local/hardware/193/undefinedapi/v1/users/selectlist?page=1".
send @ all.js?id=bf1b244d8cc9096e4a18:3
ajax @ all.js?id=bf1b244d8cc9096e4a18:3
transport @ all.js?id=bf1b244d8cc9096e4a18:20
n @ all.js?id=bf1b244d8cc9096e4a18:20
n.query @ all.js?id=bf1b244d8cc9096e4a18:20
(anonymous) @ all.js?id=bf1b244d8cc9096e4a18:21
n.invoke @ all.js?id=bf1b244d8cc9096e4a18:19
n.trigger @ all.js?id=bf1b244d8cc9096e4a18:19
s.trigger @ all.js?id=bf1b244d8cc9096e4a18:21
s.open @ all.js?id=bf1b244d8cc9096e4a18:21
s.toggleDropdown @ all.js?id=bf1b244d8cc9096e4a18:21
(anonymous) @ all.js?id=bf1b244d8cc9096e4a18:21
n.invoke @ all.js?id=bf1b244d8cc9096e4a18:19
n.trigger @ all.js?id=bf1b244d8cc9096e4a18:19
(anonymous) @ all.js?id=bf1b244d8cc9096e4a18:19
dispatch @ all.js?id=bf1b244d8cc9096e4a18:2
m.handle @ all.js?id=bf1b244d8cc9096e4a18:2
javascript?v=1579005085:2 XHR finished loading: GET "http://assets.dentalmedia.local/_debugbar/open?op=get&id=X6622c84fb022d3942622ed94cc4d5c4c".
```
Laravel log is empty.
Demo page does not reproduce the bug.

**Additional context**
- Is this a fresh install or an upgrade? 
Manual upgrade from 4.6.5, all files pulled from Git. Running on Ubuntu 18.04.3 LTS, Apache. MySql is not running on same server. 

I Pulled git to a new folder, copied over .env file and storage/oauth-xxx.key files
aditionally, I copied entire public/uploads/ over with rsync to avoid reuploading all asset images.

I ran the following commands successfully:
```
php composer.phar install --no-dev --prefer-source
php composer.phar dump-autoload
php artisan migrate
php artisan config:clear
php artisan config:cache
```

**Comment by dm-andreas** [comment]
This is still very relevant.

**Comment by kitelessd** [comment]
@dm-andreas Are you still seeing this? I have a fresh install on Ubuntu 18.04 LTS using MariaDB and just trying to build a new asset database from scratch. I'm getting this issue. Running build 4352 on hardware. I had a previous install running on Docker that was NOT showing this odd behavior. Since I have time I may just try it on CentOS.

**Comment by dm-andreas** [comment]
@kitelessd I still see this, yes. I have so far have had no luck with trying to fix this myself. Did you have any luck?

**Comment by kitelessd** [comment]
@dm-andreas Sadly no. I tried doing a CentOS install and just could not get the installer to be happy with the PHP package manager. Tried various things to massage it, but no luck. The only time I've got this to work, oddly is in a Docker setup. But I wonder if it may have started doing it at some point. The major difference is the Docker setup is MySQL in it's own container and not MariaDB. I'm going to try a bare metal install again but figure out how to force it to use MySQL instead of Maria. I don't see how Docker would be the thing that's somehow causing it to work. I tried forcing MySQL when I first did the install to metal last week but when I saw that the installer wanted to do Maria I just let it do it and didn't think anything of it. Also I found that restarting Maria from a terminal instantly fixed the pull down menu before it would die again. So yeah, Will do a more manual install along side MySQL and will report back here. It's of course a very repeatable problem. Cheers!

**Comment by juancamedrano21** [comment]
I have done this installation on ubuntu 18.04 more than 3 times and I have the same problem.

**Comment by dm-andreas** [comment]
Still relevant!

**Comment by cfenell** [comment]
Hi, this issue seems to have appeared again after a recent upgrade.
Snipe-IT version
v6.1.1-pre build 10727 (gf1b4bba3a)
PHP Version
8.1.2-1ubuntu2.11
Laravel Version
8.83.22

Steps to reproduce:
1. list assets
2. click Checkout on a deployable asset
3. on Checkout page, select Checkout to User/Asset/Location
4. Dropdown menu User/Asset/Location shows this behaviour.
