### ISSUE TITLE
LDAP with Cloud Hosted Environment

### ISSUE THREAD

**Issue by spetersen-identco** [grokability/snipe-it#7751]
Hello,

I have been trying to make use of the cloud hosted version of Snipe-IT. For the most part it is a fresh instance as all I have done was mess around with importing assests and users.

Before I imported the users I was trying to configure LDAP but was having trouble, even after following the documentation and some videos I found as they appear to be for self-hosted environments.

Is it possible to configure LDAP with the cloud hosted version purchased directly from snipeitapp.com?

**Comment by uberbrady** [comment]
Yes, many customers do use LDAP integration with the cloud-hosted version. Usually the first problem that people have is that they have IP address restrictions on their LDAP server that require addresses to be explicitly whitelisted in order to grant access. Check out https://snipeitapp.com/support and reach out if you need some guidance.

<blockquote><img src="https://snipeitapp.com/img/desktop_snipe.png" width="48" align="right"><div><strong><a href="https://snipeitapp.com/support">Support - Snipe-IT Open Source IT Asset Management</a></strong></div><div>Learn how to get support with Snipe-IT through our open source community, or upgrade to a pro support account for access to the creators of Snipe-IT.</div></blockquote>

**Comment by spetersen-identco** [comment]
Hello,

You can close the ticket.

I will reach out to support directly using the address you gave me, https://snipeitapp.com/support<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsnipeitapp.com%2Fsupport&data=02%7C01%7Cspetersen%40identco.com%7C9bcf89bb641348c3216308d7a10a6fbf%7C3723f62c3dfb4f31b21b6f9be48bea88%7C0%7C1%7C637154938504169167&sdata=159c4NtOnGdqk2jj2pivNP29o9dR4lnRew2ym8tBxXg%3D&reserved=0>, If I decide to pursue this further.

Thank you.

Scotty


Scotty Petersen
Sr. Technical Support Engineer, Global IT
IDENTCO | Labels for Life
Office: +1 (815) 322-8867
spetersen@identco.com
www.identco.com
Follow us on Linkedin
CONFIDENTIALITY NOTICE: This e-mail message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information or otherwise protected by law. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message.

Please consider the environment before printing this email
