### ISSUE TITLE
Generated barcodes are wrong

### ISSUE THREAD

**Issue by murmelbahn** [grokability/snipe-it#7819]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When I create a 1D Barcode they are generated wrong. Please see the attached image.
I have these problem with all Barcodes C128, C39 etc.

**Expected behavior**
A scanable 1D Barcode

**Screenshots**

![](https://i.ibb.co/4t0kwGM/Label.png)

**Server (please complete the following information):**
 - Snipe-IT Version: 4.8 - Linuxserver.io Docker Image

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome, Firefox & Edge
 - Version Latest

I hope someone can help me with this problem.

**Comment by gilesytheking** [comment]
The barcodes are correct. The issue is that the CSS code that outputs the barcode image on the label is not great. The default styling of the label causes the barcode image to be stretched horizontally and cut off vertically, so it is not readable.

Check this post #7331 - I have already shared a simple method on how to fix the barcode output on the labels.

You will also need to play around with your label settings to get the best fit for your label size - Read this #7416
