### ISSUE TITLE
Can some explain what components is and how to use it?

### ISSUE THREAD

**Issue by klsweat** [grokability/snipe-it#7858]
**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pbrink231** [comment]
components and accessories are very similar.

An accessory is an asset you check out to a user where you care more about quantity than individual items.

A component is an asset that goes with another asset.  This could be a power cable or an internal SSD or anything that fits that setup.  A component has to be assigned to another asset.

You have to figure out what works best for you.  You could make your internal SSDs and asset instead of a component if you want if you are tracking specific ones by serial number.  Because and asset can also be assigned to another asset.

**Comment by wmysummer** [comment]
> components and accessories are very similar.
> 
> An accessory is an asset you check out to a user where you care more about quantity than individual items.
> 
> A component is an asset that goes with another asset. This could be a power cable or an internal SSD or anything that fits that setup. A component has to be assigned to another asset.
> 
> You have to figure out what works best for you. You could make your internal SSDs and asset instead of a component if you want if you are tracking specific ones by serial number. Because and asset can also be assigned to another asset.

If the components or accessories are damaged and need to be checked back for scrap, there seems to be no solution for snipe-it. For example, the status can be set when the asset is checked in
