### ISSUE TITLE
Flaw in setup for noobs need assistance if anyone can help 

### ISSUE THREAD

**Issue by LuanRousseau** [grokability/snipe-it#7904]
so i have followed this to the "T" as im a noob 
firstly mysql setup not included so had to look for a install 
secondly done everything like in the manaul no errors 

so i get Apache running once i go to pre-flight check tell me site in not in public 
 and now is Apache not working any more i can reload again as this is eating my time

**Comment by LuanRousseau** [comment]
https://kifarunix.com/install-snipe-it-on-debian-10-ubuntu-18-04/

<blockquote><img src="https://kifarunix.com/wp-content/uploads/2019/08/snipeit-preflight.png" width="48" align="right"><div><img src="https://kifarunix.com/wp-content/uploads/2019/09/kifarunix-fav.png" height="14"> kifarunix.com</div><div><strong><a href="https://kifarunix.com/install-snipe-it-on-debian-10-ubuntu-18-04/">Install Snipe-IT on Debian 10/Ubuntu 18.04 - kifarunix.com</a></strong></div><div>Welcome to our guide on how to install Snipe-IT on Debian 10/Ubuntu 18.04.</div></blockquote>

**Comment by LuanRousseau** [comment]
can any one assist with this error im a noob here 
D'oh. If you're seeing this, your DocumentRoot is set incorrectly. It should be set to the public directory.

**Comment by thesupporthero** [comment]
Honestly, unless you need to otherwise, I would use the docker method.
That setup is far easier for noobs. 
The setup process is here: https://snipe-it.readme.io/docs/docker
If you are just starting from scratch(aka no importing of an old setup) you can be up and running in about 15 minutes.

Let me know if that helps♥

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/docker">Docker</a></strong></div><div>Docker is a very popular software containerization platform. While it's not difficult to use, it can be a little confusing for folks who are less familiar with containerization.  We'll attempt to walk you through a Docker setup here, but please see the Docker documentation for a more in-depth unders...</div></blockquote>
