### ISSUE TITLE
I Need help for New Installation 

### ISSUE THREAD

**Issue by puneetgulati02** [grokability/snipe-it#7927]
Dear Team,
My query is how to install new installation of Snipe-it 

Please help with step by step Installation instruction 

Thanks 
Regards
Puneet Gulati

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by EarlRamirez** [comment]
You can try the following linkhttps://snipe-it.readme.io/docs/installation or if you want something that has Snipe-IT installed you can take a look at https://github.com/EarlRamirez/snipeit_isoSent from my Huawei phone-------- Original message --------From: puneetgulati02 <notifications@github.com>Date: Sun, 29 Mar 2020, 14:37To: snipe/snipe-it <snipe-it@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: [snipe/snipe-it] I Need help for New Installation  (#7927)
Dear Team,
My query is how to install new installation of Snipe-it
Please help with step by step Installation instruction
Thanks
Regards
Puneet Gulati
Server (please complete the following information):
Snipe-IT VersionOS: [e.g. Ubuntu, CentOS]Web Server: [e.g. Apache, IIS]PHP Version
Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
Describe the solution you'd like
A clear and concise description of what you want to happen.
Describe alternatives you've considered
A clear and concise description of any alternative solutions or features you've considered.
Additional context
Add any other context or screenshots about the feature request here.
