### ISSUE TITLE
Bulk User Edit - Group Permissions Not Applying

### ISSUE THREAD

**Issue by Joly0** [grokability/snipe-it#7945]
The problem, which is described here "https://github.com/snipe/snipe-it/issues/5558" is still an issue and because the original bug report is closed and i cant reopen it, i made a new one (i hope, that is ok)

**Comment by ColinMcNeil** [comment]
~~Was just looking into this issue today! I think the issue is there's a single line of code being executed on user edit, that is not  being executed on bulk edit/api edit. Here is the line:~~

https://github.com/snipe/snipe-it/blob/893944403e5da1a2ace76f6d48d3f7eaf0ec1889/app/Http/Controllers/UsersController.php#L312


~~Another user in the previous issue [mentioned](https://github.com/snipe/snipe-it/issues/5558#issuecomment-424843877) that filling the permissions before adding the group seems to fix this. All of these factors seem to indicate to me that the above line which fills the permissions array (even if it is null) should be added to not just user edit, but also user bulk edit and user API edit.~~

I'm going to try this out on my fork and see what happens.

Well it looks like I am unable to reproduce this on a new instance using bulk edit, so not sure what's going on.

**Comment by Joly0** [comment]
It just happens, when i Bulk Import users from AD. Those users have (NULL) in the permissions field in the user table.  Thats wrong. The users should have every permission, but set to 0. This should happen automatically, but it doesnt. 

I had to use MariaDB sheduler to execute a task every 30 minutes to check for (NULL) values in the table and change them to the right one


As long as the Permission-Values are (NULL), they dont get inherited by the Group-permissions, so i can add the users to groups with permissions, but thats basically dont work. Only after saving every single user again, after creation, they get the right permissions and then inherit the group permission

As far as i know, thats just a problem with Ldap import

**Comment by Joly0** [comment]
any help?

**Comment by Joly0** [comment]
yes, still important

**Comment by meyerje** [comment]
I find this issue still important as well.

**Comment by Joly0** [comment]
Yes, still a Problem and seems to be even in v5
