### ISSUE TITLE
Import Assets and other components from CSV/Excel File

### ISSUE THREAD

**Issue by deeepakkumarthakur16** [grokability/snipe-it#8030]
CSV Import Feature must required to import data from Excel/CSV file so we can easily setup new server and also can use this to migrate data.

**Comment by mnemonicly** [comment]
This exists.  Whats the question?

**Comment by CSAS-Nicholas-Roberts** [comment]
For context to @dmeltzer 's comment...
https://snipe-it.readme.io/docs/importing

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/importing">Importing Assets and More</a></strong></div><div>There is a Web GUI importer available in the Import section that will allow you to upload and process and import a comma-delimited CSV through the web interface. The importer may choke on larger imports, so if you have more than several hundred records to import, you may wish to use the command-line...</div></blockquote>

**Comment by deeepakkumarthakur16** [comment]
I try to use GUI and but stuck on processing msg and if i use cli then it complete quite fast but none of serial number imported. Any idea why serial number missing from import?
![Capture](https://user-images.githubusercontent.com/64971445/83115971-c2d7c980-a0e8-11ea-8a85-03f0256a76ed.PNG)

**Comment by CSAS-Nicholas-Roberts** [comment]
I also started having this problem today too.

I've sat on the import page for over an hour while it said it was "processing" a 135.43KB file (500 assets) and it didn't go anywhere.

Snipe-IT - Version v4.9.1 - build 4341
PHP-7.2.17

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

After looking through debug mode I noticed when I started to process the import that there were some calls out to the Slack API that were erroring out. I removed the Slack integration and whaddya know, it processed right away. I think it has to do with the import's new asset creations calling out to the Slack API and then it timing out due to the high number of request and in turn causing the import to hang.

@deeepakkumarthakur16 are you by chance using the Slack integration? If so, could you disable, and try the import again? How many assets are you trying to import btw? Make sure you have something set for each of the import fields too.

**Comment by deeepakkumarthakur16** [comment]
Thanks for update. 
No, I am not using slack integration. Anyway i have imported assets from CLI but unfortunately Serial Number missing in import. I will try GUI to see if i can import serial number too. 

I also notice there is one more in licenses. I have assigned license to user but License to Name and License to email is empty. Any idea about this?

**Comment by deeepakkumarthakur16** [comment]
Thanks for update.
No, I am not using slack integration. Anyway i have imported assets from CLI but unfortunately Serial Number missing in import. I will try GUI to see if i can import serial number too.

**Comment by chshanoo** [comment]
I had the same issue on localhost. Tried multiple solutions but what worked for me was a small change in .env file. In Outgoing Mail section
change "MAIL_DRIVER=smtp"  to "MAIL_DRIVER=log"

Import worked after that.
