### ISSUE TITLE
Unable to login to Snipe IT

### ISSUE THREAD

**Issue by jeffrobey** [grokability/snipe-it#8094]
#### Expected Behavior (or desired behavior if a feature request)

want to be able to login to administer the system

-----

#### Actual Behavior

cannot login - and the reset password process either does not send an email to me (checked spam, etc),  or gives a "whoops" error if I use a slightly different alias that leads to the same email

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode - cannot
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues) 
of course

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? yes
- Version of Snipe-IT you're running - unknown as I cannot login
- Version of PHP you're running - unknown - Snipe IT is running on an AWS EC2 instance and appears healthy and running
- Version of MySQL/MariaDB you're running - unknown
- What OS and web server you're running Snipe-IT on - Snipe IT is running on an AWS EC2 instance and appears healthy and running
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)unknown
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by uberbrady** [comment]
Unfortunately, this is not enough information for us to be able to help diagnose the issue.

If you can SSH into the server, you should be able to create an Admin user using this procedure: https://snipe-it.readme.io/docs/create-an-admin - then you should be able to log in as that newly-created user to reset your 'real' admin user's password.

You should also modify your server's Mail settings (in `.env`) so that it can correctly send a password-reset mail. If those settings are already correct, then see if perhaps you have SELinux enabled - https://snipe-it.readme.io/docs/common-issues#swift_transportexception-connection-could-not-be-established-with-host-permission-denied-13

Once you can go through that and the additional troubleshooting steps, if you still are having issues, please open a new GitHub issue and we will do our best to help you solve it.

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/create-an-admin">Create an Admin</a></strong></div><div>Since v3.0, we've added the rescue utility to add an admin user via the command line. This can be helpful if you've managed to lock yourself out of your installation (for example if you can't remember your password and never set the system up to send email.)So for example, if you wanted to add a new...</div></blockquote>
<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/common-issues#swift_transportexception-connection-could-not-be-established-with-host-permission-denied-13">Common Issues</a></strong></div><div>  These commands should be run from your Snipe-IT project root, just like every other cli command we mention. They should not need to be run as root/sudo/admin.These commands clear out cached service files that help speed up modern PHP applications but can also very occasionally be out of date, resu...</div></blockquote>

**Comment by jeffrobey** [comment]
How about the "forgot password" portion not functioning?  I use the email address that was set up with Snipe IT and a password reset email never shows up.  This is a big show-stopper for my company as we had a contractor set this up,  but he was laid off due to COVID and now I'm having to jump in...really need some guidance here please
