### ISSUE TITLE
Index Page only present in public folder

### ISSUE THREAD

**Issue by jackdo1** [grokability/snipe-it#8139]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode yes
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues) yes

**Describe the bug**
As stated above all the other pages are not present in the public folder. Unaware as to which step i have missed. Please assist.

**To Reproduce** N/A

**Expected behavior**
I expected to navigate to the page successfully lol

**Screenshots**

![error pages](https://user-images.githubusercontent.com/66971672/84702146-cdcd8f00-af1b-11ea-8790-53417194da73.PNG)

**Server (please complete the following information):**
 - Snipe-IT Version Version v4.9.2 - build 4352 
 - OS: [Win Server 2016]
 - Web Server: [IIS]
 - PHP Version - PHP Version 7.4.7
--

**Desktop (please complete the following information):**
 - OS: [windows 10]
 - Browser [ chrome]
 - Version [Version 83.0.4103.97 (Official Build) (64-bit)
]

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
That's by design. The URL rewrite rules are required in order for the system to function. Please check the IIS installation documentation. 

https://snipe-it.readme.io/docs/windowsiis


<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/windowsiis">Windows/IIS</a></strong></div><div>   Extract Snipe-IT to C:\inetpub\wwwroot\snipe-it (folder name can be changed but we will reference it as is shown here)Run IIS ManagerRight Click Sites and Add Website (See settings below)Click OKYour site will now appear in the list.IIS may not enable the DELETE, PUT, or PATCH verb by default.  T...</div></blockquote>

**Comment by jackdo1** [comment]
i got the page to work with the other pages etc. The links appear like : (servername)/snipeit/index.php/licenses/create.

The CSS doesn't seem to be loading correctly. The site is displaying raw links and text and references. Please assist.
