### ISSUE TITLE
Check snipeit version via ubuntu cli

### ISSUE THREAD

**Issue by masternas** [grokability/snipe-it#8190]
How do I know the version of snipeit installed if I installed from git repository?
On my server, apache currently uses php7.3 but apparently I must have installed latest version of snipeit from git repository which would be looking for latest php 7.4 on the server.

How do I force the app to use php 7.3

**Comment by viclou** [comment]
The latest version of Snipe-IT requires only PHP 7.1.2 or higher, so that doesn't seem to be the issue: https://snipe-it.readme.io/docs/requirements

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/requirements">Requirements</a></strong></div><div>The requirements for Snipe-IT are fairly standard for a modern web server, and most servers will have most or all of these components already installed. If for some reason you don't have them installed, they are relatively easy to add.       </div></blockquote>

**Comment by masternas** [comment]
Thanks so much for the response.
Snipe-it is installed on the server with several instances for several regions. for instance on the same server, i have working snipe-it instances for different countries that are apparently using apache 2.4.29 with php7.3.   if I install the missing extensions for php 7.4, will it break the intances already on the server using php7.3?  By the way the missing extensions are mbstring, dom,curl,simplexml.

**Comment by viclou** [comment]
It looks like this previous ticket touches on this issue and it does look like there could be a problem. One user posted a workaround, though, that you might want to take a look at #7661 
<img width="950" alt="Screen Shot 2020-06-30 at 3 30 24 AM" src="https://user-images.githubusercontent.com/20525448/86116485-5dc61980-ba82-11ea-9041-96f7ffa1a446.png">

**Comment by masternas** [comment]
this is resolved , thanks
