### ISSUE TITLE
import process does not work

### ISSUE THREAD

**Issue by Farrasta** [grokability/snipe-it#8242]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I have tried to import assets. when I press the import button does not change even though I've waited for 30 minutes more
**To Reproduce**
1. Go to import
2. Click on select import file
3. Upload the file
4. Click on proces

**Expected behavior**
asset information should appear

**Screenshots**
the display doesn't change and it's always like this.
![image](https://user-images.githubusercontent.com/28496482/87770273-04fbcc80-c849-11ea-9ff8-43faa8031f31.png)

**Comment by viclou** [comment]
Hi @timothyfarmer If you're not up to date with the latest, v4.9.3, I recommend you follow the instructions here to upgrade: https://snipe-it.readme.io/docs/upgrading. 

Your import is failing because you are missing the required fields. Model Name, Asset Tag, Manufacturer, and Category are all required fields (not including these will cause your import to fail). For more information on importing and for sample .csv import files, see: https://snipe-it.readme.io/docs/importing.
