### ISSUE TITLE
Works very slowly SQL for ~1,400,000 assets.

### ISSUE THREAD

**Issue by StackAls** [grokability/snipe-it#8243]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I imported 1392861 assets. 
When I choise Assets - List All the page is loaded more 20 sec.

**To Reproduce**
1. Import more 1300000 assets
2. Click on Assets - List All 
3. See long download

**Expected behavior**
fastest show page
**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version  Version v4.9.3 - build 4395 (master)
 - OS: CentOS 7
 - Web Server: Apache
 - PHP Version : 
PHP 7.2.30 (cli) (built: Apr 15 2020 07:23:04) ( NTS )
Zend Engine v3.2.0, with Zend OPcache v7.2.30, Copyright (c) 1999-2018, by Zend Technologies

**Desktop (please complete the following information):**
 - OS: Win 7
 - Browser chrome
 - Version 83.0.4103.116 official 64-bit

**Error Messages**

**Additional context**
mysql conf
mysql  Ver 15.1 Distrib 5.5.64-MariaDB, for Linux (x86_64) using readline 5.1
```
 [server]
skip-name-resolve=1
character_set_server=utf8
innodb_file_per_table=ON
innodb_buffer_pool_size=4G
innodb_buffer_pool_instances=4
innodb_log_file_size=512M
innodb_log_buffer_size=4M
innodb_flush_method = O_DIRECT  #O_DSYNC
innodb_flush_log_at_trx_commit = 0
sort_buffer_size=256M
read_rnd_buffer_size=16M
join_buffer_size=512M
thread_cache_size=4
query_cache_size=64M
query_cache_type=0
query_cache_limit=2M
slow_query_log          = 1
slow-query_log_file     = /var/log/mariadb/mysql-slow.log
long_query_time         = 1
expire_logs_days        = 10
max_binlog_size         = 512M
innodb_stats_on_metadata = OFF
```

MariaDB tuned mysqltuner.

mysql-slow.log

```
# User@Host: snipe_user[snipe_user] @ localhost []
# Thread_id: 3452  Schema: snipeit  QC_hit: No
# Query_time: 17.311999  Lock_time: 0.000026  Rows_sent: 50  Rows_examined: 2785777
SET timestamp=1594989793;
select `assets`.* from `assets` inner join `status_labels` as `status_alias` on `status_alias`.`id` = `assets`.`status_id` and `status_alias`.`archived` = 0 where `assets`.`deleted_at` is null order by `asset_tag` asc limit 50 offset 0;
```

I add for all field indexes, But it did not help.
But if I query in mysql console fewer fields - The result is much much better.

Please change code for page Assets - List All to ONLY showed fields on this page selected in SQL query.
(e.g. select `assets`.* from `assets` - bad idea)

**Comment by uberbrady** [comment]
I feel like if we add an index across **three** columns in the assets table, it might help quite a lot - specifically:

`(status_id, deleted_at, asset_tag)`

Can you give that a shot, and let us know if it works? If so we'll add it to the Snipe-IT source, so everyone can benefit. (And, once we do that, you should remove your index so that when you run updates you don't end up with two separate indexes across the same fields).

**Comment by StackAls** [comment]
Of course I added indexes, but it didn't help.
I also tried adding an index to each table field - (9 seconds in the console mysql and 19 seconds in the browser).
the result has not changed.
Acceptable performance appeared only when I listed in the request only those fields that are displayed on the page.
I also experimented in the console mysql and got that performance (<3 sec) drops sharply if there are more than ~ 10 fields in the request in table assets/

**Comment by uberbrady** [comment]
So I'm specifically talking about a multi-column index - something like:

```sql
CREATE INDEX my_index ON assets (status_id, deleted_at, asset_tag) 
```

Unfortunately, it'd be hard for us to change our query-building system to cut down the number of fields we `SELECT` out. I'm curious if you have your database "far away" from your web-server? I'm not used to seeing those large differences in query performance due to too many columns being chosen. But, sometimes, weird things happen.

I'm going to try my best to see if I can seed a database with a large number of entries so I can replicate the issue you're seeing. If you haven't already made the index I just suggested, can you give that a shot, and let me know how it goes?

**Comment by uberbrady** [comment]
Were you able to add the multi-column index and see if it helped, @StackAls ? It's a shot in the dark but if it helps you it might help other users, and we'll want to add a migration to implement that index.

I'm currently hyper-focused on v5 so I haven't had a chance to try and replicate your environment in my development environment yet, unfortunately.
