### ISSUE TITLE
Automated Alerting

### ISSUE THREAD

**Issue by Pete987** [grokability/snipe-it#8246]
Hi all, I would like to just get community confirmation of the following

1) There is no way to get an Automated Report emailed to me weekly of any Unaccepted Assets? It seems that someone has to manually generate this report. If so, is this true for ALL reports in the Reports link? We ask specifically for the Overdue Audits Report and the Unaccepted Assets Report. 

2) Can someone explain to the the process of Automating backups of SnipeIT? I can see how to run backups manually, how can I run an automated backup? 
Many thanks everyone

**Comment by snipe** [comment]
You have to set up the alerts using cron or scheduled tasks. This is in the documentation. 

https://snipe-it.readme.io/docs/configuring-alerts-backups
https://snipe-it.readme.io/docs/email-alerts

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/configuring-alerts-backups">Configuring Alerts & Backups</a></strong></div><div>Starting from Snipe-IT v3.0, all automated tasks are handled via the scheduler. To set a cron job to run every minute to ping the scheduler:The scheduler already knows how often it should trigger the individual tasks, because of this code in the Console Kernel:So basically, the scheduler will figure...</div></blockquote>
<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/email-alerts">Email Alerts</a></strong></div><div>Snipe-IT comes with several email alert options which can be run manually via command line, or more typically on a cron job (Linux) or scheduled task (IIS). Most of these settings are managed in Settings &gt; Notifications, however self-hosted users will need to set up a cron job to trigger the aler...</div></blockquote>
