### ISSUE TITLE
Allow items to have different "Deployed" status labels.

### ISSUE THREAD

**Issue by sboonstra0** [grokability/snipe-it#8296]
Using Snipe-IT to manage Chromebooks for a high school. In the summer, we want to "Check In" the devices, but then we have no way of assigning the same Chromebook to each student in the fall, besides manually matching student to device, or importing a spreadsheet (which we're using Snipe-IT to move away from). Ideally, we could keep the devices as "Checked Out" but change the status label from "on loan" to "turned in" or similar. Currently, however, because "Deployed" is a metastatus label, it's not an option for "Status Type" when creating custom status labels. This is the feature I'm requesting.

If a different solution exists to keep assets assigned while checked in, please let me know.

![image](https://user-images.githubusercontent.com/28842475/89429087-b8e2d000-d702-11ea-9f6e-52f9a1f89fa3.png)

**Comment by petersont4** [comment]
Could you create a custom Status label with a status type as deployable?  Name it something like (IN IT POSSESSION) .  Then because the item is still in a deployable status, it does not check the item in.

I have setup a custom status label called "Needs Asset Tag" Where if I find an item that needs a new asset tag printed, I put it in that status.  Its checked out status maintains the same, then I can put it back into Ready to Deploy Status once the label is printed and all is good.

**Comment by sboonstra0** [comment]
That works perfect. I'm a little embarrassed I didn't realize that myself. :) Thank you for your help, @petersont4 !
