### ISSUE TITLE
How to set "serial" as a required field.

### ISSUE THREAD

**Issue by conan522** [grokability/snipe-it#8368]
How to set "serial" as a requested field.

I changed as below, but did not work.

Snipe-IT\resources\views\hardware\edit.blade.php

@include ('partials.forms.edit.serial', ['translated_serial' => trans('admin/hardware/form.serial'), 'required' => 'true'])

**Comment by snipe** [comment]
You would need to edit the model validation.

That said, keeping local changes means you're going to have a harder time upgrading down the line since your local version will not longer be the same as ours. You might just want to create a required custom field called "Required Serial", and then the required part of the custom field validation will kick in.

**Comment by conan522** [comment]
Thanks.
