### ISSUE TITLE
Requestable Assets

### ISSUE THREAD

**Issue by jmartins1** [grokability/snipe-it#8416]
**Describe the bug**
Deployed vs. Available for request

**To Reproduce**
On requestable Assets page for users. 

**Expected behavior**
Assets tab, shows all requestable items. Items should not appear here if there are already deployed.
Asset Models tab, shows total quantity of asset model. It should only show what's available, i.e. what is not deployed.

**Comment by snipe** [comment]
It works this way by design. An asset being checked out doesn't mean it will be checked out forever. In the situation of, for example, test devices for an app development company, the checkout time may be days or weeks, not months or years. "I'm next in line when this becomes available" is that use case.
