### ISSUE TITLE
ldap sync memory size 

### ISSUE THREAD

**Issue by linux-ops** [grokability/snipe-it#8535]
PHP Fatal error:  Allowed memory size of 524288000 bytes exhausted (tried to allocate 1310720 bytes) in /data/cmdb_web/vendor/adldap2/adldap2/src/Query/Processor.php on line 95
PHP Fatal error:  Allowed memory size of 524288000 bytes exhausted (tried to allocate 20480 bytes) in /data/cmdb_web/vendor/laravel/framework/src/Illuminate/Log/Logger.php on line 40

**Comment by syndr** [comment]
I'm seeing the same error. This is on version 5.0.0, and was updated from v4.9.5.  It's running on Docker using the official Docker release.   Tried setting the `LDAP_MEM_LIM` environment variable to 750M, and I still get the same error as below.

This appears when I select "test" in the LDAP settings page.

I did note that the PHP info page accessed from the settings page lists the PHP memory limit as 128M.

```
[2020-10-20 17:07:26] production.ERROR: Allowed memory size of 134217728 bytes exhausted (tried to allocate 528384 bytes) {"userId":11025,"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Allowed memory size of 134217728 bytes exhausted (tried to allocate 528384 bytes) at /var/www/html/vendor/adldap2/adldap2/src/Query/Processor.php:95)
[stacktrace]
```

**Comment by SmithD3** [comment]
#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
A clear and concise description of what the bug is.

When trying to sync LDAP, we get a "504 Gateway Time-out"
When trying to Test LDAP Synchronization, we get a "500 Server Error" (it will actually test sync successfully rarely though)

**To Reproduce**
Steps to reproduce the behavior:
1. Go to 'Settings>LDAP'
2. Click on 'Test LDAP Synchronization'
3. See error '500 Server Error'

**Expected behavior**
A LDAP sync successfully test and also sync LDAP.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Server (please complete the following information):**
 - Snipe-IT Version 
 Version v5.0.0 - build 4484 (develop)
 - OS: [e.g. Ubuntu, CentOS]
Docker
 - Web Server: [e.g. Apache, IIS]
Built in Docker Web Server
 - PHP Version 
7.2.24-0ubuntu0.18.04.6

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
Windows 10 1809
 - Browser [e.g. chrome, safari]
Chrome
 - Version [e.g. 22]
Version 86.0.4240.75

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
We will get two debug error messages at a time:

```
[2020-10-21 08:23:32] production.ERROR: Allowed memory size of 134217728 bytes exhausted (tried to allocate 528384 bytes) {"userId":11023,"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Allowed memory size of 134217728 bytes exhausted (tried to allocate 528384 bytes) at /var/www/html/vendor/adldap2/adldap2/src/Query/Processor.php:95)
Stack trace:
#0 {main}  
```

```
[2020-10-21 08:23:32] production.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Allowed memory size of 134217728 bytes exhausted (tried to allocate 528384 bytes) in /var/www/html/vendor/adldap2/adldap2/src/Query/Processor.php:95
[stacktrace]
#0 {main}
"} 
```

- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
Unable to test LDAP in the Demo
- Include any additional information you can find in `storage/logs` and your webserver's logs.
```
[2020-10-21 08:23:32] production.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Allowed memory size of 134217728 bytes exhausted (tried to allocate 528384 bytes) in /var/www/html/vendor/adldap2/adldap2/src/Query/Processor.php:95
Stack trace:
#0 {main}  
[2020-10-21 08:23:32] production.ERROR: Allowed memory size of 134217728 bytes exhausted (tried to allocate 528384 bytes) {"userId":11023,"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Allowed memory size of 134217728 bytes exhausted (tried to allocate 528384 bytes) at /var/www/html/vendor/adldap2/adldap2/src/Query/Processor.php:95)
[stacktrace]
#0 {main}
```

**Additional context**
- Is this a fresh install or an upgrade? 
Upgrade
- What OS and web server you're running Snipe-IT on
Official Docker container
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) 
Docker
- Include what you've done so far in the installation, and if you got any error messages along the way.
We ran the `php upgrade.php` after following the 5.0 upgrade documentation for Docker by pointing it at the new container because we were getting many `500 Server Errors`
- Indicate whether or not you've manually edited any data directly in the database
No, we haven't

Add any other context about the problem here.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.


<blockquote><img src="https://snipeitapp.com/img/desktop_snipe.png" width="48" align="right"><div><strong><a href="https://snipeitapp.com/demo">Try the Demo - Snipe-IT Open Source IT Asset Management</a></strong></div><div>Try the live demo of Snipe-IT, the best open source IT asset management system around.</div></blockquote>

**Comment by linux-ops** [comment]
edit  app/Console/Commands/LdapSync.php    memory_limit  SIZE  FIX .

but  ,why .env file ldap options  memory_limit  no work ???

**Comment by syndr** [comment]
We upgraded our Docker container to v5.0.1, and I'm still seeing this issue.  I changed the `memory_limit = 128M` to `memory_limit = 1024M` in `/etc/php/7.2/apach2/php.ini` for the purposes of testing, and restarted apache with `apachectl -k graceful`, and this fixed the 500 error when the "Test LDAP settings" button is clicked, and it does return results.

However, this isn't really viable, as the file is of course overwritten with the default values every time the container is recreated.

Also, when I attempt to sync LDAP users from the user section of the UI, it sits there "processing" for a minute or to, and then I get the generic nginx "504 Gateway Time-out" page.

For environment variables, `LDAP_MEM_LIM = 750M` and `LDAP_TIME_LIM = 1200`.

**Comment by SmithD3** [comment]
@uberbrady

**Comment by uberbrady** [comment]
The latest v5.0.3 has at least a possible fix for the LDAP memory consumption issue in it; can you folks give that a shot and see if it helps at all?

**Comment by uberbrady** [comment]
(It didn't! But this does: https://github.com/snipe/snipe-it/releases/tag/v5.0.4 )

<blockquote><img src="https://repository-images.githubusercontent.com/14346979/164a6580-7d79-11e9-865f-eae87593e11a" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="/snipe/snipe-it/releases/tag/v5.0.4">Release v5.0.4 · snipe/snipe-it</a></strong></div><div>New in v5.0.4
This is a bug fix release that should handle some of the issues reported over the past few days.
We'll be hitting them back as quickly as you can throw issues at us, so keep them comi...</div></blockquote>

**Comment by uberbrady** [comment]
Also, in v5 we weren't correctly respecting `LDAP_MEM_LIM` - until 5.0.5 or so. Now we do.

**Comment by uberbrady** [comment]
I think this is solved, but we can certainly reopen it if it is not.
