### ISSUE TITLE
Duplicate URL on images after V5 upgrade

### ISSUE THREAD

**Issue by ghost** [grokability/snipe-it#8559]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Image URL for logo and asset uploads is duplicating the domain URL after upgrade to V5

**To Reproduce**
Upgrade to V5

**Expected behavior**
Images to show with no duplicate URL

**Screenshots**
![image](https://user-images.githubusercontent.com/66947149/96697957-71c0be80-1384-11eb-8789-125cf3c4a290.png)

**Server (please complete the following information):**
 - Snipe-IT Version 5
 - OS: Windows Server 2016
 - Web Server: IIS
 - PHP Version: 7.4

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chromium-Based Edge

**Smartphone (please complete the following information):**
 - N/A

**Error Messages**
None

**Additional context**
Upgrade, no manual editing of data in any form

**Comment by SamehElsakka** [comment]
i have the exact same issue

**Comment by WELLBOREIS** [comment]
Same here

**Comment by nbently** [comment]
@SamehElsakka are you using IIS on Windows as well?

**Comment by WELLBOREIS** [comment]
@nbently I am

**Comment by nbently** [comment]
> @nbently I am

I had noticed, I am wondering if there is something weird happening specifically on IIS. I'm going to try to set up a VM with Snipe-IT on IIS later & do an upgrade from 4.9.5 to 5 to see if I can get the error.

**Comment by SamehElsakka** [comment]
@nbently   yes i am, and i have just resolved it by using the new .env file i coppied all the data and left the app url as null,this resolved the issue for me

**Comment by ghost** [comment]
> @nbently yes i am, and i have just resolved it by using the new .env file i coppied all the data and left the app url as null,this resolved the issue for me

You set the app URL as null? That's not ideal.

**Comment by snipe** [comment]
It’s not ideal, no. Before you tried that, can you confirm that your APP_URL included the http protocol (http:// or https://)

**Comment by SamehElsakka** [comment]
I just checked it again added the APP_URL without http protocol as before(AMS.Domain.com) and all images URL duplicated again so i added the http protocol and worked well now(http://AMS.Domain.com). but thee question is why this only happened after upgrading the version 5 before was working without any issues i have been using it for a year now.

**Comment by snipe** [comment]
>  but thee question is why this only happened after upgrading the version 5 before was working without any issues i have been using it for a year now.

We upgraded the underlying framework Snipe-IT is built on, and I believe they changed some of the inner workings of that, which is why you're seeing it only now. The env parser is more strict now, among other things. We *do* mention that you should include the protocol in that APP_URL value in the docs, but I imagine you're not the first (nor will you be the last) who missed that bit. Unfortunately, since it's a framework level change (i.e. not us), it's hard to mitigate that.

We did also make some changes to put us in a better position to allow uploads to go to S3/Rackspace/wherever versus being hosted on the same drive as the app itself, so we changed some of the URL handling, which might be another reason why you're only seeing this now.
