### ISSUE TITLE
Error on Backup

### ISSUE THREAD

**Issue by Raffudeen** [grokability/snipe-it#8611]
Dear ,

i can't able to genrate backup of my snipeit server .Attached the Screen Shot. Please advice...
![Capture](https://user-images.githubusercontent.com/70876850/97102735-0004af80-16b9-11eb-8f24-4f87f0225c56.JPG)
 server.. Attached the Screenshot .

![image](https://user-images.githubusercontent.com/70876850/97102722-e8c5c200-16b8-11eb-85d9-835ae4fc5b3d.png)

**Comment by denzfarid** [comment]
> Dear ,
> 
> i can't able to genrate backup of my snipeit server .Attached the Screen Shot. Please advice...
> ![Capture](https://user-images.githubusercontent.com/70876850/97102735-0004af80-16b9-11eb-8f24-4f87f0225c56.JPG)
> server.. Attached the Screenshot .
> 
> ![image](https://user-images.githubusercontent.com/70876850/97102722-e8c5c200-16b8-11eb-85d9-835ae4fc5b3d.png)

try chmod -R 777 /var/www/snipeit/storage/app/backup-temp

**Comment by Raffudeen** [comment]
If i try this im getting : Operation not permitted. Attached the screen shot .

![image](https://user-images.githubusercontent.com/70876850/97111874-44f90800-16f2-11eb-994b-4356eaf32baa.png)

**Comment by roratonet** [comment]
Prepend "sudo" if administrator is in the sudoers file, or login as root

**Comment by Raffudeen** [comment]
Done... Thank You...

**Comment by uberbrady** [comment]
I'm glad you got it going and it's working for you, but generally we tend to try to avoid using `chmod -R 777` - because it means that *any* user on this Unix box can now read and write to the backup directories. If there's only ever one 'user' on the box at any time? Probably not a big deal (though @snipe , who is far more of a security nerd than I am, may disagree).

But if you did have some kind of setup where a bunch of different users were logging on to this box - or if it was on shared hosting - I would recommend instead trying to `chown` the directories over to the same user that your webserver runs as. Or even if you had a bunch of separate _services_ running on this box - if a user compromised one of them, they could probably get access to your backups. But, again, if you're just running Snipe-IT? Probably ok, then?

**Comment by Raffudeen** [comment]
THANKS FOR THE SUPPORT..KEEP SUPPORTING…… And I have an other issue too while asset checkout. For that I should open a new ticket or I can continue in this???  Sent from Mail for Windows 10 From: Brady WetheringtonSent: Monday, October 26, 2020 7:25 PMTo: snipe/snipe-itCc: Raffudeen; AuthorSubject: Re: [snipe/snipe-it] Error on Backup (#8611) I'm glad you got it going and it's working for you, but generally we tend to try to avoid using chmod -R 777 - because it means that any user on this Unix box can now read and write to the backup directories. If there's only ever one 'user' on the box at any time? Probably not a big deal (though @snipe , who is far more of a security nerd than I am, may disagree).But if you did have some kind of setup where a bunch of different users were logging on to this box - or if it was on shared hosting - I would recommend instead trying to chown the directories over to the same user that your webserver runs as. Or even if you had a bunch of separate services running on this box - if a user compromised one of them, they could probably get access to your backups. But, again, if you're just running Snipe-IT? Probably ok, then?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by roratonet** [comment]
If there is no similar issue open, please create a new one with your concern.

**Comment by denzfarid** [comment]
> I'm glad you got it going and it's working for you, but generally we tend to try to avoid using `chmod -R 777` - because it means that _any_ user on this Unix box can now read and write to the backup directories. If there's only ever one 'user' on the box at any time? Probably not a big deal (though @snipe , who is far more of a security nerd than I am, may disagree).
> 
> But if you did have some kind of setup where a bunch of different users were logging on to this box - or if it was on shared hosting - I would recommend instead trying to `chown` the directories over to the same user that your webserver runs as. Or even if you had a bunch of separate _services_ running on this box - if a user compromised one of them, they could probably get access to your backups. But, again, if you're just running Snipe-IT? Probably ok, then?

I totally agree !!, if snipeit is installed with the installer, then by default we have a snipeitapp user, and we can chown that user and chmod -R 755, I give 777 solution because I don't know what user the web server is running?
administrator, or default www-data or maybe apache,
should be chown based on the user running the service 🤝

Thanks for the correction :)
