### ISSUE TITLE
Issue while composer install on php 7.1.33

### ISSUE THREAD

**Issue by GaneshKandu** [grokability/snipe-it#8622]
**Describe the bug**
Hi I Having an issue while installing composer

```
Composer detected issues in your platform:

Your Composer dependencies require a PHP version ">= 7.2.0". You are running 7.1.33.
```

Snipe-IT required php 7.2.0 but [https://snipe-it.readme.io/docs/requirements](https://snipe-it.readme.io/docs/requirements) mentioned it require 7.1.3

**Screenshots**

![image](https://user-images.githubusercontent.com/12833130/97261171-49cdd100-1844-11eb-8b0a-69cc7c08633d.png)

**Server (please complete the following information):**
 - Snipe-IT Version : 5.0.4
 - OS: [e.g. Ubuntu, CentOS] : CentOS
 - Web Server: [e.g. Apache, IIS] : Apache
 - PHP Version : 7.1.3

**Error Messages**

```
Composer detected issues in your platform:

Your Composer dependencies require a PHP version ">= 7.2.0". You are running 7.1.33.
```

**Additional context**

[https://packagist.org/packages/doctrine/lexer](https://packagist.org/packages/doctrine/lexer) need php 7.2
[https://packagist.org/packages/spatie/laravel-backup](https://packagist.org/packages/spatie/laravel-backup)  6.9.0 need php 7.2

**Comment by hpz** [comment]
I have the same issue. The install.sh file for Debian 9 installs php 7.1 packages.

**Comment by ffuentes** [comment]
Hi, I upgraded from v4.8.0 to 5.0.4 without issues and I'm running php v7.1.33 on CentOS 7. 

Are you doing a fresh install?

**Comment by GaneshKandu** [comment]
> Are you doing a fresh install?

yes

**Comment by snipe** [comment]
This is definitely a bug, either in the docs or in the composer file. I don't *think* we actually need PHP 7.2 - it should only require 7.1.3, but our composer.json definitely locks it in at 7.2.

I'm going to try a fresh install with just 7.1.3 (removing the composer PHP version requirement) and see if it works.

**Comment by snipe** [comment]
I just tried it with 7.1.3 and everything seemed okay. 

I'd love confirmation of that by others tho? Just change the bit at the end of `composer.json` to:

```json
"config": {
    "preferred-install": "dist",
    "sort-packages": true,
    "optimize-autoloader": true,
    "process-timeout": 3000,
    "platform": {
      "php": "7.1.3"
    }
  }
```

and re-run `composer install --no-dev`

I'd still recommend using PHP 7.2 if you can, since later versions of Snipe-IT will likely require it, but I'll update the composer file to reflect the correct requirement if we can confirm. Not sure I can push that into a version update since not much else changed, but if we can confirm that it does actually work wth 7.1.3, I'll see if I can make that happen.

**Comment by GaneshKandu** [comment]
@snipe  Thanks for clarification.
