### ISSUE TITLE
Add user via SAML on login

### ISSUE THREAD

**Issue by fredericOfTestfabrik** [grokability/snipe-it#8687]
**Server (please complete the following information):**
 - Snipe-IT Version 5.0.4

**Is your feature request related to a problem? Please describe.**
It appears that in order to login with saml, I already need an account in snipe-it. At least there should be an option that creates an user automatically.

**Describe the solution you'd like**
Implement a flag that creates a user from saml data, if there is a valid saml login and the flag is set

**Comment by hixair** [comment]
I think that what you are asking for is provisioning.
There is a SCIM feature to do that but i am not sure that the SAML component used by snipe-it allows it (and you IDP has to support SCIM also).
Your IDP probably provides an LDAP interface, you could sync with the LDAP to provision accounts into snipe-it (with the proper account address so that they can login).

**Comment by danielewood** [comment]
I too would appreciate such functionality, even if limited to auto-creation of user on first login of said user as far as provisioning and put them in a group that I can grant a default set of permissions for all users.

Right now I generate a CSV using GAM from my GSuite tenant and then import that, I would prefer to not have to do this manual step. 

We use GSuite Business, not Business Plus, which does not provide LDAP functionality. GSuite does do SCIM, but it looks like you would have be a [pre-configured SAML app](https://cloud.google.com/identity/solutions/automate-user-provisioning) (and who knows how to get Google to approve that, much less where to ask for it).

**Comment by fredericOfTestfabrik** [comment]
Unfortunately my IDP does not have a LDAP interface, as far as i know. I agree with @danielewood, that auto-creation on first login in would be enough, at least for my use case.

**Comment by snipe** [comment]
I'm not sure that's really possible though, since a password is required to create a user and we wouldn't get that from SAML.

**Comment by danielewood** [comment]
> I'm not sure that's really possible though, since a password is required to create a user and we wouldn't get that from SAML.

I'm perfectly fine with automatic generation of a 64character random string for the password. Just make it a note on the checkbox when enabling auto creation from SAML on first login. 

When SAML is enabled, I don't want users logging in with their own password anyways.

**Comment by RyanMorash** [comment]
I'm fine with randomized password generation as well.

SCIM support would be nice so we don't need to wait for the user's first sign in to Snipe-IT to assign assets. I'm surprised Google doesn't allow SCIM on custom apps, but it would be nice for Azure AD or other IDaaS providers like Okta.

Just-in-time provisioning of users on first SAML login would most likely be needed as well. In addition to updating user info, it would be needed for cases where SCIM is not supported and in case a user signs in before SCIM has provisioned them.

**Comment by kenchan0130** [comment]
Is there any progress on this issue?
Provisioning with LDAP is not very common for users using managed IdPs.

I think provisioning with SAML with JIT or SCIM is becoming more common.

**Comment by SeanHansell** [comment]
+1 for SCIM support. We use Okta as our IdP and having the ability to provision (as well as update, and deprovision) users via SCIM would be very helpful. Combined with SAML it can create a complete lifecycle tool.

**Comment by uberbrady** [comment]
There are a couple of problems with this, and why we haven’t really rushed to implement it.

The biggest one is that most IT organizations have a small subset of users who actually log in, and a larger chunk of users who have assets assigned to them, but may not log in directly.

Adding a user on SAML login doesn’t help those folks much.

As for other more complex authentication systems like SCIM, it’s not off the table. LDAP is a nightmare for us to support, and a more modern system would absolutely be appreciated, but I don’t know that enough of the various identity providers out there support it. I would love for us to, though, if we could.

⭐ pull requests are always welcome 😄 ⭐

**Comment by adagioajanes** [comment]
Just to clarify for everyone, there are two different feature requests being discussed here. Those are SAML JIT and SCIM.

The original request is referring to SAML Just In Time (JIT) provisioning. That is, when a user logs in via SAML, and the user does not already exist in the system, the system will use the SAML response to create a new user.

> The biggest one is that most IT organizations have a small subset of users who actually log in, and a larger chunk of users who have assets assigned to them, but may not log in directly.
> 
> Adding a user on SAML login doesn’t help those folks much.

This is pretty much the top reason why I think SAML JIT is the wrong move for this.

_System for Cross-domain Identity Management_ (SCIM) would accomplish this goal much better. With SCIM, instead of provisioning at logon, the users and groups are provisioned via an API connection between the application and the SCIM compatible directory service. I have put in a feature request for SCIM functionality over at #10412 (that mentions Azure AD specifically, but SCIM is an open standard that _should_ be supported by more than Azure AD).

**Comment by mattytr2** [comment]
+1

**Comment by snipe** [comment]
We have a PR open for SCIM and it will be in v6.

**Comment by sk3pp3r** [comment]
+1
