### ISSUE TITLE
Moving Snipe IT to Ubuntu on Azure

### ISSUE THREAD

**Issue by giga-t** [grokability/snipe-it#8704]
Hello everyone,

Unfortunately my strongest side is not Linux and Snipe IT, but I'm learning, and I would really appreciate your help very much.
Situation is following:
I have an existing, local Snipe IT self hosted (on Ubuntu server) which i would like to migrate to Cloud. I've created a VM on Azure, installed Ubuntu server and finished setting up Snipe IT. Now I'd like to migrate the data and everything from the old server to the new one. I've found this article:
https://snipe-it.readme.io/docs/moving-snipe-it

But, I'm not quite sure how to do these steps, because they're described so briefly. I've already backed up old data from Snipe-IT admin panel at Admin > Backups. Now I'd like to perform the following steps:

Import your data into your target server's database - **how should I import data into my new cloud server's database?**

Copy over your old .env, or (if upgrading while moving), use the example.env for the current version and fill in the blanks, saving the revised copy as .env in the new server. We recommend this if you're moving+upgrading and new things were added to the .env since your last version, as it's just typically easier than going through the example.env line by line and adding things to an existing .env, but the choice is yours. Make sure the database name and credentials in your new .env match the database name, username and password for your new target database. - **Not quite clear what should I do here.**

Copy over the directories and their contents from the public/uploads directory - **How should I do this?** 

Copy over the directories and their contents from the storage/private_uploads directory - **How should I do this?** 

Copy over your storage/oauth-private.key and storage/oauth-public.key - **How should I do this? (BTW, on the old server I had Local Active Directory sync, on the azure I want to integrate Azure SAML SSO)**

If your hostname (the name through which you access Snipe-IT) has changed, be sure to change that in your .env - **How should I do this?** 

Make sure the storage and public/uploads directories (and all subdirectories) are writable by the web server. - **How should I do this?** 

Run php artisan migrate to make sure there are no outstanding database migrations 

Run php artisan config:clear to clear out any stored config variables 

Once again, I would really appreciate your help.

**Comment by snipe** [comment]
This is really kind of outside the scope of Snipe-IT's support. The docs on moving Snipe-IT are "brief" because we do sort of expect you know a least a little bit about servers (even cloud servers) so that you can perform the kinds of operations like importing/exporting/edit the .env/changing permissions, etc. It would be impossible (and impractical) for us to document how to do this on every cloud provider that exists. 

> BTW, on the old server I had Local Active Directory sync, on the azure I want to integrate Azure SAML SSO

In theory, you'd need *both* if you wanted to keep importing the list of users in your AD (for example so they become part of your user's list, so you can assign things to them). Azure SSO doesn't provide any sort of directory access, only SSO login. That's not really our fault, just an artifact of how SAML/SSO works.

I don't have a lot of familiarity with Azure, so I'll leave this ticket open in case other community users do and can possibly help.
