### ISSUE TITLE
Cannot map Default Location on import

### ISSUE THREAD

**Issue by kstant** [grokability/snipe-it#8705]
#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
There is a field called "Default Location" when I export from SnipeIT. But when I create an import CSV file and have  "Default Location" as one of my Header Field, it doesn't automatically map to any field on import, and there is no (obvious) import field to select in the import field mapper. 

Also, a lot of the fields on export are named something slightly different from the import fields.
* I am fairly new to Snipe IT but couldn't find this exact problem addressed in any help forum or documentation. Thanks.

**To Reproduce**
1. Go to import
2. Select Process

**Expected behavior**
Exported fields should have the same names as the import fields. And there should be a field called "default location" in the import.

**Server (please complete the following information):**
 - Snipe-IT Version = v4.7.7 - build 4160 (master)
 - OS: [e.g. Ubuntu, CentOS] ?
 - Web Server: [e.g. Apache, IIS] ?
 - PHP Version = 7.3.23

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] all
 - Browser [e.g. chrome, safari] all

**Additional context**
- Is this a fresh install or an upgrade? fresh
- What OS and web server you're running Snipe-IT on. ?
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc). ?
- Include what you've done so far in the installation, and if you got any error messages along the way. na
- Indicate whether or not you've manually edited any data directly in the database. No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
The exported headers and the import headers are not the same because they serve two different purposes (and because we don't use translated fields in the import process). You should be using the headers specified here: https://snipe-it.readme.io/docs/importing#sample-csv-downloads

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/importing#sample-csv-downloads">Importing Assets and More</a></strong></div><div>There is a Web GUI importer available in the Import section that will allow you to upload and process and import a comma-delimited CSV through the web interface. The importer may choke on larger imports, so if you have more than several hundred records to import, you may wish to use the command-line...</div></blockquote>

**Comment by kstant** [comment]
Thanks for the reply. So which import header maps to "Default Location"?

**Comment by snipe** [comment]
I believe just `Location`

**Comment by kstant** [comment]
Negative. "Location" (on import) maps to "Location" (which is current location) AND "Checkout Location"

**Comment by kstant** [comment]
Answered my own question. For anyone else, here is the explanation.

If your import CSV file ONLY has the "Location" header on import, it will populate into "Default Location" AND "Location" (current location). Overwriting existing values.

If your import CSV has **all three** of the following headers it will split up the location of the asset:
Location, Checkout Type, Checkout Location

**Example (on import CSV):**
Location = IT Closet
Checkout Type = location
Checkout Location = Room 302

**Will give you this result in SnipeIT:**
Location = Room 302
Default Location = IT Closet

* Note the definition of "Location" switches from Default Location in import file to Checkout Location in the SnipeIT system. 
* Also, be sure to include "Checkout Type" set to "location" (lower case) or it wont work.
