### ISSUE TITLE
Assigned accessories list is empty

### ISSUE THREAD

**Issue by yanagha** [grokability/snipe-it#8760]
After updating to the latest version if I want to check accessories assigned to the user, cannot see them. To replicate the issue
Go to People > Select user > Open Accessories tab and you will see something like this 
Showing 1 to 7 of 7 rows, but the list is empty. Please see the screenshot

![image](https://user-images.githubusercontent.com/18484466/99382993-bc334d80-28e6-11eb-974a-6d4bc159e4dc.png)

Snipe-it version  v5.0.7 - build 5615 (master)

**Comment by snipe** [comment]
Please provide answers to the questions you deleted. I cannot reproduce this on the demo.
https://demo.snipeitapp.com/accessories/1
https://demo.snipeitapp.com/users/5#accessories

Also make sure you've selected columns in the column selector for the table view, and confirm whether or not you're seeing any errors in your error log or browser console. Without that information, it's impossible to guess what's happening here.


#### Confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Add any other context about the problem here.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

![enlkq1k](https://user-images.githubusercontent.com/197404/31936238-da7c20cc-b865-11e7-8706-4cf76a7ec461.gif)

<blockquote><img src="https://demo.snipeitapp.com/favicon.ico" width="48" align="right"><div><strong><a href="https://demo.snipeitapp.com/accessories/1">Snipe-IT Asset Management Demo</a></strong></div></blockquote>
<blockquote><img src="https://snipeitapp.com/img/desktop_snipe.png" width="48" align="right"><div><strong><a href="https://snipeitapp.com/demo">Try the Demo - Snipe-IT Open Source IT Asset Management</a></strong></div><div>Try the live demo of Snipe-IT, the best open source IT asset management system around.</div></blockquote>

**Comment by yanagha** [comment]
Hi, 
The problem is fixed. It  was related to the columns. It seems they have been unticked automatically after the update.

Thank you!

**Comment by snipe** [comment]
Glad to hear you're all sorted! In the future, if you've resolved your issue, please try to remember to close your ticket - it helps us out a lot. (We have to manage a lot of tickets.)

![tenant-tyvm](https://user-images.githubusercontent.com/197404/35019316-1bec03bc-fadb-11e7-92d3-0694b211e921.gif)

**Comment by yanagha** [comment]
Hi, 

Is it possible to set which columns should be visible for all users?  We have more than 500 users and for each users, I am setting columns one by one. All columns were visible before the update.
