### ISSUE TITLE
[Help Needed] Need Okta LDAP (& others LDAP providers) testing for new LDAP sync

### ISSUE THREAD

**Issue by uberbrady** [grokability/snipe-it#8808]
We've seen a few reports now that Snipe-IT v5's LDAP sync operation is starting to trigger some kind of incompatibility with Okta's version of LDAP. We're **probably** just sending them too many queries. But it's really hard to 'see' from our end whether or not we're doing that.

Please check out my PR here: #8801 and let us know if it works for you (and who your LDAP provider is).

Okta is specifically the only provider we're actually having trouble with right now, but I'd be happy to see testing with _any_ LDAP provider out there. I need to get this fixed for our customers and users; heavy users of Snipe-IT and our LDAP sync are the ones who are getting bit by this bug, and I would love to get this in people's hands before Thanksgiving (which is Thursday the 26th here in the US).

The change I made is pretty...uh....gross. I just back-ported (or forward-ported? I don't know which) our old LDAP sync script and one of the models that powered it from v4. It seemed to just work.

But I'd still love a little bit of testing on this, especially since we invested so much on getting the brand-new LDAP system to work - I'd hate to switch back to the 'old' system and have it not help our situation at all.

Thanks in advance for helping us out!

**Comment by uberbrady** [comment]
FYI - I've personally tested it against an Active Directory setup with more than a thousand users in it, and it *did* seem to work fine there. This code is, after all, pretty well battle-tested at this point.

**Comment by nilsrb** [comment]
Hi uberbrady,

we are using OpenLDAP and i tried this fix, because LDAP-Sync (and Login) is also not working on our side (https://github.com/snipe/snipe-it/issues/8617). Before using this fix i got Error 500. Now i changed these files and now i get ` Error: ldap_search(): Search: Bad search filter`. Tried to change the filter a few times, but it didn't work. The Test-LDAP-Sync button in ldap-settings works fine.

Best regards!

**Comment by snipe** [comment]
@nilsrb What version were you using before this pull request? All of the 500 errors were fixed in v5.0.9. This PR is addressing an issue we've only seen in Okta, but we obviously wanted to test that it doesn't break anything before. 

> Before using this fix i got Error 500

For which, login or sync?

Bad search filter usually means exactly that - the search filter is bad. (Make sure you're not using the outside parentheses in your search filter, per the v4 LDAP docs)

**Comment by nilsrb** [comment]
Hi snipe, 

thank you! The outside parentheses - exactly this was the problem :facepalm: 
I didn't check this, because the Ldap-Test did show me the 10 sample users, so i thought that the filter was fine :)

But the LDAP sync only works with this fix. I did update to v.5.0.9 before using this PR and it didn't work. Now i reverted this fix and tried again with correct LDAP filter and v.5.0.9 - again error 500:

```
[2020-11-25 10:12:49] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Argument 1 passed to App\Console\Commands\LdapSync::updateCreateUser() must be an instance of Adldap\Models\User, instance of Adldap\Models\Ent
ry given, called in /var/www/html/snipe-it/app/Console/Commands/LdapSync.php on line 245 in /var/www/html/snipe-it/app/Console/Commands/LdapSync.php:181
Stack trace:
[2020-11-25 10:12:49] production.ERROR: Argument 1 passed to App\Console\Commands\LdapSync::updateCreateUser() must be an instance of Adldap\Models\User, instance of Adldap\Models\Entry given, called in /var/www/html/snipe-it/app/Console/
Commands/LdapSync.php on line 245 {"userId":146,"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Argument 1 passed to App\\Console\\Commands\\LdapSync::updateCreateUser() must be an instance of Ad
ldap\\Models\\User, instance of Adldap\\Models\\Entry given, called in /var/www/html/snipe-it/app/Console/Commands/LdapSync.php on line 245 at /var/www/html/snipe-it/app/Console/Commands/LdapSync.php:181)
[stacktrace]
```

> For which, login or sync?

For both i get error 500.

**Comment by snipe** [comment]
@nilsrb I'm sorry, I'm confused (it's late here). 

So on this PR - the one where we restored the LDAP functionality back to v4's LDAP - it *did* work with the removed parentheses, correct?

> I didn't check this, because the Ldap-Test did show me the 10 sample users, so i thought that the filter was fine :)

Totally understand why you wouldn't. The LDAP test uses the *newer* LDAP sync stuff, which means the parentheses are fine there. We should at least update the Ldap Test method to work the same as the actual sync, otherwise it sorta defeats the purpose of the test. I'll make a note to that PR so we can make sure we normalize that between the two.

> I did update to v.5.0.9 before using this PR and it didn't work

That's weird, since all of the other LDAP issues were resolved in v5.0.9 as far as I know. (I believe you, just not sure why that would be the case.)

@uberbrady - I'm adding this note to the PR. Hopefully we can get this merged tomorrow.

I appreciate you taking the time to test this. Even if this works for Okta, we obviously don't want to break stuff for non-Okta people. Right now this is high priority, as many of our customers are encountering issues with Okta+Snipe-IT sync. :( 

The v5 LDAP PR was well-intentioned, but it's obviously impossible to test against every possible third-party LDAP/AD provider. I hate rolling back code, especially from outside contributors, but until we can get this sorted with Okta, we have to try this.

**Comment by nilsrb** [comment]
>  I'm sorry, I'm confused (it's late here).

Ok, but now i see that my text is also a litte bit confusing :smiley: 

> So on this PR - the one where we restored the LDAP functionality back to v4's LDAP - it did work with the removed parentheses, correct?

Yes.

> That's weird, since all of the other LDAP issues were resolved in v5.0.9 as far as I know. (I believe you, just not sure why that would be the case.)

Hmmm ok, that's really weird. But this PR was really helpful for us since now i am able to sync again (new employees were added and we can assign the assets we gave them the last weeks). Maybe i will try to use Keycloak for login (i wanted to do this anyway, but didn't have time yet) and we're happy.  If i can provide any more information, let me know (https://github.com/snipe/snipe-it/issues/8617).

Thank you and regards from Germany!

Nils

**Comment by snipe** [comment]
> Maybe i will try to use Keycloak for login

Ah, so with this PR branch, sync works but login doesn't?

**Comment by nilsrb** [comment]
> > Maybe i will try to use Keycloak for login
> 
> Ah, so with this PR branch, sync works but login doesn't?

Exactly. Login still gives me error 500.

**Comment by snipe** [comment]
@nilsrb Hmm... that should have been fixed in https://github.com/snipe/snipe-it/pull/8774. Is it ALL LDAP users who get a 500, or ones that try to login who are marked as "login disabled" within Snipe-IT?

**Comment by nilsrb** [comment]
My colleagues also get a 500 :(

The linked PR/Fix was about the `activated: 1` field, right?
Checked the database and for example my user seems to be `active`... 


```
MariaDB [snipeit]> select * from users where username="nils" \G;
*************************** 1. row ***************************
                 id: 1
              email: nils.b....
           password: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        permissions: {"superuser":1}
          activated: 1
    activation_code: NULL
       activated_at: NULL
...

```

**Comment by uberbrady** [comment]
That "need a `User`, got an `Entry`" error is a typing problem in PHP - it means that something you're doing is returning a non-User LDAP entry - perhaps a Computer, or some other LDAP-ey thing - but not a User.

It's not possible that you have some people and their computers having the exact same 'short name', is it? If so, I'd recommend to play around with the base DN, if there's anything more we can do there.

**Comment by nilsrb** [comment]
Hi uberbrady, 

checked this again with my colleague. We played around with LDAP filter, but i can't see what we could do to fix this. Our filter just returns user :(

**LDAP Log:**
```
Nov 27 08:02:12  slapd[1176]: conn=478753 fd=42 ACCEPT from IP=XXX.XXX.XXX.XXX:53308 (IP=XXX.XXX.XXX.XXX:636)
Nov 27 08:02:12  slapd[1176]: conn=478753 fd=42 TLS established tls_ssf=256 ssf=256
Nov 27 08:02:12  slapd[1176]: conn=478753 op=0 BIND dn="XXXXXXXXXXXX" method=128
Nov 27 08:02:12  slapd[1176]: conn=478753 op=0 BIND dn="XXXXXXXXXXXX" mech=SIMPLE ssf=0
Nov 27 08:02:12  slapd[1176]: conn=478753 op=0 RESULT tag=97 err=0 text=
Nov 27 08:02:12  slapd[1176]: conn=478753 op=1 BIND anonymous mech=implicit ssf=0
Nov 27 08:02:12  slapd[1176]: conn=478753 op=1 BIND dn="uid=christian,ou=people,dc=XXXXXXXXXX,dc=de" method=128
Nov 27 08:02:12  slapd[1176]: conn=478753 op=1 BIND dn="uid=christian,ou=people,dc=XXXXXXXXXX,dc=de" mech=SIMPLE ssf=0
Nov 27 08:02:12  slapd[1176]: conn=478753 op=1 RESULT tag=97 err=0 text=
Nov 27 08:02:12  slapd[1176]: conn=478753 op=2 SRCH base="ou=people,dc=XXXXXXXXX,dc=de" scope=2 deref=0 filter="(uid=christian)"
Nov 27 08:02:12  slapd[1176]: conn=478753 op=2 SRCH attr=*
Nov 27 08:02:12  slapd[1176]: conn=478753 op=2 SEARCH RESULT tag=101 err=0 nentries=1 text=
Nov 27 08:02:12  slapd[1176]: conn=478753 op=3 UNBIND
Nov 27 08:02:12  slapd[1176]: conn=478753 fd=42 closed
```

You can see that my colleague Christian was successfully authenticated and LDAP search found 1 result (nentries=1). But he can't login and gets a 500 error. When using a wrong password he gets an error on the login-page that the password is wrong, so this works fine. Something seems to be broken after the (successful) LDAP-login...
