### ISSUE TITLE
Syncing with AD

### ISSUE THREAD

**Issue by UserGoodtm** [grokability/snipe-it#8847]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
In the previous 5.0.9 version, user data was synced with AD - phone number, position, in the notes field the inscription Imported from LDAP. This data was updated every time syncing with AD was performed. In the current version 5.0.10, if you delete these records (phone number, position), they are not registered in the user properties after synchronization.

PS. Please develop a specific logic for working with AD. In the last version (5.0.9), syncing with AD erased all my entries in the user properties, in the "notes" field. Don't go from one extreme to the other.

**Comment by uberbrady** [comment]
We had to make some hard choices on the sync for 5.0.10. The version of LDAP sync we had before was very aggressive about mapping every single field, and that was good. But it also beat the crap out of LDAP servers, to the point where customers were being throttled by some LDAP providers. It caused severe failure-to-sync for our largest users and customers.

I think the correct solution here is to present additional mapping fields in the LDAP settings for **every** attribute that makes sense in Snipe-IT.

fwiw, @UserGoodtm , the old pre-v5.0.10 syncing logic is still available to you via Artisan, if you run `php artisan snipeit:ldap-sync-ng` - that may be the thing you want to schedule running periodically. But if you hit the 'LDAP sync' button, you'll still hit the new logic. That logic may still blow out notes fields though.

**Comment by sarang2502** [comment]
Hello @uberbrady and @snipe , 

Even we faced this issue, we saved a lot of things in notes section under users and now everything is replaced by "Imported from LDAP". More over now with the new LDAP in place I am unable to sync custom field for email:
As you can see here, the value comes as "null"
![image](https://user-images.githubusercontent.com/54850984/102933427-9b778e00-4478-11eb-9cad-d1ece4440d62.png)

I am able to get everything working as it was previously (except notes which I guess are lost now) by using `php artisan snipeit:ldap-sync-ng` command. 

Hope this is fixed in future releases. Thanks :)
