### ISSUE TITLE
SAML Debugging is very hard

### ISSUE THREAD

**Issue by uberbrady** [grokability/snipe-it#8853]
Two main problems I just ran into while troubleshooting this for a customer:

- If there is some kind of cert mismatch, we absolutely **must** show it in the logs, so the administrator can troubleshoot what's going wrong. This would've probably saved me a few days. This issue I was handling was probably related to #8852 .
- If the user actually correctly authenticated via SAML, but does not have a corresponding user in Snipe-IT, we should **definitely** show that in the logs, so the Administrator can correct the problem - probably a configuration problem on one side or the other, but definitely needs correction. Of course if the access is unwanted, the admin need not do anything. We **cannot** show the error to the end-user however; that would violate security.

**Comment by johnson-yi** [comment]
Hi uberbrady

SAML errors from onelogin/php-saml should be visible in the Debug Bar but you will need to change the dropdown bar to the request of the SAML endpoint where it happened which in this case is "/saml/acs". It can be missed in the Debug Bar since we redirect back to /login.

The Debug Bar should also be showing errors for when the SAML user cannot be found.

You can see the example of both situations [here](https://github.com/snipe/snipe-it/pull/8023#issuecomment-624291948).

**Comment by uberbrady** [comment]
Makes sense, and thanks for explaining that @johnson-yi ! This remains one of my favorite pull requests ever, thanks again so much for it. Our customers really love it.

One of the issues we have in a production environment is that we can't turn on the Debug Bar for customer instances, and we tend to not like to enable `APP_DEBUG` - these instances tend to face the internet so that's too much of a security risk. What I'd probably want to do is upgrade the Log messages from Debug up to something higher - maybe up to Error but definitely at least Warning.
