### ISSUE TITLE
Unable to Install using PHP 8

### ISSUE THREAD

**Issue by ajohnson6494** [grokability/snipe-it#8935]

**Comment by snipe** [comment]
Our suggestion for right now would be to downgrade PHP. I don't believe we've tested this on PHP8 yet.

@uberbrady have you tested installations at all with PHP8?

**Comment by uberbrady** [comment]
No, I haven't tested it at all. I suspect it may require a Laravel version bump though; I think Laravel only very recently got compatibility with PHP 8 working.

**Comment by fireballhh** [comment]
The First error can easy be solved by run composer update this will give you some yellow notices afther the update is finished:

Package doctrine/reflection is abandoned, you should avoid using it. Use roave/better-reflection instead.
Package patchwork/utf8 is abandoned, you should avoid using it. Use symfony/polyfill-mbstring or symfony/string instead.
Package fzaninotto/faker is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.

real problem starts when you try to generate the key

````
php artisan key:generate
PHP Fatal error:  Declaration of Doctrine\DBAL\Driver\PDOConnection::query() must be compatible with PDO::query(string $query, ?int $fetchMode = null, mixed ...$fetchModeArgs) in C:\inetpub\wwwroot\snipe-it\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php on line 81

In PDOConnection.php line 81:

  Declaration of Doctrine\DBAL\Driver\PDOConnection::query() must be compatible with PDO::query(string $query, ?int $
  fetchMode = null, mixed ...$fetchModeArgs)
```
`
so guess until this is fixed only way is to use php 7x

**Comment by nyamoga9** [comment]
I am having the same issue.  I update to php8 because some other projects needs it.  Is there a work around for the error?

PHP Fatal error:  Declaration of Doctrine\DBAL\Driver\PDOConnection::query() must be compatible with PDO::query(string $query, ?int $fetchMode = null, mixed ...$fetchModeArgs) in C:\inetpub\wwwroot\snipe-it\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php on line 81

In PDOConnection.php line 81:

  Declaration of Doctrine\DBAL\Driver\PDOConnection::query() must be compatible with PDO::query(string $query, ?int $
  fetchMode = null, mixed ...$fetchModeArgs)
```

**Comment by ajsy** [comment]
> I am having the same issue. I update to php8 because some other projects needs it. Is there a work around for the error?
> 
> PHP Fatal error: Declaration of Doctrine\DBAL\Driver\PDOConnection::query() must be compatible with PDO::query(string $query, ?int $fetchMode = null, mixed ...$fetchModeArgs) in C:\inetpub\wwwroot\snipe-it\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php on line 81
> 
> In PDOConnection.php line 81:
> 
> Declaration of Doctrine\DBAL\Driver\PDOConnection::query() must be compatible with PDO::query(string $query, ?int $
> fetchMode = null, mixed ...$fetchModeArgs)

same problem here

**Comment by ajohnson6494** [comment]
What version of doctrine/dbal are you using? It seems to be working on `"doctrine/dbal": "^3.0",`

**Comment by snipe** [comment]
@ajohnson6494 they would be using the one we specify in `composer.lock`. If you're running `^3.0`, I'm glad it seems to be working, but it also means you ran `composer update` which you should never do. We generate the `composer.lock` file so that we can be sure that all dependencies have been tested and accounted for, and you don't get stuck on an edge case bug because you happen to be three point releases ahead or behind in a particular library. You should only be running `composer install`.

**Comment by ajohnson6494** [comment]
@snipe Understood that for a normal install you would NOT run a composer update, but when trying to test out upgrading to support PHP8 you have to modify the composer.json file to update versions of dependencies to be compatible, which is the whole point of this issue.

**Comment by snipe** [comment]
@ajohnson6494 Yes, thank you, I'm aware of how composer works. My point is that telling people to mess with compose, especially if they're not developers and don't expect to be submitting PRs to increase compatibility, is bad news and will cause the other users and us a lot of headache. 

DBAL version 3 [requires at least PHP 7.3](https://packagist.org/packages/doctrine/dbal#3.0.0), which is higher than our minimum PHP requirement (which is why it's not been pulled forward yet.) We don't change PHP requirements outside of (typically) major releases or at the very least a minor release.

If you want to mess with composer.json, be my guest, but understand that it means our ability to help you with things moving forward will be greatly hindered if not impossible.

**Comment by ajohnson6494** [comment]
Why was this closed??? PHP 8 is still not working and is the current version.

**Comment by mfsid** [comment]
Snipe-IT works well with PHP 8.0.3 o XAMPP. The only problem I'm facing is LDAP Sync not working. It gives 500 Server Error.

![image](https://user-images.githubusercontent.com/61146540/117577688-a8032880-b09f-11eb-9d5f-003beda17fd8.png)

I enabled debugging and found out I'm having same errors in laravel.logs as mentioned in Issue #3319 

Do I need to downgrade my PHP Version?

**Comment by snipe** [comment]
I can’t answer that without knowing what the logs say, but either way it should probably be a new ticket. We’ve had many releases since the original ticket was closed.
