### ISSUE TITLE
LDAP Authentication not working "Unable to validate user credentials!"

### ISSUE THREAD

**Issue by AEN1337** [grokability/snipe-it#9063]
LDAP Synchronization and User import works flawlessly only the authentication isn't.

**Expected Behavior**

- Functioning login with LDAP user.

**Actual Behavior**

Not working.
Error message: Unable to validate user credentials!
![snipegit1](https://user-images.githubusercontent.com/31441147/106148815-ce98f580-6179-11eb-87cd-290162ec7d2a.png)
![snipegit2](https://user-images.githubusercontent.com/31441147/106148824-cfca2280-6179-11eb-9da5-cac2ee1483b8.png)
![snipegit3](https://user-images.githubusercontent.com/31441147/106148827-d062b900-6179-11eb-807d-e5127536c3cc.png)
![snipegit4](https://user-images.githubusercontent.com/31441147/106148828-d0fb4f80-6179-11eb-9f20-d00691709e51.png)

Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode

- [ ] I have read checked the Common Issues page

**Provide answers to these questions:**

    Is this a fresh install or an upgrade?
    Upgrade

    Version of Snipe-IT you're running: v5.0.13-pre build 5749 (gd19c6ab8e) 
    Last working version: None.

    Version of PHP you're running
    7.4.3 

    Version of MySQL/MariaDB you're running
    10.3.25-MariaDB-0ubuntu0.20.04.1

    What OS and web server you're running Snipe-IT on: Ubuntu 20.04 / Apache

    What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
    install.sh

    WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error

[13:54:38] LOG.debug: Preparing to test LDAP login
debuglog
[13:54:38] LOG.debug: Connection failed

    What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
    Login page and /admin/ldap

    Any errors that appear in your browser's error console.
   None

    Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
    No

    Include any additional information you can find in storage/logs and your webserver's logs.

 WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error (Test LDAP Synchronization)
`[13:56:41] LOG.info: Preparing to test LDAP user login
[13:56:41] LOG.info: Preparing to test LDAP bind connection
[13:56:41] LOG.info: Testing Bind
[13:56:41] LOG.info: Preparing to get sample user set from LDAP directory
[13:56:41] LOG.info: Testing LDAP sync`

EDIT: I have tried several different LDAP Authentication queries so far and none of them worked:

1. cn=
2. uid=
3. samaccountname=
4. uid=samaccountname
5. samaccountname=uid
6. sAMAccountname=
7. sambaSamaccount=
8. etc.

**Comment by andrew-mi** [comment]
We are running Snipe-IT on prem. (and so all the dns names are internal)
I was getting the same error as you.
Ticking "Allow invalid SSL Certificate" got it working for me. Not sure about the security implications, if someone is reading this shaking their head thinking that is a bad idea - please speak up.
This is my working configuration:
![image](https://user-images.githubusercontent.com/20514615/106387916-007ab800-6417-11eb-9a72-8f7c78bb356b.png)

**Comment by andrew-mi** [comment]
Clarification (because it is blurred)
LDAP Bind Username: domainname\username
and make sure to re-enter your Bind password as you change the username

**Comment by AEN1337** [comment]
@andrew-mi 

Thanks for your reply, unfortunately we are not running an AD just yet, so we cant bind that way.

**Comment by AEN1337** [comment]
A little addition:

I quickly set up a WIndows Domain and AD and lo and behold the login works flawlessly on the first try.
Still not quite sure why the LDAP authentication does not work with OpenLDAP and LDAP Account Manager.

**Comment by andrew-mi** [comment]
Ahh ok. Didn't notice you weren't using AD. Good luck resolving the issue.

**Comment by stbc** [comment]
Got a similar problem, maybe that is connected, see https://github.com/snipe/snipe-it/issues/9028 
I got the same error, when ticking the box "Append domain name to user name field" as we are not appending any domain-name to the username, so the error is valid. When switching that of, I got the error stated in the linked ticket... Thus no login besides local admin accounts is possible right at the moment... which is really annyoing!

**Comment by adm-romanb** [comment]
Hi,
I've got same problem, snipeit 5.1.3 or 5.1.4 (ubuntu 20.04, docker image) can't auth ldap users. Every time I try 'Test LDAP Login' I get Unable to validate user credentials!
I've tried various option combinations, nothing works.
![snipeit_ldap_problem](https://user-images.githubusercontent.com/28982232/113423515-47653980-93d7-11eb-9269-ab46642479d0.jpg)

I checked ldap server logs and found next:
`Apr  2 08:44:18 ldap1 slapd[10915]: conn=3350563 fd=57 ACCEPT from IP=x.x.x.x:36156 (IP=0.0.0.0:636)
Apr  2 08:44:18 ldap1 slapd[10915]: conn=3350563 fd=57 TLS established tls_ssf=256 ssf=256
Apr  2 08:44:18 ldap1 slapd[10915]: conn=3350563 op=0 BIND dn="cn=readonly,dc=company,dc=com" method=128
Apr  2 08:44:18 ldap1 slapd[10915]: conn=3350563 op=0 BIND dn="cn=readonly,dc=company,dc=com" mech=SIMPLE ssf=0
Apr  2 08:44:18 ldap1 slapd[10915]: conn=3350563 op=0 RESULT tag=97 err=0 text=
Apr  2 08:44:18 ldap1 slapd[10915]: conn=3350563 op=1 BIND anonymous mech=implicit ssf=0
Apr  2 08:44:18 ldap1 slapd[10915]: conn=3350563 op=1 BIND dn="uid=user,ou=People,dc=company,dc=com" method=128
Apr  2 08:44:18 ldap1 slapd[10915]: conn=3350563 op=1 RESULT tag=97 err=49 text=
Apr  2 08:44:18 ldap1 slapd[10915]: conn=3350563 op=2 UNBIND
Apr  2 08:44:18 ldap1 slapd[10915]: conn=3350563 fd=57 closed
`
 The problem is that openldap can't manage _BIND **dn="uid=user**,ou=People,dc=company,dc=com"_, it must be only _BIND **dn="cn=fullname**,ou=People,dc=company,dc=com"_
If I change _Username Field_ to _cn_ from _uid_ and change _LDAP Authentication query_ to _cn=_ from _uid=_ LDAP auth starts to work, but I have to use my fullname to login instead of username. Which obviously isn't an option for us.

**Comment by sunflowerbofh** [comment]
Our ldap does work with BIND dn="cn=<uid>,ou=...,ou=...dc=ourdomain". So the solution for us is to use ou=...,ou=...,dc=ourdomain as Base Bind DN and cn=* as LDAP Authentication query. The problem is, if you have 2 users from different ldap trees (ou=Students,ou=Accounts,dc=ourdomain and ou=Staff,ou=Accounts,dc=ourdomain) this won't work. You have to decide which user group to give ldap access to. 
In a well-programmed application it should be enough to enter "dc=ourdomain" as BindDN and the ldap client would find out the bind dn for the user. Further details can be found here:
https://github.com/snipe/snipe-it/issues/9410#issuecomment-900918762

**Comment by snipe** [comment]
> In a well-programmed application it should be enough to enter "dc=ourdomain"

I welcome your pull request.

**Comment by gerhag** [comment]
Hi the issue described by @sunflowerbofh, although it could have been described in a more kind manner, still remains in Snipe-IT v5.2.0. The current authentication process isn't designed to handle LDAP users in different sub-tree's, which is a very common thing in most LDAP-Directory's.
Looking into the Snipe-IT v6 roadmap, I've seen that a rewriting of the LDAP system is planned, so my question would be if the rewriting regards this issue ?

**Comment by tuantran92** [comment]
![image](https://user-images.githubusercontent.com/29625506/166898508-805cfa6c-1d95-42da-91fd-b9ae58e1f25e.png)

Tick "Append domain name to username field" got it working for me

**Comment by sunflowerbofh** [comment]
Obviously the latter setting only works for AD. I finally managed to create a patch for having username, dn and LDAP search base independent. For having a issue number I will re-open that again.
