### ISSUE TITLE
Paid customization service

### ISSUE THREAD

**Issue by yanagha** [grokability/snipe-it#9302]
Hi, 

Do you have paid customization service? If yes, please let me know the pricing. 

Thank you!

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by snipe** [comment]
Because of our license, any changes we would make for you would also have to be released to the general community. While we don't exactly offer paid services, we evaluate every feature request on how valuable it could be to the product overall. 

If you can give us a better idea of what specifically you're looking for, we can narrow it down to something we can potentially add to the product, or something one of our community members might be able to do for you. (Remember though, any code changes need to be released to the public.)

**Comment by yanagha** [comment]
Hi @snipe , 

Thank you for your reply. 

We would like to check out more than one assets and accessories at the same time.
For example, we have 100 keyboards and computers in the storage and we want to assign 50 of them to a location computer lab or to the person who is responsible for the lab. We need to click the checkout button 50 times. 

https://github.com/snipe/snipe-it/issues/9247

**Comment by snipe** [comment]
That's on the short term roadmap
