### ISSUE TITLE
liveware support?

### ISSUE THREAD

**Issue by zachary** [grokability/snipe-it#9393]
Since the liveware only supports laravel 7, so does it support liveware?

thanks

**Comment by snipe** [comment]
I think you just answered your own question... Snipe-IT v5 runs Laravel 6, so, we can't support LiveWire yet. Once we pull everything forward to Laravel 7+, we will be switching to LiveWire for a lot of our stuff, but we have to wait until we're ready for a Snipe-IT major point release, since the PHP version requirement will have changed.
