### ISSUE TITLE
Cannot Specify Single License to User or Asset. 

### ISSUE THREAD

**Issue by AbhimanyuNeupane** [grokability/snipe-it#9453]
**Server (please complete the following information):**
 - Snipe-IT Version v5.1.4 build 5886 (g9f3a8a43c)
 - OS: Windows Server 2016
 - Web Server: IIS
 - PHP Version 7.4.13

**Is your feature request related to a problem? Please describe.**
-> Yes. We are having issue assigning license to asset or user. Lets say we have 3 key of Adobe Reader and we need to assign to user. We are not able to track which user is using which key. Tracking of the key is hard.

**Describe the solution you'd like**
In Checkout License Seat, If serial have drop down list of key than we can assign specific serial to specific user or asset. After that we can track which user or asset are using which key.

**Describe alternatives you've considered**
I am new on snipe-it don't have any alternative :( 
Searching for it.

![Capture](https://user-images.githubusercontent.com/38075836/115394571-a06c0480-a202-11eb-99b2-e038f474ba56.PNG)
![Capture3](https://user-images.githubusercontent.com/38075836/115394604-aa8e0300-a202-11eb-85ac-267446e066ea.PNG)
![Capture5](https://user-images.githubusercontent.com/38075836/115396474-be3a6900-a204-11eb-84f6-9e589e01d0bb.PNG)

As we can see user have 2 license Microsoft Office and adobe and have all key assign to them. We need to assign only one key to the user. Why should we assign 2 key of same application for one user?

**Comment by boring10** [comment]
I believe that the intent of the license is to have a single product key for each license instance. There are some licenses that you can use the same product key for multiple installs (multi activation key (MAK) or site licenses) so you would have more seats for a single product key.

In your case, it sounds like you only have individual keys so you would want to create a new license for each product key with a single seat and then checkout to the use. This would link the product key for the user/asset so you know which product key was used more easily.

**Comment by AbhimanyuNeupane** [comment]
Lets say example. I have brought 10 license of MS Office  and i want to assign to the user. There are multiple key for same product. I have difficulties assigning them. As you can see on previous image on 'Checkout License Seat' there are all key. 
I want to assign only one key to one user so that i can track what and which key has been used for whom.

**Comment by boring10** [comment]
So in this case, you purchased 10 individual licenses of MS Office so you would actually create 10 separate instances of MS Office licenses on Snipe-IT each with a different product key and only a single seat available.

![MS Office Individual Product Keys](https://user-images.githubusercontent.com/35600612/115517082-c621f980-a254-11eb-864e-2c54670f6d1a.png)

![Microsoft Office Individual Product Keys](https://user-images.githubusercontent.com/35600612/115517110-ccb07100-a254-11eb-891c-ea8deba84977.gif)

You can create a single license with all of the information in it and then use the action button on the right to duplicate it (blue button) and change the product key for each instance that you duplicate.

![MS Office - Duplicate](https://user-images.githubusercontent.com/35600612/115518796-9673f100-a256-11eb-8351-daa659f10a88.gif)

---

The reason that you can have more than one seat for a single license is, for instance, Microsoft offers volume licenses that use a single key and can be used multiple times (Multiple Activation Key (MAK) - <https://docs.microsoft.com/en-us/deployoffice/vlactivation/activate-office-by-using-mak>). In this case you would have a single product key that can be used on more than one user/asset (seats) depending on the license agreement. That means that all of the users/assets that are assigned the license would actually use the same product key.

![MS Office Volume License](https://user-images.githubusercontent.com/35600612/115517902-a6d79c00-a255-11eb-9115-6c5a0719847e.png)

Other software companies have similar types of agreements as well since a medium to large business would not want to purchase 1000 separate license keys to manage for the users/asset. These license agreements can usually be done through a 3rd party vendor. For instance, we only have 19 licenses of MS Office for our office staff but have a volume license agreement so that we only need to use a single product key with 19 seats available. It's then our job to ensure that we assign the license appropriately to avoid violating the license agreement.

Does that make sense?

<blockquote><img src="https://docs.microsoft.com/en-us/media/logos/logo-ms-social.png" width="48" align="right"><div><strong><a href="https://docs.microsoft.com/en-us/deployoffice/vlactivation/activate-office-by-using-mak">Activate volume licensed versions of Office by using MAK - Deploy Office</a></strong></div><div>Provides Office admins with information about using Multiple Activation Key (MAK) to activate volume licensed versions of Office 2019 and Office 2016, including Project and Visio.</div></blockquote>

**Comment by AbhimanyuNeupane** [comment]
Ok i understand this. but in case of other application where we have different key for all user. Then how can we assign key ? how can we assign individual key to individual user?
We need to track which key is assigned to which user. if this feature is added then it will help not only MAK key it will also help to mange other application key.

**Comment by boring10** [comment]
The only way to assign an individual key to a single user is to create a new instance of the license for each key. For instance, let's say that the keys listed below are the individual keys for Adobe Reader.

- Key 1: 1111
- Key 2: 2222
- Key 3: 3333

If the purchase information is the same for all 3 of these keys then you can create a single license with 1 seat available and assign a product key to that license (ie. key 1 above). You can then duplicate that license and place add the product key (ie. key 2). I'm not saying that this is a clean solution but it does allow you to more easily track who is using what license.

See below for a GIF walk-through.

![Peek 2021-04-24 08-11](https://user-images.githubusercontent.com/35600612/115958348-18714d80-a4d5-11eb-8036-7f0dd461c634.gif)
