### ISSUE TITLE
Snipe IT composer install

### ISSUE THREAD

**Issue by rvidhy** [grokability/snipe-it#9488]
![image](https://user-images.githubusercontent.com/83179963/116002639-4a95c300-a62d-11eb-85f4-a770fee28b4f.png)

**Server (please complete the following information):**
 - Snipe-IT Version 5.1.4
 - OS: Windows server 2019
 - Web Server: IIS
 - PHP Version 7.4.16

I get this error message popping up even with the PHP8.0 installed.
Even the composer update fails
![image](https://user-images.githubusercontent.com/83179963/116002768-d871ae00-a62d-11eb-9543-b1cf37e55d72.png)

Is there any resolution for this

**Comment by snipe** [comment]
It's telling you what's wrong - permission is denied. It does not have permission to write the directory to create a `vendor` directory. 

You should not be using `composer update`, but if your permissions are busted, it would make sense that you'd see the same thing.

**Comment by athompsoncmc** [comment]
Hi, did you ever fix this? 
I'm doing a migrate to a new server and I'm receiving this error from composer when trying composer install. When I moved the ComposerSetup to the SnipeIT folder, I did not run it for all users (admin), because I made that mistake before and it messed things up on my old server where I had to run all commands on the local admin profile. I've also checked my permissions and they are as follows:
SnipeIT\Uploads - IUSR Full Control
SnipeIT\Bootstrap\cache - IUSR Full Control
SnipeIT\Storage - IUSR Modify
Windows\Temp - IUSR Modify

I've already copied over my old env file (changed the appkey to ChangeMe) and imported the mysql database. I thought one of those might be the issue because they come after installing Snipe-IT on the "Moving Snipe-IT" article, so I changed the env file back to the example one. Same issue. 
Any advice on what I'm doing wrong or what you did to fix this error?
Any advice?

**Comment by athompsoncmc** [comment]
> Hi, did you ever fix this? 
> 
> I'm doing a migrate to a new server and I'm receiving this error from composer when trying composer install. When I moved the ComposerSetup to the SnipeIT folder, I did not run it for all users (admin), because I made that mistake before and it messed things up on my old server where I had to run all commands on the local admin profile. I've also checked my permissions and they are as follows:
> 
> SnipeIT\Uploads - IUSR Full Control
> 
> SnipeIT\Bootstrap\cache - IUSR Full Control
> 
> SnipeIT\Storage - IUSR Modify
> 
> Windows\Temp - IUSR Modify
> 
> 
> 
> I've already copied over my old env file (changed the appkey to ChangeMe) and imported the mysql database. I thought one of those might be the issue because they come after installing Snipe-IT on the "Moving Snipe-IT" article, so I changed the env file back to the example one. Same issue. 
> 
> Any advice on what I'm doing wrong or what you did to fix this error?
> 
> Any advice?

I changed my SnipeIT directory's permissions for my user profile's to modify. I don't believe I had this issue before because I was installing as a local admin and not a domain admin. Thanks!

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
