### ISSUE TITLE
Upload/Delete Asset Image via API

### ISSUE THREAD

**Issue by athc0** [grokability/snipe-it#9594]
**Server (please complete the following information):**
 - Snipe-IT Version v5.1.2-pre - build 5831 (develop)
 - OS/Web/PHP: Hosted by Snipe-IT

**Is your feature request related to a problem? Please describe.**
I need to be able to delete images from a large number of assets but am not able to via the API.

**Describe the solution you'd like**
An option to upload and/or delete images via the API.

**Describe alternatives you've considered**
Getting a list of all assets and manually editing each one to delete the images.

**Comment by PetriAsi** [comment]
This would be a great and really useful feature. It would make maintaining model and other information easier. 

Api currently accepts only json formatted data. While uploading  images with json is technically possible,  could it be simpler to change api to allow also request with contenttype multipart/form-data.  

If this get implemented in snipe api , I'll write SnipeitPS support for image modifications.

**Comment by PetriAsi** [comment]
There related issue #9483 about assign images via api.

**Comment by PetriAsi** [comment]
I'm currently preparing PR  for api image uploads and removals.

My current code handles multipart/form-data requests . That would make uploading images easy. As  there's already ImageUploadRequest class that can be used for updating images and image removes.  So no need to maintain duplicate code
for api images handling. Post request are working without anything special, but PUT and PATCH will require additional '_method' attribute containing request method.  That's due to how php/laravel handles multipart requests.

@athc0  While working on PR  that I saw that assets already supports setting images via api  with 'image_source' value have to be base64 encoded and prefixed with header 'data:image/png;base64,....' like inline images inside html code. You can use that to set images.
