### ISSUE TITLE
SnipeIT API Not Showing All Accessories Checked Out

### ISSUE THREAD

**Issue by mtanabe8** [grokability/snipe-it#9605]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I'm using Google Apps script to make JSON requests to our SnipeIT server's API in order to display accessories on a Google Sheet. When I use the "/accessories/:id/checkedout", for a certain accessory, I only get 50 out of the 97 accessories I have checked out to come from the API. The response shows "total: 97", but only has 50 entries in "rows".

**To Reproduce**

**Expected behavior**
I would like all 97 accessories to display not just 50.

**Screenshots**
https://drive.google.com/file/d/1GCMPVGbMOW-OMYBZN7NoDDX7BpjMSw45/view?usp=sharing, https://drive.google.com/file/d/1hVbtCLFm16jBTqAf1fKl7MW3y2L_9wqQ/view?usp=sharing

**Server (please complete the following information):**
 - Snipe-IT Version 5.15 - build 6055
 - OS: Ubuntu v1804
 - Web Server: Apache
 - PHP Version 7.2.24-0ubuntu0.18.04.7

**Desktop (please complete the following information):**
 - OS: Windows 10 v2004
 - Browser chrome
 - Version 90

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include the output from `php -m` (this should display what modules you have enabled.)

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by boring10** [comment]
The API doesn't explicitly state that there is a limit parameter available for "accessories/:id/checkedout" but the default is 50 and the max is 500. In order to get more than 500 you will need to do some pagination. Basically, you will need to make a single call with a limit of 500 and, on that first request at least, get the total number of rows. From there you can then use the offset to continue to pull batches of up to 500 at a time and then bundle it all together for the output.

if you were to use a limit of 500 then you would get your, in this case, 97 results. The limit just states the max number of results to return but will return fewer if there are not 500.

Parameters that are available for the "accessories/:id/checkedout".
- limit: Specify the number of results you wish to have returned (ie. 1, 10, 25, ..., 500) <- 500 is the limit and then you must use the offset for a pagination effect.
- offset: Number of results to offset by (ie. 500, 1000, 1500, etc)
- order: Specify the order [asc | desc]
- sort: The fieldname to sort by (ie. id, name, username, etc.) <- The ability to sort by some fields depends on the API endpoint sometimes but usually you can end up sorting by the majority of fields that would make sense.

**Comment by mtanabe8** [comment]
Thank you, I got it to work! Those parameters weren't listed in the API guide.

https://snipe-it.readme.io/reference#accessoriesidcheckedout

Thanks again!

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/reference#accessoriesidcheckedout">Overview</a></strong></div><div>Snipe-IT is a free, open source IT asset management system. Features include management of assets, users, licenses, accessories, consumables and components, as well as two-factor authentication, LDAP/AD syncing, and asset acceptance confirmation.</div></blockquote>
