### ISSUE TITLE
Users cannot log in with a new LDAP password

### ISSUE THREAD

**Issue by UserGoodtm** [grokability/snipe-it#9628]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Users cannot log in with a new LDAP password

**To Reproduce**

**Expected behavior**
The program is configured to connect to LDAP. User passwords in LDAP change at regular intervals. It turned out that after the last update of the program, users can not log in with a new LDAP password. Users can only log in with their old, previous password. The tips from the Common Issues page didn't help.

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version v5.1.5 
 - OS: [e.g. Ubuntu, CentOS] CentOS
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version  7.4.16

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] All
 - Version [e.g. 22] Last

**Smartphone (please complete the following information):**

**Error Messages**

**Additional context**
- Is this a fresh install or an upgrade? upgrade
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh

**Comment by UserGoodtm** [comment]
After upgrading to 5.1.6, the situation has not changed. Users still can't log in with the correct (new, last) password. They can log in under the previous password. Developers, please pay attention to the request and give an answer on how to solve the problem.

**Comment by uberbrady** [comment]
I don't know how much of this is a _cultural_  or _language_ issue, or if you're just an actual jerk, but you're definitely coming across that way. You get this product for **free**. We try our best - alongside our community - to support it. If you don't learn this lesson for us on this product, at least learn it for other software that you get at absolutely zero cost. We don't owe you our time, or energy, and neither do they. And you'll get much better help if you are nice, and you'll make lives better for the people who give you software for free. Going forward, if you open new issues where you sound like a jerk, I'm going to close them and lock them. You will then be free to open a new one where you can try again.

Now, onto your issue. If LDAP is only allowing 'old' passwords, not new ones - then your LDAP connection is broken. You must be using the Password Sync feature, which worked with the old passwords (and, then, cached those passwords). That's why they still work. If you go into the 'test login' boxes in the LDAP settings I suspect you're going to find that none of your users will be able to pass the test box correctly.

Usually when we see an LDAP configuration suddenly 'break' it's either the TLS certificate expired, or, if you're using LDAP sync, that your LDAP service user's password has either expired or has been changed by someone else in the organization.

**Comment by UserGoodtm** [comment]
Thank you for reminding me that I use a free product. I did not allow such rude statements in the direction of the developers. I didn't touch on the language and culture of the developers. I respect the work of developers. I just wanted to draw attention to my problem, as it concerns not only me, but everyone who uses this program, including those who use it on a paid basis. We can say that we are free testers, but no one says "thank you"to us for this. Your rude answer shows your cultural level, which is probably not at a high level. Let's stay within the bounds of decency. Thank you for your technical response.

**Comment by UserGoodtm** [comment]
Synchronization is successful, and new users are created. The user with the rights to synchronize with AD has a permanent password that does not expire. Checking the synchronization settings for this user passes without problems. The problem is with users whose password changes every 90 days.

**Comment by UserGoodtm** [comment]
I found a solution to the problem

**Comment by snipe** [comment]
> Developers, please pay attention to the request

implies that we are normally NOT paying attention to requests, whereas we clearly are. 

@UserGoodtm I think your response has just proved @uberbrady's point. 

> Your rude answer shows your cultural level, which is probably not at a high level. 

Listen, we've been down this road with you before. When the developers think you're being rude, maybe take a moment with your "cultural level" and figure out how you can rephrase. Countering a complaint about how we feel you're being a little rude with a ruder response seems to be the opposite of the reaction you should be shooting for - not to mention it's going to make us not exactly want to jump through hoops to help you (even though @uberbrady graciously tried to anyway.)

I've tried to explain why you keep rubbing us the wrong way when you open issues (not even mentioning opening 20 in a day), but it doesn't seem to sink in. Do better.
