### ISSUE TITLE
Where are SAML settings for v 4.9.3?  

### ISSUE THREAD

**Issue by rootla** [grokability/snipe-it#9635]
Hi-

Cannot locate info in any changelog re:when SAML config options were added.  Running v4.9.3 build 4395 (g9a2440dc4) docker container and do not have SAML or any SAML options under admin tab as noted here:https://snipe-it.readme.io/docs/saml.   Was SAML added since v4.9.3 build 4395 (g9a2440dc4)?  I cannot locate any clear indication in any change log that clearly states "added SAML" or anything comparable.  Please advise. 

Yours,
Larry

**Comment by snipe** [comment]
SAML was not available in 4.9.3, IIRC. I believe it was released in the stable release of v5.0.0, with [the first SAML commit](https://github.com/snipe/snipe-it/commit/c3d8024e1fc80982f7408fa590418df8e4ed9181) being in [v5.0.0-beta-3.0](https://github.com/snipe/snipe-it/releases/tag/v5.0.0-beta-3.0).

**Comment by rootla** [comment]
Thank you for the quick reply.  I think it would be useful to clearly identify in changelogs which version was the first to include SAML- unless I missed it(?).  Thanks again!

Yours,
Larry

**Comment by snipe** [comment]
We do have it in the v5.0.0-beta-3.0 changelog (linked above), but GH search isn't always super great about letting folks filter through <del>changelings</del> changelogs (seriously, autocorrect?) easily. It's always a toss-up, since we like to have very clear, descriptive and complete changelogs (which means they're a little on the verbose side), but also making major features visible can be difficult. :(
