### ISSUE TITLE
UI Update/Redesign

### ISSUE THREAD

**Issue by fordster78** [grokability/snipe-it#9713]
I'm currently in the process of redesigning the look of Snipe-it, using the develop-v6-integration branch.

Would you be interested in a PR once this has been done @snipe ?

It is going to be using the following:
Tailwindcss
AlpineJS
Livewire
Blade Components

And the look/feel will be something similar to this screencast by Adam Wathan:

https://youtu.be/6xgMkGMIudE

Any feedback or suggestions on what you would like me to add are welcome.

**Comment by snipe** [comment]
I... I honestly don't know how to answer this. We specifically decided against using a TALL stack because we don't like it very much, and it's more limited (currently) than Boostrap. We've used Tailwind. It's fine - but why break what isn't broken? We're already working towards transitioning a lot of our javascript into Livewire (and we're super excited about it), as I'm sure you noticed in the integration branch's composer file. 

On a personal level, it's kind of hard for me not to take this kind of personally? Having someone effectively decide that my 8 years of UI work on this project isn't adequate and they can do better is a little insulting, whether you mean it that way or not. At that point, why not just make your own asset management software and leave Snipe-IT as it is? "I love it, except for every single part of how how it looks and behaves!" I just can't imagine anyone trying to "redesign" Snipe-IT without working with me ENORMOUSLY closely. I have opinions on how this software should work, and those opinions have treated us pretty well so far, if I may say so. Not to mention that I'm already working on some UI improvements on that integration branch, so... 

It's open source, so you can do what you like - and I guess I'd look at a PR when you were done, but it seems a little bonkers to me.

**Comment by fordster78** [comment]
OMG. I am so sorry @snipe 
I never intended to insult you or the software. It is an amazing app and purely wanted to help.

I not very good at design and blog posts i've read say to redesign a site that inspires you. Snipe-it is that site.

If I managed to redesign it in such a way that fit with your vision then I wanted to do that. That was my intention of this post so I didn't move away from that vision.
