### ISSUE TITLE
The mac address format is invalid.

### ISSUE THREAD

**Issue by itsluzby** [grokability/snipe-it#9731]
Hello
firstly thanks for very nice and useful tool.

Why all of these formats are invalid?

`01:02:03:04:ab:cd`
`01-02-03-04-ab-cd`
`01.02.03.04.ab.cd`
`0102:0304:abcd`
`0102-0304-abcd`
`0102.0304.abcd`
`01020304abcd`

Browser: Chrome version 91.0.4472.114 (Official Build) (64-bit)

Same thing happen in official demo and in my fresh installation.
Snipe-IT v5.1.6 build 6109 (gace7abc1a)
PHP 7.4.3
Laravel 6.20.28

**Comment by boring10** [comment]
The first two should work. They both worked on demo https://develop.snipeitapp.com.

Make sure that you don't have a leading or trailing space when using the MAC address format.

<blockquote><img src="https://develop.snipeitapp.com/favicon.ico" width="48" align="right"><div><strong><a href="https://develop.snipeitapp.com/">Snipe-IT Asset Management Demo</a></strong></div></blockquote>

**Comment by inietov** [comment]
As @boring10 noted, the first 2 forms in your examples does work. For the others... they are supported MAC addresses formats, but they aren't expressed in the example regex we provide. If you want them to be supported in your install, you should tweak the custom field's regex.

**Comment by mutawa19** [comment]
@boring10 
I have the same issue and I tried to test the demo site and got the same error.
![image](https://user-images.githubusercontent.com/57601023/223232797-655f4cd8-409a-446b-9a70-fb4bd97b6b52.png)


Here is the MAC I used to test: ‪B0:4G:13:05:83:1C

**Comment by marcusmoore** [comment]
Hi there @mutawa19,

I don't think `B0:4G:13:05:83:1C` is a valid mac address since `G` is outside of the supported range right?

**Comment by mutawa19** [comment]
@marcusmoore 
I did change few things because I didn't want to publicly list my MAC address. That `G` was one of the characters I changed. 
I did some farther testing and I think the issue was that I copied the MAC address from the text file exported from windows "System information" tool. For some reason, there is and invisible space before the `B`. Even though I tried to delete this leading space, which I couldn't see to delete anyway, doing so does nothing. 

I wrote a Java code to compere the manually typed string vs the copied one. The code detects and invisible leading space for some reason. I still don't know why this is happening.

It would be nice if you the developers add a trim function to the code for this textbox so it can clean the leading spaces before sending this to the DB. 

![image](https://user-images.githubusercontent.com/57601023/223275119-ccaf7cf5-e391-4f11-8869-6f3f2dd9caab.png)

**Comment by marcusmoore** [comment]
@mutawa19 
Ah invisible characters are always fun 😅

Trimming input before storing is a valid request. I'm hesitant to open a PR that makes that change, even though it makes sense to me, due to the chances of it breaking _someone's_ workflow _somehow_. The app doesn't use Laravel's `TrimStrings` and I have a feeling that is for a reason. But you're free to open a new issue so it can be discussed.

**Comment by mutawa19** [comment]
@marcusmoore 
I am not familiar with the process here. In fact, I don't even think that trimming would solve the issue. I tried to print the length of the trimmed string in Java and it still gives me 18 characters when it should be only 17 (including the charAt(0)). 

Opening the text file VS code editor reveals that there is a `‪[U+202A]` before the MAC address I am trying to copy. 
I just thought I should mention this here incase someone has the same issue or maybe for the developers to try and truncate the string in this textbox. I don't know. 

![image](https://user-images.githubusercontent.com/57601023/223288142-11ecc5fa-de6c-4301-81b1-dc29dcabb921.png)

**Comment by marcusmoore** [comment]
@mutawa19 no worries and thank you. I appreciate you sharing your process to help anyone in the future that might have the same issue! 😄
