### ISSUE TITLE
API key screen and import screen are blank

### ISSUE THREAD

**Issue by Woebenskie** [grokability/snipe-it#9743]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I can't generate an api key, the option doesn't show up under personal api keys but the user has the permissions.
**To Reproduce**
1. Go to top right: user
2. Click on manage api keys
and there are no keys to manage
![afbeelding](https://user-images.githubusercontent.com/42571709/123293997-bce33080-d514-11eb-8a30-9a6bc809ec2f.png)

**Expected behavior**
To manage and create api keys in that location
**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/42571709/123294058-cbc9e300-d514-11eb-9a8d-f5f83399941e.png)

**Server (please complete the following information):**
 - Snipe-IT Version v5.1.7 - build 6136 (master)
 - OS: [e.g. Ubuntu, CentOS] Debian 10.10
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version 7.4.16

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 21H1
 - Browser [e.g. chrome, safari] chrome as well as firefox
 - Version [e.g. 22] chrome: 90.0.4430.212 firefox: 89.0

**Error Messages**
No error message

**Additional context**
- Is this a fresh install or an upgrade? upgrade
- What OS and web server you're running Snipe-IT on Debian 10.10
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh
- Include what you've done so far in the installation, and if you got any error messages along the way. tried to clear cache as written in the common issues.
- Indicate whether or not you've manually edited any data directly in the database NO

None

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by UserGoodtm** [comment]
I confirm that in the 5.1.7 version, I have the same problem. There was no such problem in 5.1.6.

**Comment by Woebenskie** [comment]
Just to verify I did a clean install on 5.1.7 with the same specs as above and it is the same issue

**Comment by cmoore-mayesh** [comment]
Can also confirm -- was working fine under 4.8.0 when I upgraded to 5.1.7.  My installation is an upgrade from 4.8.0 -> 5.1.7.

Not sure if it will assist in diagnosis:
Snipe-IT versionv 5.1.7 build 6136 (gbc0c88781)
PHP Version 7.2.24-0ubuntu0.18.04.7
Laravel Version 6.20.29

**Comment by snipe** [comment]
Hmm - we didn't make any changes to that stuff recently, so I'm not exactly sure what might be happening here... 

Did you try the usual stuff? Clearing your browser cache+cookies, and 

```ssh
composer dump-autoload
php artisan cache:clear 
php artisan config:clear
php artisan route:clear
php artisan dugbar:clear
php artisan event:clear
php artisan view:clear
php artisan optimize:clear
php artisan clear-compiled
```

**Comment by snipe** [comment]
Update: I can confirm this on a production instance - please stand by, We'll have a fix out shortly.

**Comment by snipe** [comment]
It's not you, it's us. It looks like the last time we did an asset build via `npm run prod`, something silently failed in that process. I desperately wish it wouldn't - I want that to be a glaring, bright red banner that loudly proclaims "Yo stuff is donked!", but it just quietly let the build run, and that broke the bits that utilize Vue.js. (We rebuilt assets in v5.1.7 to fix a small visual bug in the yellow skin for dark mode, but I'm still not sure how that would have broke Vue... sigh.)

I think what likely happened here is that since we've been working on v6, which uses a different version of npm, node modules, composer *and* mix, something from v6 got sucked in and quietly failed. 

We're on it tho. Should definitely have a fix out in the next few hours.

**Comment by snipe** [comment]
Okay, this fix is out on master now. We're still scratching our heads over how this happened, and our build pipeline is kinda messed up right now. I basically just snatched the JS file from 5.1.6, since we knew that was a working version, but building assets locally is still failing for me and @uberbrady. We'll sort through the larger issue in the next day or so, but at least we've got the immediate issue fixed. 

Again, pretty sure this is a symptom of working on v6 and v5 at the same time - there's got to be something weird that's cached somewhere and is making things act wonky. But, at least v5's Vue screens are back up and running now. 

My apologies for the bug. We're working on stripping Vue out in v6 to simplify our asset building moving forward. :(
