### ISSUE TITLE
Labels Are Not Generated The Correct Size

### ISSUE THREAD

**Issue by MGPlunk** [grokability/snipe-it#9851]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When we print labels we have a label sheet that is a 48 page grid of labels (4 by 12) that can be run through a regular printer. I have configured Snipe IT with the correct dimensions for the labels. When printing them they are either too small or too big, along with the margins being off for where they should be located.

I have tried changing the margin settings in Google Chrome to either match the label margins or setting it to 0 to see if Snipe will sort out the margins, but none of them work.

The labels are Avery brand and are code: L4778

**To Reproduce**
1. Go to label settings
2. Adjust all the margins as per the specifications of the labels
3. Select 48 devices and click generate labels
4. The produced labels will not be the correct size when printed

**Expected behavior**
Labels are printed with the correct margins so they match the label positions

**Screenshots**
![labels_cr_draw](https://user-images.githubusercontent.com/87833340/126713835-bf72ba07-fa99-4038-8b20-980f503039e4.jpg)

**Server (please complete the following information):**
Hosted by Snipe IT: v5.1.8 - build 6148

**Desktop (please complete the following information):**
 - OS: Windows 10 - 21H1 (19043.1110)
 - Browser Chrome
 - Version 92.0.4515.107

**Error Messages**
N/A

**Additional context**
- Is this a fresh install or an upgrade?
- Brand new instance

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by aHVzY2g** [comment]
@MGPlunk where you able to solve it, I have the exact same problem with similar labels Avery L6009?

**Comment by MGPlunk** [comment]
@aHVzY2g we gave up and are just using Word with a plugin to generate and print the labels.

If there is a fix though, I would be interested.

**Comment by Kaphalor** [comment]
@MGPlunk can you share how you managed it?
I also have issues regarding the L6009 Labels

**Comment by MGPlunk** [comment]
> @MGPlunk can you share how you managed it? I also have issues regarding the L6009 Labels

We gave up with Snipe and just used the Avery website. As it works perfectly for their products: https://www.avery.com/software/design-and-print/

<blockquote><img src="https://www.avery.com/app/images/logos/avery-logo-share.jpg" width="48" align="right"><div><strong><a href="https://www.avery.com/software/design-and-print/">Free Label Printing Software - Avery Design & Print</a></strong></div><div>With Avery Design & Print, creating quality personalized products has never been easier. Just choose a template, customize your product and then print it yourself or let us print it for you. Even better, you can do it from any device, anytime, anywhere.</div></blockquote>

**Comment by Kaphalor** [comment]
Thanks for info, will give it a try!

**Comment by Godmartinz** [comment]
I just wanted to point out that we have added an alternative label engine that should solve your issues.

**Comment by freekeee** [comment]
Any ideas if this was ever resolved, other than sending us to a 3rd party site?
I'm attempting to print labels to Avery L7163 (14x2 labels on A4) and even when i manually enter the dimensions, the print output is way off!
Any ideas would be appreciated.

**Comment by snipe** [comment]
Hi there - this issue was closed in 2023. Please create a new issue and be sure to provide the following information:

- Version of Snipe-IT you're running. (If you didn't grab an official release, let us know which branch you pulled from.)
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error.
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is displayed in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable [on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `storage/logs/laravel.log` and your webserver's logs.
- Indicate whether or not you've manually edited any data directly in the database
- Indicate that you've read the rest of the [Getting Help documentation](https://snipe-it.readme.io/docs/getting-help) and [Common Issues](https://snipe-it.readme.io/docs/common-issues).

(When you reply to old, closed threads, it sends an email notification to everyone who ever participated in it, which can be pretty annoying to have happen on a thread that's been resolved for a while.)
